### ISSUE TITLE
Investigate Toolkit performance related to loading solutions

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-visual-studio#103]
> @awschristou I am loading directly into the solution. There are almost 34 projects within the solution. 
> I checked without loading solution and this time visual studio load fast but when I open solution, it gives me the same alert again. 
> ![Annotation 2020-06-12 145817](https://user-images.githubusercontent.com/24789996/84490900-3834c400-acbd-11ea-8b3a-5838a77bee3c.png)

_Originally posted by @M-Imtiaz in https://github.com/aws/aws-toolkit-visual-studio/issues/14#issuecomment-643187894_

I suspect this is related to adding the dotnet global tooling into projects. This scenario involving 34 projects in a solution likely illustrates the performance. (see original issue for attached log as well)

**Comment by awschristou** [comment]
Hi  @M-Imtiaz , if we produced a preview build of the toolkit containing improvements for solution load times, would you be interested in trying it out?

**Comment by M-Imtiaz** [comment]
@awschristou I would love to try out. If you guys need any logs etc, I will provide here

**Comment by awschristou** [comment]
I have made a test build of the toolkit containing a fix that should improve your Visual Studio startup time, by only trying to set up the Lambda Testing tool only once.

If you have a chance to try it out, I would be interested in hearing how it worked for you.
* Download [AWSToolkitPackage.zip](https://github.com/aws/aws-toolkit-visual-studio/files/5171186/AWSToolkitPackage.zip) (MD5 Checksum: ff17226f909a45284d5b1ca8d0fcf39c)
* Unzip the file. It contains the toolkit as a .vsix file
* Close down your running Visual Studio instances
* double click the .vsix file to install it
* after the VSIX installer completes, re-launch Visual Studio and try out this version of the toolkit

(cc: @M-Imtiaz - if you are able to load a solution with many projects a couple of times, I would be interested in seeing the log file afterwards )

**Comment by M-Imtiaz** [comment]
@awschristou I have downloaded and installed the extension the day you mentioned me here. I spent a few days checking. It is really working well. Never got that alert from the visual studio again. I am attaching the log file. I also suggested this extension to my friend who was also facing the same issue and he is also satisfied with this preview version. Solution loading is much faster now
[log.txt](https://github.com/aws/aws-toolkit-visual-studio/files/5187036/log.txt)

**Comment by jwarhurst** [comment]
Working great!

**Comment by awschristou** [comment]
Thank you for trying out the test build @M-Imtiaz and @jwarhurst !

From that log, it looks like the toolkit's impact on solution load times was reduced from 20sec+ to 2-10sec. This change looks viable.

**Comment by awschristou** [comment]
v1.19.0.0 of the Toolkit is now available. When solutions load, dotnet tooling is set up once per solution instead of once per project, which should make larger solutions load notably quicker.
