### ISSUE TITLE
Problems populating the bucket dropdown in the Lambda deploy wizard

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-visual-studio#106]
A Lambda deploy wizard problem was reported:

> I changed some code and tried to deploy again using the serverless.template publishing mechanism. Even though it saved my stack and bucket name in its config file, it wouldn't load those into the dropdown fields. In fact, I couldn't even type my bucket name into the bucket field - it was just blank with no items in the dropdown, and wouldn't allow keyboard input. After restarting VS, this worked.

**Comment by mtttcgcg** [comment]
This appears to occur if the role's token expires between opening of the publish to aws screen. We use a script to renew our tokens into the local aws creds file on our machine. Even if this external script has been run and the token is valid, the VS plugin won't see that new token and instead blanks out the dropdowns:

![image](https://user-images.githubusercontent.com/19497375/85158941-afb0a900-b211-11ea-817f-2055fa7104d0.png)

These two dropdowns are not editable - can't type inside.
The only workaround is to restart visual studio. Then it gets the latest token and works.

**Comment by awschristou** [comment]
Thank you for the additional context @mtttcgcg , this helps to dig in to this a little further.

Out of curiosity, how frequently is your token renewal occurring?

As a possible workaround, have you considered setting up a [credential_process](https://docs.aws.amazon.com/credref/latest/refdocs/setting-global-credential_process.html) style of credential?

**Comment by mtttcgcg** [comment]
Our tokens expire after 1 hour. We use https://github.com/Nike-Inc/gimme-aws-creds to get the token and save it to the %HOME%\.aws\credentials file. I guess it would be pretty easy to convert that output to the JSON that credential_process looks for. Let me investigate that, thanks!

**Comment by awschristou** [comment]
I would be interested in hearing if you have success with that. Also, we have a feature request for SSO/SAML (#98). If that would help you, please take a moment to add a reaction to the issue's initial post, as that helps us measure interest in requested features.

**Comment by awschristou** [comment]
Hi @mtttcgcg , version 1.21.0.0 of the toolkit is now available. It has support for AWS SSO based credentials, which you may be interested in trying out. 

Additionally, when the modal publish dialogs come up, the Toolkit now makes an attempt to validate the credentials. This would help in the case where the credentials have expired before the dialog tries to load resources when it is initially displayed. I'd be interested in hearing if this helps you out.

**Comment by awschristou** [comment]
I'm going to close this issue since it hasn't received any updates in a while, and the Toolkit has gained additional credentials support since this issue was filed. If the problem persists, please re-open the issue or file a new one, and share details about the behavior you are seeing.
