### ISSUE TITLE
"Security group does not exist" error when deploying to Beanstalk

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-visual-studio#107]
Deploying a .NET Core application to Linux, using an RDS security group can fail with a "Security group does not exist" error:

![image(14)](https://user-images.githubusercontent.com/39839589/86062129-df835c00-ba1c-11ea-83c9-9875a46d3cc2.png)

Repro steps:
* Make an RDS instance on the default vpc
* deploy a .NET Core application to Beanstalk, Linux target, and select the RDS instance security group
* deploy fails

Notes:
* the security group does get created on the account
* this does not happen if deploying to a Windows target
* this does not happen if referencing an RDS security group where the RDS instance is in a non-default VPC

**Comment by karamo-aws** [comment]
Is there an update on the ticket ? Any idea of a timeline ?

**Comment by altalibs** [comment]
I am also waiting for this to be resolved. Thank you!

**Comment by awschristou** [comment]
A fix for this has been released with v1.18.1.0 of the Toolkit.
