### ISSUE TITLE
Cannot select Launch Type as Fargate with Scheduled Task in VS AWS toolkit With US-WEST-2

### ISSUE THREAD

**Issue by AmmarBashir** [aws/aws-toolkit-visual-studio#110]
**Expected**
Allow deploying ECS scheduled fargate task with AWS toolkit

**Reproduction Steps**
Right-click on project on solution explorer and select Publish to AWS Container
Select Region US (Oregon) and Set Deployment target to 'Scheduled task on ECS Cluster'
Click Next and Launch Type dropdown is disabled with value set to EC2

**Logs**
Shows Under Launch Type 'Fargate is currently not supported in this region. Fargate is supported in the regions: us-east-1, us-east-2, us-west-2, us-west-1, ca-central-1, eu-west-1, eu-central-1, eu-west-2, op-southeast-1, ap-northeast-1, ap-southeast-2, ap-northeast-2, ap-south-1, cn-north-1'

**Environment**
AWS Toolkit Version: 1.18
OS Info: Windows 10 Build 18363
Build Environment Visual Studio 2019 16.4.5
Targeted .NET Platform: .NET Core 2.1.603

**Comment by rli** [comment]
Thanks for the report, I can reproduce this issue. This is currently in our queue, but there is no ETA for the fix yet.

**Comment by awschristou** [comment]
v1.20.1.0 of the Toolkit was released today, which includes fixes that allow scheduled Fargate-based Tasks to be deployed through the Toolkit.
