### ISSUE TITLE
 IP address could not be found.

### ISSUE THREAD

**Issue by shadyyehia** [aws/aws-toolkit-visual-studio#117]
The link is not downloadable, browser display the message :
amazonwebservices.gallerycdn.vsassets.io’s server IP address could not be found.

**Comment by awschristou** [comment]
Hi @shadyyehia , where are you seeing this message, and what actions were you performing that resulted in showing this message?

**Comment by awschristou** [comment]
Closing issue, please provide additional details if you are still having problems with the toolkit.
