### ISSUE TITLE
aws-ecs-tools-defaults.json saved incorrect Docker Repository name when contains slash (/)

### ISSUE THREAD

**Issue by anuith** [aws/aws-toolkit-visual-studio#123]
**Describe the bug**
The `tag` value in aws-ecs-tools-defaults.json saved an incorrect value when **Docker Repository** value contains slash

**To Reproduce**
Steps to reproduce the behavior
1. Create a `netcoreapp` project with container capability.
2. Configure AWS account profile with account that can push images to Amazon ECR.
3. Right click on the created project and select **Publish container to AWS...**.
4. On the **Publish container to AWS** dialog : Set **Docker Repository** to something like `imagegroup/imagename`.
5. Choose **Deployment Target**. e.g. `Push only the Docker image to Amazon Elastic Container Registry`.
6. Check **Save settings to aws-ecs-tools-defaults.json and configure project for command line deployment.**
7. Click **Publish** and wait for the publish completes.
8. Check the saved `aws-ecs-tools-defaults.json` file in the project.

**Expected behavior**
The `tag` value in `aws-ecs-tools-defaults.json` should be `imagegroup/imagename`.

**Screenshots**
![image](https://user-images.githubusercontent.com/623033/93566777-c3f27680-f9b7-11ea-9325-5bd74a9ea973.png)
![image](https://user-images.githubusercontent.com/623033/93566265-f6e83a80-f9b6-11ea-93bc-7e55fbeadeb6.png)

**Computer :**
- Windows Version : Windows 10 Pro
- Visual Studio Version : 16.7.0 Community
- AWS Toolkit for Visual Studio Version : 1.18.1.0

**Comment by justinmk3** [comment]
Thanks for reporting, confirmed!

**Comment by awschristou** [comment]
A fix for this issue was released today in v1.20.1.0. The Toolkit can now successfully deploy to Docker repositories containing a slash.
