### ISSUE TITLE
Renaming account profile throws error

### ISSUE THREAD

**Issue by luckerby** [aws/aws-toolkit-visual-studio#127]
**Describe the bug**
Opening AWS Explorer in Visual Studio and trying to edit one of the existing profile's name results in an `Object reference not set to an instance of an object` error, as seen in the screenshot below. The profile name is however successfully renamed, it's only that one has to close and reopen Visual Studio in order to view the change.

**To Reproduce**
1. Open AWS Explorer from Visual Studio's View menu
2. Select a profile and click the "Edit Profile" icon
3. Change the profile name to something else
4. Enter the account number and click "Ok"

**Expected behavior**
The profile to be renamed silently.

**Screenshots**
![image](https://user-images.githubusercontent.com/31319583/96431098-b8d77400-120b-11eb-8692-a45ff26181f2.png)

**Computer (please complete the following information):**

- Windows Version: Windows 10 1909
- Visual Studio Version: 16.5.0 Preview 5
- AWS Toolkit for Visual Studio Version: 1.18.1.0

**Comment by awschristou** [comment]
Thank you for reporting this @luckerby - I can confirm that I was able to reproduce this for a basic shared credentials profile (not a .NET Credentials profile)

**Comment by awschristou** [comment]
This issue has been addressed in more recent versions of the Toolkit (I believe version 1.21.0.0 and newer).
