### ISSUE TITLE
Federated identity cannot be used to browse in AWS Explorer

### ISSUE THREAD

**Issue by luckerby** [aws/aws-toolkit-visual-studio#128]
**Describe the bug**
Unsure this is really a bug, or just me not grasping the security concepts in AWS yet, but: trying to use a federated identity's access key (id and secret) within AWS Explorer in Visual Studio always results in an error when trying to browse resources.

**To Reproduce**
1. Have a pre-existing profile created in AWS Explorer
2. Go to the SSO screen and choose the "Command line or programmatic access"
3. Copy the access key id and secret, and paste them in the AWS Explorer profile
4. Try to browse (say EC2 instances for a region)

**Expected behavior**
The resources should be displayed.

**Screenshots**
What actually happens:
![image](https://user-images.githubusercontent.com/31319583/96639810-e7983c00-132a-11eb-8cfe-6eaf91c015f2.png)

**Computer (please complete the following information):**

- Windows Version: Windows 10 1909
- Visual Studio Version: 16.5.0 Preview 5.0
- AWS Toolkit for Visual Studio Version: 1.18.0.0

**Additional context**
Every time the federated identity is used to get the access key (id+secret), new values are generated. I'm assuming however that this is normal.
Part of a Fiddler trace is below, taken when trying to browse the EC2 instances, yet it doesn't really bring anything new:
![image](https://user-images.githubusercontent.com/31319583/96639849-f979df00-132a-11eb-880f-3664582dc294.png)

**Comment by kiiadi** [comment]
I'm assuming by Federated Auth - you're referring to SSO ? If so first-class support for this is on our roadmap.

**Comment by luckerby** [comment]
@kiiadi that is correct, SSO.

As it is on the roadmap, 2 questions if I may:
- When is a rough estimate for a first preview of the feature
- I'm using the .NET SDK, which I'm seeing that in turn relies on the profiles defined in AWS Explorer. Is there a workaround for getting the SDK working? (I realize this is out of the scope for this repo, so any pointer would be appreciated)

**Comment by awschristou** [comment]
Hi @luckerby , version 1.21.0.0 of the Toolkit contains support for AWS SSO based credentials.

Details can be found at:
* Blog post: https://aws.amazon.com/blogs/developer/introducing-aws-toolkit-for-visual-studio-support-for-aws-sso-and-assume-role-with-mfa/
* User docs: https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/sso-credentials.html

(This issue appears to be similar to #98 )
