### ISSUE TITLE
VisualStudio CloudFormation template editor shows key is invalid for this object

### ISSUE THREAD

**Issue by etoh91** [aws/aws-toolkit-visual-studio#129]
## Description
Visual Studio v1.18.1.0 for Cloudformation is throwing 'xxx key is invalid for this object" for "HttpParameters" and "QueryStringParameters" and any parameter under "QueryStringParameters" when trying to create EventBridge/Event Rules resource. Screenshot below: 

## Reproduction Steps
These are valid properties according to documentation for EventBridge/Event Rules (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Events.html). Similar issues for other scenarios:
1. https://github.com/aws/aws-sdk-net/issues/663
2. https://github.com/aws/aws-sdk-net/issues/133

---

**Screenshots**
![image](https://user-images.githubusercontent.com/74193507/98550969-c2805480-226a-11eb-86b8-f6f3e825bfd6.png)

- Windows Version:
- Visual Studio Version: 2017/2019
- AWS Toolkit for Visual Studio Version: v1.18.1.0

**Comment by normj** [comment]
I see the problem in the VS schema is targets is model as object instead of an array of objects. I'm working on making that change and get it published out.

**Comment by awschristou** [comment]
The CloudFormation validation was updated today. The next time Visual Studio is launched, the Toolkit should retrieve definition updates, which include the requested types.
