### ISSUE TITLE
Mock Lambda Test Tool not loaded when opening .sln from Explorer

### ISSUE THREAD

**Issue by lsgroi** [aws/aws-toolkit-visual-studio#134]
When launching Visual Studio by double clicking on an .sln file, the Toolkit does not load the Mock Lambda Test Tool.
If Visual Studio is opened first, and then I open a solution, the Test Tool is available.

(Original issue below)

---

An existing solution has a project in `<solution_dir>\src\<project_dir>`, once the solution is opened in Visual Studio the `launchSettings.json` file is not created and therefore the Mock Lambda Test Tool is not available for debugging.
If I move the project to `<solution_dir>\<project_dir>` the tool is available.
The project in VS is added to a solution folder but does not seem to impact.

**To Reproduce**

- Create a solution with AWS Lambda Project (C#)
- Remove the project from the solution
- Physically move project directory to `<solution_dir>\src\`
- Re-add the project to the solution in VS
- Close the solution
- Delete the directories `Properties`, `bin`, `obj` in the project's directory (simulating a fresh git clone)
- Open the solution
- The `launchSettings.json` file is not created, Mock Lambda Test Tool not available

**Expected behavior**
The `launchSettings.json` file is created, Mock Lambda Test Tool available

**Computer:**

- Windows Version: Windows 10 Enterprise 10.0.18363
- Visual Studio Version: 16.8.2
- AWS Toolkit for Visual Studio Version: 1.20.0.0

**Comment by awschristou** [comment]
Hi @lsgroi , I wasn't able to reproduce your issue here. Is there a chance that your solution is in a location on your computer that has limited write permissions?

If you have a chance, please share your Toolkit log from `%localappdata%\AWSToolkit\logs\visualstudio\log.txt`, it might offer some clues.

**Comment by lsgroi** [comment]
@awschristou the only error I see in the file is this, which shouldn't cause the issue

```
2020-12-03 10:34:36,014 [1] ERROR Amazon.AWSToolkit.Navigator.Node.AWSViewModel - Error setting up credential file watcher
System.ArgumentException: The directory name C:\Users\Luca\.aws is invalid.
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at Amazon.AWSToolkit.Navigator.Node.AWSViewModel.SetupSharedCredentialFileMonitoring()
```

Could you please try to with this sample solution [AWSLambda1.zip](https://github.com/aws/aws-toolkit-visual-studio/files/5635479/AWSLambda1.zip)

I have tried on two different machines so it shouldn't be a permission problem. The only way I can get the Mock Lambda Test Tool to become available is to unload and reload the project while Visual Studio is open.

**Comment by awschristou** [comment]
Hi @lsgroi , I have revised the issue text to reflect that the Test tool is available when you open a solution within Visual Studio, but it is not available when loading Visual Studio by double clicking on solution files from the Windows Explorer. Please let me know if that does not accurately reflect your situation and I'll file that as a separate issue.

**Comment by awschristou** [comment]
Version 1.21.3.0 of the Toolkit is now available, which will load the Lambda Test Tool even if Visual Studio is loaded directly into a solution.
