### ISSUE TITLE
AWSToolkitPackage package did not load correctly for VS2019 Enterprise

### ISSUE THREAD

**Issue by charles310** [aws/aws-toolkit-visual-studio#138]
![image](https://user-images.githubusercontent.com/76484592/102898983-443be280-44a5-11eb-917a-852cad2d2fea.png)

Upgraded my Visual Studio from VS2017 to VS2019 and when download and installed the new version of the toolkit after that it stop working.

Information in the ActivityLog:

```
    <time>2020/12/22 14:27:17.583</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>see formatted contents below</description>
    <guid>{12ED248B-6D4A-47EB-BE9E-8EABEA0FF119}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
```

Description contents:
```
CreateInstance failed for package [AWSToolkitPackage]Source: ';mscorlib'; Description: Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for ';Amazon.AWSToolkit.Settings.ToolkitSettings'; threw an exception.
 ---> System.MissingMethodException: Method not found: ';Amazon.Runtime.Internal.Settings.IPersistenceManager Amazon.Runtime.Internal.Settings.PersistenceManager.get_Instance()';.
   at Amazon.AWSToolkit.Settings.SettingsPersistence..ctor()
   at Amazon.AWSToolkit.Settings.ToolkitSettings.Initialize()
   at Amazon.AWSToolkit.Settings.ToolkitSettings..cctor()
   --- End of inner exception stack trace ---
   at Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)System.TypeInitializationException: The type initializer for ';Amazon.AWSToolkit.Settings.ToolkitSettings'; threw an exception.
 ---> System.MissingMethodException: Method not found: ';Amazon.Runtime.Internal.Settings.IPersistenceManager Amazon.Runtime.Internal.Settings.PersistenceManager.get_Instance()';.
   at Amazon.AWSToolkit.Settings.SettingsPersistence..ctor()
   at Amazon.AWSToolkit.Settings.ToolkitSettings.Initialize()
   at Amazon.AWSToolkit.Settings.ToolkitSettings..cctor()
   --- End of inner exception stack trace ---
   at Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage..ctor()System.MissingMethodException: Method not found: ';Amazon.Runtime.Internal.Settings.IPersistenceManager Amazon.Runtime.Internal.Settings.PersistenceManager.get_Instance()';.
   at Amazon.AWSToolkit.Settings.SettingsPersistence..ctor()
   at Amazon.AWSToolkit.Settings.ToolkitSettings.Initialize()
   at Amazon.AWSToolkit.Settings.ToolkitSettings..cctor()
```

- Windows Version: 10
- Visual Studio Version: VS2019 Enterprise 16.8.3
- AWS Toolkit for Visual Studio Version: 1.20

**Comment by gsweetwood** [comment]
Hi @charles310,

When installing VS2019, did you select any workloads or were none chosen? Here's a screenshot of the part of the process I'm referring to:
![VS2019 workloads](https://user-images.githubusercontent.com/25124281/103103666-764d6180-45d7-11eb-9205-0a9e9871cb82.png)

**Comment by charles310** [comment]
Can someone please help me with this?

**Comment by awschristou** [comment]
Thank you for reporting this issue. I've formatted the log output in your issue description to make it easier to look inti

**Comment by awschristou** [comment]
Hi @charles310 , have you tried fully uninstalling the Toolkit from both VS 2017 and VS 2019 (you might have to do the uninstall from each VS version separately) prior to installing the toolkit into both? At this time, the same Toolkit extension can be installed into both VS versions, however the extension internals may have gotten confused if it was installed into VS 2019 sometime after it was installed into VS 2017.

**Comment by charles310** [comment]
Hi @awschristou I actually uninstall both VS2017 and VS2019 and install again the VS2019 and the toolkit but I still encountering the same issue.

**Comment by awschristou** [comment]
@charles310 I'm guessing that the Toolkit is trying to use older versions of the AWS SDK than what it needs. I've made a test build for you to try out, which should try to reference the newer AWS SDK versions.

Can you please download and install [AWSToolkitPackage.zip](https://github.com/aws/aws-toolkit-visual-studio/files/5771535/AWSToolkitPackage.zip), and see if this version of the Toolkit starts up for you?

**Comment by compelx** [comment]
@awschristou Windows 10, fresh install of Version 16.8.3, tried the zip you attached -- extension installed just fine and I'm able to create projects with it.

**Comment by charles310** [comment]
Hi @awschristou I tried removing first the existing toolkit and install the zip you provided but still encountering the same issue :(

![image](https://user-images.githubusercontent.com/76484592/103725577-dac5e300-5011-11eb-89db-9d02ec8aa45f.png)

Attaching here the install log for your checking.. [dd_VSIXInstaller_20210106111512_4950.log](https://github.com/aws/aws-toolkit-visual-studio/files/5773767/dd_VSIXInstaller_20210106111512_4950.log)

**Comment by awschristou** [comment]
Hi @charles310 , based on the error message, the Toolkit has having problems locating `IPersistenceManager`, which is available in more recent versions of the `AWSSDK.Core` module. I suspect your system has a component installed that has registered older versions of the AWS SDK, and the Toolkit is somehow using these versions of the SDK.

Could you please help us diagnose this?
* With the AWS Toolkit installed, open two instances of Visual Studio 2019
* Use the second instance of VS2019 to attach a debugger to the first instance:
  * In the second instance, go to **Debug** > **Attach to Process...**
  * select the first instance of Visual Studio, it is called **devenv.exe**
  * wait for the debugger to attach
* From the **Debug** menu, select **Windows** > **Modules**
* when the Modules panel opens, search for **AWSSDK**
* Share a screenshot of this panel. I'm interested in seeing the Path and Version columns at a minimum. I'd like to see all of the reported dll's, particularly AWSSDK.Core.dll

This is what mine looks like for example:
![image](https://user-images.githubusercontent.com/39839589/104052229-3e7d1700-519e-11eb-9c38-0233a9bbdaaa.png)

**Comment by charles310** [comment]
Hi @awschristou Please see screenshot below. I only have this result.

![image](https://user-images.githubusercontent.com/76484592/104152167-bdca4f00-5419-11eb-81e4-1169937343f9.png)

**Comment by awschristou** [comment]
Thank you @charles310 -- somehow the AWSSDK.Core module has been installed into your system's Global Assembly Cache (GAC). If you are aware of a tool or utility that you've installed that may have put that there, uninstalling that tool would remove this DLL from the GAC. Otherwise, Microsoft has some instructions on [how to remove an assembly from the GAC](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-remove-an-assembly-from-the-gac). If you do the latter, the tool that put the assembly into the GAC may break.

Please remove the assembly one of the two ways, and then see if you're able to successfully start the toolkit.

**Comment by raymondpunzalan10** [comment]
Hi @awschristou - sorry I haven't responded to this but the toolkit works now after I remove it from the GAC folder.
Thanks a lot for helping me on this.
we can mark this resolve already. Thanks!

**Comment by charles310** [comment]
Hi @awschristou sorry I havent replied to you but the ToolKit now works after I remove it in the GAC Folder.
Thank you for helping me on this.
I will close this bug. Thanks!
