### ISSUE TITLE
The AWS toolkit for Visual Studio does not get installed for Visual Studio 2019 16.8.3. Fails with an error - "This extension is not installable on any currently installed products".

### ISSUE THREAD

**Issue by saurabhbajaj2309** [aws/aws-toolkit-visual-studio#139]
**Describe the bug**
When trying to install the AWS toolkit for Visual studio (for Visual Studio Enterprise 2019 v16.8.3), the extension ends up in an error mentioning  - "This extension is not installable on any currently installed products".

**To Reproduce**
Steps to reproduce the behavior
example:
1. Double click and run the extension AWSToolkitPackage.vsix.
2. Wait for a few seconds. The installation ends up in an error.

**Expected behavior**
The installation should go through successfully.

**Screenshots**

**Computer (please complete the following information):**

- Windows Version: Windows 10 Enterprise (version 10.0.18363 Build 18363)
- Visual Studio Version:  2019 v16.8.3
- AWS Toolkit for Visual Studio Version:  (v 1.20.0.0) Downloaded latest from link https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2017

**Additional context**

![AWS_Toolkit_Error](https://user-images.githubusercontent.com/13097171/103175809-dae81500-4892-11eb-9d16-eb7a51c56793.JPG)

**Comment by shruti0085** [comment]
Thanks for reaching out. When Visual Studio is closed, could you please retrieve your log file from %localappdata%\AWSToolkit\logs\visualstudio and attach it?

**Comment by awschristou** [comment]
Hi @saurabhbajaj2309 in the screenshot you posted of the VSIX installer there is a "View Install Log" link at the bottom.

Can you please attach the contents of this log when your install of the Toolkit extension fails?

**Comment by awschristou** [comment]
I am closing this issue since there hasn't been a response. @saurabhbajaj2309 if you are able to provide an install log, please re-open the issue and attach it.
