### ISSUE TITLE
AWS sso support

### ISSUE THREAD

**Issue by MatthewVines** [aws/aws-toolkit-visual-studio#141]
**Is your feature request related to a problem? Please describe.**
When using AWS SSO profiles aws toolkit for visual studio will not connect. returning 'The security token included in the request is invalid.

**Describe the solution you'd like**
I would like the extension to use my credentials and connect to AWS using aws sso.

**Describe alternatives you've considered**
Somehow setting my aws credentials in a broader context
ie eval "$(aws2-wrap --profile myprofile --export)"
This has been unsuccessful

**Additional context**
https://docs.aws.amazon.com/credref/latest/refdocs/setting-global-sso_start_url.html#setting-sso_start_url-sdk-compat

**Comment by awschristou** [comment]
Thank you for reaching out @MatthewVines . This issue is a duplicate of #98. Please add a reaction to that issue - it helps us know how much interest there is for new functionality.
