### ISSUE TITLE
Unable to deploy .NET 5 Core Web API in container 

### ISSUE THREAD

**Issue by alexgurman** [aws/aws-toolkit-visual-studio#145]
**Describe the bug**
On trying to follow https://aws.amazon.com/blogs/developer/net-5-aws-lambda-support-with-container-images/ instructions for deploying ASP NET Core 5 application with container, I get an error:
docker build: image operating system "linux" cannot be used on this platform, see below.

Created IAM Role ecs_execution_AWSServerless1
Attach policy PowerUserAccess to role ecs_execution_AWSServerless1
Created IAM role arn:aws:iam::593380097378:role/ecs_execution_AWSServerless1 with managed policy PowerUserAccess
Waiting for new IAM Role to propagate to AWS regions
Inspecting Dockerfile to figure how to build project and docker image
Executing docker build
... invoking 'docker build', working folder 'C:\mine\Study\Container\Serverless\AWSServerless1\AWSServerless1, docker file C:\mine\Study\Container\Serverless\AWSServerless1\AWSServerless1\Dockerfile, image name awsserverless1:latest'
... docker build -f "C:\mine\Study\Container\Serverless\AWSServerless1\AWSServerless1\Dockerfile" -t awsserverless1:latest .
... docker build: Sending build context to Docker daemon  768.5kB
... docker build: Step 1/3 : FROM public.ecr.aws/lambda/dotnet:5.0
... docker build: 5.0: Pulling from lambda/dotnet
... docker build: image operating system "linux" cannot be used on this platform
Error executing "docker build"
Error while deploying ECS Service to AWS: Unknown
Attempting to clean up any ELB resources created for the failed deployment
ECS Service deployment failed

**To Reproduce**

**Comment by awschristou** [comment]
Hi @alexgurman , can you check if your Docker Desktop is set to using Windows Containers? If so, you'll want to switch it to use Linux containers and try deploying again. The base lambda dotnet images (eg: `public.ecr.aws/lambda/dotnet:5.0`) are linux based.

**Comment by awschristou** [comment]
I am closing this issue as guidance. If the suggestion in https://github.com/aws/aws-toolkit-visual-studio/issues/145#issuecomment-779391795 does not address the problem, please re-open and provide additional details.

**Comment by alexgurman** [comment]
I can't run Linux containers on my windows machine

**Comment by awschristou** [comment]
Have you tried switching your Docker Desktop to use Linux containers? https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

**Comment by alexgurman** [comment]
tried, no difference
