### ISSUE TITLE
Not able to install AWS toolkit for Visual Studio 2019 (Version 16.8.3)

### ISSUE THREAD

**Issue by saurabhbajaj2309** [aws/aws-toolkit-visual-studio#148]
**Computer (please complete the following information):**

- Windows Version: Windows 10 Enterprise (10.0.18363)
- Visual Studio Version: 2019 (Version 16.8.3)
- AWS Toolkit for Visual Studio Version: 16.8.3036

**Install log**

**Comment by saurabhbajaj2309** [comment]
[dd_VSIXInstaller_20210321191227_7128.log](https://github.com/aws/aws-toolkit-visual-studio/files/6177538/dd_VSIXInstaller_20210321191227_7128.log)
![Error](https://user-images.githubusercontent.com/13097171/111907444-4f3de900-8a7b-11eb-90b9-166e557d6e59.JPG)

**Comment by awschristou** [comment]
Hi @saurabhbajaj2309 , I see in the log it says 
```
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
```

Are you able to successfully install other Visual Studio extensions? Something you might want to try is to open the Visual Studio Installer (this should be in your start menu), and try to Repair your Visual Studio instance, as well as Update it to the latest version. Then reboot your system and try to install the AWS Toolkit extension again.

**Comment by awschristou** [comment]
There has not been any response, so I am closing this issue. If you have additional details, please re-open it.
