### ISSUE TITLE
CloudFormation Template schema validation doesn't recognize *PolicyId for CloudFront CacheBehaviors

### ISSUE THREAD

**Issue by carlin-q-scott** [aws/aws-toolkit-visual-studio#149]
**Describe the bug**
The SAM Template schema validation doesn't recognize CachePolicyId or OriginRequestPolicyId for CloudFront CacheBehaviors

**To Reproduce**

1. Create a new SAM project
2. Open serverless.template
3. Add a new resource of `"Type": "AWS::CloudFront::Distribution"`
4. Set the DefaultCacheBehavior using the AWS Managed Policy Ids as required by CloudFormation.

Example CloudFront Distribution config:
```json
    "CFDist": {
      "Type": "AWS::CloudFront::Distribution",
      "Properties": {
        "DistributionConfig": {
          "DefaultCacheBehavior": {
            "TargetOriginId": "Api",
            "ViewerProtocolPolicy": "redirect-to-https",
            "AllowedMethods": [ "GET", "HEAD" ],
            "CachePolicyId": "658327ea-f89d-4fab-a63d-7e88639e58f6",
            "OriginRequestPolicyId": "acba4595-bd28-49b8-b9fe-13317c0390fa"
          }
        }
      }
    }
```

**Expected behavior**
I shouldn't have errors listed in my template file or the Error List window.

**Computer (please complete the following information):**

- Windows Version: 10 Pro 20H2
- Visual Studio Version: 2019 16.8.3
- AWS Toolkit for Visual Studio Version: v1.20.1.0 (2021-01-21)

**Comment by awschristou** [comment]
The CloudFormation validation was updated today. The next time Visual Studio is launched, the Toolkit should retrieve definition updates, which include the requested types.
