### ISSUE TITLE
The 'AWSToolkitPackage' package did not load correctly - error after install

### ISSUE THREAD

**Issue by petervhristov** [aws/aws-toolkit-visual-studio#15]
I downloaded the AWS toolkit for Visual Studio 2017 and installed it. I received a message that the install was successful. Then I opened Visual Studio and I get an error: 

![image](https://user-images.githubusercontent.com/44411862/50526120-f8b8ee80-0aad-11e9-9f31-ce74d9003fb0.png)

I get the same message when I try to open the AWS toolkit from the VS menu (View). 

## Your Environment
I have VS 2017 Professional, version 15.9.4 . 

I am attaching the install log. 
[VSIXInstaller_ce1bf8e2-6c7b-4a84-b0ba-1e8fc768f3d6.log](https://github.com/aws/aws-sdk-net/files/2715566/VSIXInstaller_ce1bf8e2-6c7b-4a84-b0ba-1e8fc768f3d6.log)

And the activity log referenced in the error.

[ActivityLog.txt](https://github.com/aws/aws-sdk-net/files/2715576/ActivityLog.txt)

**Comment by AdhaSahar** [comment]
Any update on this? Same problem happening with visual studio 2019

**Comment by RT4U** [comment]
Same issue here.

**Comment by awschristou** [comment]
A fix is queued up for situations where the ActivityLog contains the following contents:

```
Source: &apos;EnvDTE&apos; Description: Error HRESULT E_FAIL has been returned from a call to a COM component.&#x000D;&#x000A;System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.&#x000D;&#x000A;   at EnvDTE.Events.get_DebuggerEvents()&#x000D;&#x000A;   at Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage.Initialize()&#x000D;&#x000A;
```

As a workaround, you can install a debugger into Visual Studio as follows:
* Launch the Visual Studio Installer
* Modify your VS installation
* Click the Individual components tab
* Under the "Development activities" section, check "C# and Visual Basic"
* Install the checked components

**Comment by sanakalam** [comment]
The same issue I am facing is there any solution to resolve it?

**Comment by sanakalam** [comment]
Update your VS. add/remove program --> vs --> change/update.
It works for me.

**Comment by awschristou** [comment]
A fix for this is now available in v1.17.1.0 of the toolkit

**Comment by AmritanshuAVerma** [comment]
Hi , I am facing the same issue and i have tried all the methods mentioned above ,including cleaning the folders but nothing works for me, any help will be appriciated.

**Comment by danteMesquita** [comment]
Guys, it worked for me just create a folder like this:
c:/Users/yourUser/.aws

**Comment by awschristou** [comment]
Hi @AmritanshuAVerma and @danteMesquita , this issue relates to a different failure. You might be referring to the problem mentioned in #152 , which a fix was released for today. Please try that out, and file a new issue if you are encountering any problems.
