### ISSUE TITLE
Error running on EC2: Error loading AWS profiles: The Encrypted store is not available.

### ISSUE THREAD

**Issue by grausolutions** [aws/aws-toolkit-visual-studio#151]
**Is your feature request related to a problem? Please describe.**

Currently AWS Toolkit is not supported on Windows 2016 operating system.

Current Prerequisites: Run a supported operating system: Windows 10, Windows 8, or Windows 7.

**Describe the solution you'd like**

We have many developers working on EC2 instances with Visual Studio installed, (allows us to use instances profiles with certain permissions rather than IAM Users.)

**Describe alternatives you've considered**

Due to Windows servers not being supported we no longer using AWS Toolkit for Visual Studio.

**Comment by awschristou** [comment]
Hi @grausolutions thank you for reaching out. Are you able to install the Toolkit into Visual Studio successfully, or is the request that you would like to use the EC2 instance role in Visual Studio instead of setting up an profile in the shared credentials files?

**Comment by grausolutions** [comment]
I am able to install Toolkit into Visual Studio successfully, but when I open Visual Studio I get the following error:

`Error loading AWS profiles: The Encrypted store is not available. This may be due to use of a non-Windows operating system or Windows Nano Server, or the current user may not have its profile loaded.`

I get the above message when I open Visual Studio (after installing the AWS Toolkit), I also get the same message when I try to add a new profile using the AWS Toolkit UI.

Lastly, having the AWS Toolkit load EC2 Instance credentials from the EC2 Instance metadata would be amazing, this will eliminate the need of IAM Users which a lot of company try to avoid (security risk)

**Comment by grausolutions** [comment]
I forgot to add that we are already using **EC2 instance metadata** for credentials resolution on Visual Studio.

AWS documentation
https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html

**Comment by awschristou** [comment]
When you get the "The Encrypted store is not available", are you still able to use the Toolkit (for example with the shared credentials files), or is it fully non-functional?

> Lastly, having the AWS Toolkit load EC2 Instance credentials from the EC2 Instance metadata would be amazing, this will eliminate the need of IAM Users which many companies try to avoid (security risk).

This sounds very handy, we'll have to investigate this.

**Comment by grausolutions** [comment]
When you get the "The Encrypted store is not available", are you still able to use the Toolkit (for example with the shared credentials files), or is it fully non-functional?

It is completely non-functional, even though we have a config file with multiple profiles and it does not pick any profiles.

**Comment by awschristou** [comment]
> It is completely non-functional, even though we have a config file with multiple profiles and it does not pick any profiles.

Thank you for letting us know. Ideally, the Toolkit would still be operational, just not referencing the encrypted store if that cannot be accessed. This gives us some information on where to investigate.

**Comment by shruti0085** [comment]
Hi @grausolutions, could you please share the specifications about your development environment below?
OS Info: eg. Windows 10
VS Version: eg. Visual Studio 2019 Community
EC2 AMI : eg. Microsoft Windows Server 2019 Base
Any other specifics would also be helpful for us to reproduce the issue and investigate it further.

**Comment by grausolutions** [comment]
Hi @shruti0085 let me know if any other information about my environment is required.

VS Version:  Visual Studio 2019 Professional
EC2 AMI :  Microsoft Windows Server 2016 Base

**Comment by shruti0085** [comment]
Hi @grausolutions , thanks for the quick response. Just wanted to confirm if you are using the latest version of the toolkit i.e 1.21.1.0?

**Comment by grausolutions** [comment]
> Hi @grausolutions, thanks for the quick response. Just wanted to confirm if you are using the latest version of the toolkit i.e 1.21.1.0 and if you have administrator access to the files on your system?

Yes, we recently updated the toolkit to the latest version hopping it would help.

**Comment by shruti0085** [comment]
Unfortunately I was unable to reproduce the issue logged in as an admin user with an EC2 Windows Instance based on Windows 2016 Server Base image and latest version of the toolkit installed in VS2019 Professional.

I would like to see if other AWS tooling (e.g. AWS Tools for Powershell) has a similar issue accessing the file. Can you try running this command from a powershell window:
`Set-AWSCredential -AccessKey akey -SecretKey skey -StoreAs myProfileName`
 and check if the sample profile ("myProfileName") can be found within the file in the location: `%USERPROFILE%/AppData/Local/AWSToolkit/RegisteredAccounts.json`?

**Comment by awschristou** [comment]
Hi @grausolutions , we weren't able to reproduce your issue, but we have made a change that keeps the Toolkit startup stable when there is a problem loading from different credential sources (like the SDK Store). If you have a chance to try out the fix, we've made a test build of the Toolkit, and would be interested in knowing if this helps you out.

[AWSToolkitPackage.zip](https://github.com/aws/aws-toolkit-visual-studio/files/6422839/AWSToolkitPackage.zip)
Sha 384: `9c2fbb98a8fc437bd9a21c151d94310bf295feb1d26fb77253a371bf08f680af5cbf34d9cbacd1a9f4d0197f7adf34d0`

**Comment by grausolutions** [comment]
Sure I can open it as a new issue, thank you!

**Comment by awschristou** [comment]
Version 1.21.2.0 of the Toolkit was released today, which disables loading credentials defined in the SDK Credential Store on startup if the Toolkit is unable to decrypt them. The error message should no longer occur on startup.
