### ISSUE TITLE
The 'AWSToolkitPackage' package did not load correctly - directory name is invalid

### ISSUE THREAD

**Issue by Lavidimus** [aws/aws-toolkit-visual-studio#152]
I've been using the AWS toolkit for a few days, I received the unfortunate 'package did not load correctly' error when loading Visual Studio this morning. Attached is the activity log. 

I have tried uninstalling, reinstalling the plugin. Uninstalling, reinstalling Visual Studio. I also have tried solutions found on the web with similar errors (however reported as fixed) just in case.

Any help would be appreciated. Thanks!

[ActivityLog.zip](https://github.com/aws/aws-toolkit-visual-studio/files/6359073/ActivityLog.zip)

_Update_: This particular issue applies to Version 1.21.0.0 of the Toolkit. See https://github.com/aws/aws-toolkit-visual-studio/issues/152#issuecomment-824950082 for a workaround.

**Comment by awschristou** [comment]
Hi @Lavidimus thank you for reaching out and sharing your log file. It appears that the latest version of the Toolkit (which we released yesterday) may have an issue trying to access a nonexistent folder.

As a workaround, before launching Visual Studio, can you try going to your `%userprofile%` folder and creating an empty folder called `.aws`? (In your case, it looks like the Toolkit is looking for a folder called `C:\Users\chris\.aws`

With this workaround, I would be interested in knowing if you are successful in starting up Visual Studio without seeing this error.

**Comment by JCADORE** [comment]
Hi @awschristou,

I had the same issue, and it worked when I create the .aws folder. Thanks!

**Comment by Lavidimus** [comment]
Can confirm that fixed it. Thanks!

**Comment by awschristou** [comment]
Thanks for the confirmation! I have re-opened this issue until we can release a fix for it.

**Comment by mr-esb** [comment]
Adding .aws folder under user's home directory didn't work for me. It had to be added under c:\repositories.

SetSite failed for package [AWSToolkitPackage]Source: 'System' Description: The directory name c:\repositories\.aws is invalid. System.ArgumentException: The directory name c:\repositories\.aws is invalid.   at System.IO.FileSystemWatcher..ctor(String path, String filter)   at Amazon.AWSToolkit.Credentials.IO.ProfileWatcher.InitializeWatchers(List`1 credentialFilePaths)   at Amazon.AWSToolkit.Credentials.IO.ProfileWatcher..ctor(List`1 credentialFilePaths)   at Amazon.AWSToolkit.Credentials.Core.SharedCredentialProviderFactory.SetupProfileWatcher()   at Amazon.AWSToolkit.Credentials.Core.ProfileCredentialProviderFactory.Initialize()   at Amazon.AWSToolkit.Credentials.Core.ToolkitCredentialInitializer.Setup(ICredentialProviderFactory factory)   at Amazon.AWSToolkit.Credentials.Core.ToolkitCredentialInitializer.SetupFactories()   at Amazon.AWSToolkit.Credentials.Core.ToolkitCredentialInitializer..ctor(ITelemetryLogger telemetryLogger, IRegionProvider regionProvider, IAWSToolkitShellProvider toolkitShell)   at Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage.<InitializeAsync>d__72.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__70.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)   at Microsoft.VisualStudio.Services.VsTask.GetResult()


Hope this helps.

**Comment by awschristou** [comment]
Version v1.21.1.0 has been released. We have made a fix that should allow the Toolkit to successfully start up even when the shared credentials folder is not found.
