### ISSUE TITLE
Error refreshing existing lambda functions

### ISSUE THREAD

**Issue by andredasilvauk** [aws/aws-toolkit-visual-studio#164]
The "Function Name" drop down is not populated in the "Upload to AWS Lambda" form and the log shows an error

**Steps to reproduce:**
1. Right-click project to deploy the lambda handler 
2. Click "Publish to AWS Lambda..." 
3. "Upload to AWS Lambda" form is displayed and the "Function Name" drop down is not populated
4.  The following error is added to the log file
2021-06-21 19:14:14,883 [1] ERROR Amazon.AWSToolkit.Lambda.ViewModel.UploadFunctionViewModel - Error refreshing existing lambda functions.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Amazon.Lambda.AmazonLambdaClient'.
   at Amazon.Runtime.AmazonServiceClient.ThrowIfDisposed() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AmazonServiceClient.cs:line 405
   at Amazon.Runtime.AmazonServiceClient.InvokeAsync[TResponse](AmazonWebServiceRequest request, InvokeOptionsBase options, CancellationToken cancellationToken) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AmazonServiceClient.cs:line 240
   at Amazon.Lambda.AmazonLambdaClient.ListFunctionsAsync(ListFunctionsRequest request, CancellationToken cancellationToken) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\Lambda\Generated\_bcl45\AmazonLambdaClient.cs:line 3698
   at Amazon.AWSToolkit.Lambda.ViewModel.UploadFunctionViewModel.<UpdateFunctionsList>d__187.MoveNext()

**Expected behavior**
"Function Name" drop down should be populated with the available Lambda Functions

**Screenshots**
![image](https://user-images.githubusercontent.com/73283501/122809288-d3e01380-d2c5-11eb-92e4-431d665d7119.png)

**Computer (please complete the following information):**

- Windows Version: Windows 10 OS Build 19043.985
- Visual Studio Version: 2019 - 16.10.2 
- AWS Toolkit for Visual Studio Version: 1.21.2.0

**Comment by shruti0085** [comment]
Hi @andredasilvauk , can you please share your entire log file located within %localappdata%\AWSToolkit\logs\visualstudio?
Also, can you confirm that you have existing zip based lambda functions in the account and region(us-east-1) specified above?

**Comment by andredasilvauk** [comment]
Hi @shruti0085,

Thank you for your response.

Please find attached the log file 
[log.txt](https://github.com/aws/aws-toolkit-visual-studio/files/6701843/log.txt)

As for the zip based lambda functions, I am not sure how to provide this information. I am, however, able to deploy them when using the zip package type, but have to be very careful to match all the environment variables, subnets and security groups in the template with the current lambda, or I end up altering the current lambda function values, which is why I am very interested in getting to the bottom of this issue.

Kind regards,

Andre da Silva

**Comment by shruti0085** [comment]
Looking at the toolkit logs it seems like it could be possible that the VS instance was not fully setup/initialized when the Publish To AWS Lambda menu item was selected/clicked. 
Could you re-try after waiting a couple of mins to allow full initialization of the toolkit and VS instance?

As for my question relating to zip based lambda, by navigating to AWS Explorer in the Visual Studio, selecting the credential and region you specified above, expand AWS Lambda and if you have any existing Lambda functions in that region, you should be able to see them under that node.

The Upload to AWS Lambda function dialog in the Function name dropdown lists names of Lambda functions matching type selected in the dialog that already exist in your account(specified with credentials) in the region selected through the Region dropdown. Taking the example of this image,  with PackageType selected to be Zip, the FunctionName dropdown would list all existing Zip based functions in your account in region N.Virginia. If you don't have any existing functions, the dropdown would be empty,

As for the altering lambda function behavior, can you provide a few more details/steps to reproduce it?
What is `template` referring to here, is it the `aws-lambda-tools-defaults.json` file?

**Comment by andredasilvauk** [comment]
I tried waiting and clicking the Publish To AWS Lambda menu item but unfortunately had the same result.

I have plenty of lambda functions in the AWS Explorer, also, from the AWS CLI, when viewing the lambdas, it shows that it is a ZIP package type.

I may have not have explained myself properly regarding the altering lambda function behavior. What I meant is that I need check the existing subnets, security groups and environment variables for the lambda I am planning to update, so I can match these values in the AWS Upload to AWS Lambda forms, or they will either be under incorrect subnets or security groups, or have incorrect environment variables

**Comment by awschristou** [comment]
Hi @andredasilvauk , I have a fix for a problem that was preventing the Function list from getting populated. Please try this build of the Toolkit, to see if it addresses your issue:

[AWSToolkitPackage.zip](https://github.com/aws/aws-toolkit-visual-studio/files/7573449/AWSToolkitPackage.zip) version 1.23.3.11190
Sha 384: `B8760E1683F81CE14FBE42DDA5E02DAC2349A0EE9FF1D0F237692B2E693B96C1FF13B947EC8314583FFE2B543C8F5939`

**Comment by andredasilvauk** [comment]
Hi @awschristou, thank you very much for your response.

I can confirm that the function list issue has been fixed.

Feel free to close the ticket.

Thank you for the fix.

Kind regards

**Comment by awschristou** [comment]
Thank you for the confirmation @andredasilvauk - this fix hasn't been released to the marketplace yet. I'll re-open this issue, and close it again when the fix has been released. (You're welcome to keep using the test build until then)

**Comment by awschristou** [comment]
A fix for this issue has been released with the 1.24.0.0 version of the Toolkit
