### ISSUE TITLE
CloudFormation Template validation reports errors for AWS::ECS::Service

### ISSUE THREAD

**Issue by maximilianor-tkf** [aws/aws-toolkit-visual-studio#166]
As of Toolkit v 1.21.2.0, the CloudFormation template validation marks the following AWS::ECS::Service fields as errors. The validation requires updating:

AWS::ECS::Service.DeploymentConfiguration.DeploymentCircuitBreaker

Thanks!

**Comment by awschristou** [comment]
We've updated the definitions used by the Toolkit. The next time you start Visual Studio, the Toolkit should download the updated definitions file, and these fields should no longer be classified as an error.
