### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by wessupermare** [aws/aws-toolkit-visual-studio#167]
## Update

The AWS Toolkit is now available for Visual Studio 2022! You can get this from the [Marketplace](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2022) or directly within the IDE's extension manager.

We're still working on bringing the full feature set into VS 2022. Until we do, the extension will have "Preview" in the name, and we will continue to update this issue with progress and updates. The features that are currently not available in 2022 are:
* ~Creating and loading CloudFormation projects~ (available in v1.23.3.0)
* ~Configuring access to CodeArtifact repos~ (available in v1.23.2.0)
* We are now considering removing the "Preview" flag in a future release.

---

## Original post

**Computer (please complete the following information):**

- Windows Version: Windows 11 version 21H2 (OS Build 22000.71)
- Visual Studio Version: 17.0.0 Preview 2.0
- AWS Toolkit for Visual Studio Version: 1.21.2.0

**Install log**

[dd_VSIXInstaller.log](https://github.com/aws/aws-toolkit-visual-studio/files/6833447/dd_VSIXInstaller_20210716142319_48d0.log)  

**Any other information**

I am aware this is currently an unsupported version, so I suppose this is simultaneously both a feature request _and_ an install issue. For now, having an unsupported release that accepts VS version 17 would be nice. Thank you!

**Comment by awschristou** [comment]
Thank you for making the request @wessupermare  - I have pinned this issue as the one that people can register interest in by adding a reaction to the original post.

AWS Toolkit support for Visual Studio 2022 is on the roadmap. Producing extensions for VS 2022 requires some architectural adjustments in order to accommodate changes in the VS extensibility model. We don't have a test build at this time, but will link them into this issue as they become available.

**Comment by ThomasVaccarini** [comment]
Please! I'm waiting for it!

**Comment by MikeJansen** [comment]
I'm on the bleeding edge, running VS 2022 preview daily for most of my development needs.  Also our entire infrastructure is in AWS and we're in the process of moving to serverless where we can.  Would LOVE to see this.

**Comment by awschristou** [comment]
Thanks for explaining your usage scenario @MikeJansen . I don't have a test build or an ETA at this time, but we have started to look into creating an extension that targets VS 2022.

**Comment by mk-ten** [comment]
This is now the only blocker for us for moving to VS2022. Is there an ETA for this yet?

**Comment by awschristou** [comment]
A new build has been posted into https://github.com/aws/aws-toolkit-visual-studio/issues/167#issuecomment-952174057 for anyone interested in checking it out.

**Comment by awschristou** [comment]
The AWS Toolkit is now available for Visual Studio 2022 on the [Marketplace](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2022) - please see the [original issue text](https://github.com/aws/aws-toolkit-visual-studio/issues/167#issue-946605976) for updates as we continue to onboard more of the previous Toolkit features into Visual Studio 2022.

**Comment by tgitchel** [comment]
When do you think a Lambda runtime for .NET 6.0 will be available in the AWS publish dialog?

**Comment by awschristou** [comment]
Currently the Lambda service does not have a .NET 6 managed runtime. I don't have information to share about timelines, but we would look to add .NET related runtimes into the Lambda publish dialog shortly after the Lambda service supports them.

In the meantime, we are looking into adding Lambda project blueprints for .NET 6 Image based Lambdas. More information about .NET 6 on AWS can be found at https://github.com/aws-samples/aws-net-guides/tree/master/RuntimeSupport/dotnet6#aws-lambda

**Comment by mk-ten** [comment]
Is there an ETA for CodeArtifact support?

**Comment by awschristou** [comment]
Thanks for letting us know that you're waiting on the CodeArtifact support @mk-ten . We've started looking into it this week, I'll post another comment when there is new information about that.

**Comment by awschristou** [comment]
Hi @mk-ten , version v1.23.2.0 of the Toolkit is now available, with CodeArtifact support.

**Comment by mk-ten** [comment]
Brilliant! Thanks @awschristou!

**Comment by awschristou** [comment]
The AWS Toolkit for Visual Studio 2022 is no longer marked as preview, with version 1.24.0.0. I will close this issue, and any new requests, issues, or comments can be filed as new issues in the repo.
