### ISSUE TITLE
Node.js Lambda Integration Should Save Configuration

### ISSUE THREAD

**Issue by ddrinka** [aws/aws-toolkit-visual-studio#17]
Moved from https://github.com/aws/aws-vsts-tools/issues/76

When deploying a .Net Lambda function the tool saves the configuration and will deploy with an identical configuration the next time. The Node.js Lambda integration does not support saving the configuration, requiring me to re-enter all parameters for each deploy.

Please add similar configuration saving functionality to the Node.js deployment functionality.

**Comment by awschristou** [comment]
Support for NodeJS Lambda development and deployment has been removed from the AWS Toolkit for Visual Studio, starting in version [1.50.0.0](https://github.com/aws/aws-toolkit-visual-studio/blob/main/CHANGELOG.md#15000-2024-03-28). See https://github.com/aws/aws-toolkit-visual-studio/issues/286 for more details.
