### ISSUE TITLE
How can I enable JSON syntax validation for the AWS::Serverless::StateMachine type?

### ISSUE THREAD

**Issue by macfarmw** [aws/aws-toolkit-visual-studio#171]
## The Question

I am using the AWS Toolkit for Visual Studio to create an AWS Serverless application. I found in the documentation that the type AWS::Serverless::StateMachine is one of the supported resource types for SAM templates. My serverless.template file uses JSON format because that it what was generated when I created the project in Visual Studio using the *AWS Serverless Application with Tests (.NET Core -C#)* project template. 
I have added a simple HelloWorld state machine using the documentation and the `dotnet lambda deploy-serverless` creates it successfully in AWS.

However, all of the properties for the StateMachine show as invalid with the red squiggly warnings.
![image](https://user-images.githubusercontent.com/10874510/128608352-acc78f68-7584-44f9-9bfb-c8d4f087cbc3.png)

Is there anything I can do to make the Visual Studio JSON editor recognize these properties?

### Environment

* Build Version:  AWS Toolkit 1.21.3.0 
* OS Info: Windows 10 
* Build Environment: Visual Studio 2019 16.10.0 
* Targeted .NET Platform:  .NET Core 3.1

---

**Comment by awschristou** [comment]
Hi @macfarmw , the Toolkit currently doesn't contain a definition for `AWS::Serverless::StateMachine`. I don't have a workaround for you. I will mark this as a feature request.

**Comment by macfarmw** [comment]
@awschristou 
OK. Thanks for the update. As a work around I have re-written my template in YAML. This works and does not give any syntax errors. There is no intellisense support like the JSON, but I was not really using that much anyway.

**Comment by awschristou** [comment]
`AWS::Serverless::StateMachine` is now supported by the Toolkit's intellisense support for json based CloudFormation templates.
