### ISSUE TITLE
Multi-site / Multi-platform

### ISSUE THREAD

**Issue by m1zun0** [aws/aws-toolkit-visual-studio#177]
Hi I have a .net web app which I'm publishing from VS2017 to my EC2 instance running IIS.
I recently added a .Net Core Web App which I'm also publ;ishing to the same instance.

When I publish the original app, the new core app gets deleted.
When I publish the core app, both sites remain stable.

I'm not sure how to change my original app publishing process to protect the core app.

Please help / advise if possible.

**Comment by m1zun0** [comment]
ps the .net core app is in VS2019

**Comment by awschristou** [comment]
The Toolkit does not support publishing more than one application to the same destination.

**Comment by m1zun0** [comment]
Well that's not strictly true, you can publish multiple apps using manifest.
