### ISSUE TITLE
CF Template Editor doesn't recognize S3 Filter rules

### ISSUE THREAD

**Issue by smcknight-ww** [aws/aws-toolkit-visual-studio#182]
**Describe the bug**
When configuring an S3 Event source for a Serverless function, the CloudFormation Template editor expects a string value for `S3KeyFilter`/`NotificationFilter` rather than the expected object.  

**To Reproduce**

1. Create a new project using the AWS Serverless Application template.
2. Select the "Detect Image Labels' blueprint, to setup a function with an S3 event source.
3. Add a `Filter` property to the S3 Event source, with an object value
4. Attempt to add an `S3Key` property within the `Filter` value object.
5. Note - the value defaults to a string, and throws validation errors when trying to replace with the proper object body (see screenshot)

**Expected behavior**
The Template editor should correctly recognize the JSON definition of the Filter property, on an S3 Event source for Serverless function resource.

**Screenshots**
![image](https://user-images.githubusercontent.com/25306305/138138166-10b00eec-d5ed-407a-908e-e51798fe464a.png)

**Computer (please complete the following information):**

- Windows Version: N/A
- Visual Studio Version: 16.11.3
- AWS Toolkit for Visual Studio Version: 1.22.0.0

**Additional context**
N/A

**Comment by awschristou** [comment]
We've updated the definitions used by the Toolkit. The next time you start Visual Studio, the Toolkit should download the updated definitions file, and these fields should no longer be classified as an error.
