### ISSUE TITLE
AWS SSO login results in multiple pop-windows spawning when Visual Studio window is left open and login expires

### ISSUE THREAD

**Issue by hcparr** [aws/aws-toolkit-visual-studio#190]
**Describe the bug**

If using an AWS SSO profile in the AWS Toolkit and the Visual Studio window is kept open for an extended amount of time where the SSO session expires, the AWS SSO Login process is tried over and over again.  This results in multiple pop-up windows being spawned on top of one another and requires each window to be closed individually before being able to access anything else within the Visual Studio window or even close the Visual Studio window itself.

**To Reproduce**

1. Use an AWS SSO profile in the AWS Toolkit and complete the SSO Login process
2. Leave the Visual Studio window open long enough for the SSO login to expire and the toolkit will attempt to connect multiple times resulting in multiple pop-up windows requesting to complete the AWS SSO Login process

**Expected behavior**

The toolkit should only attempt to start the SSO Login process once and only produce a single pop-up window.  Another alternative would be to not attempt to retry the SSO Login process when it expires and instead show a message in the Toolkit Explorer stating the user needs to retry the connection which would then trigger the SSO Login process.  It should not continue to retry and spawn multiple pop-up windows that require each one to be closed individually.

**Screenshots**

Example of the spawned pop-up windows 
![image](https://user-images.githubusercontent.com/59836423/139324665-8548c69c-4e37-466c-adef-33360aff4d04.png)

**Computer (please complete the following information):**

- Windows Version: Windows 10 OS Build 19043.1288
- Visual Studio Version: 2019 16.11.5
- AWS Toolkit for Visual Studio Version: 1.23.0.1

**Comment by awschristou** [comment]
In Toolkit v1.41.0.0 we've made some improvements that reduce the likeliness that multiple SSO prompts will appear. If you see this in newer Toolkit versions, please file a new issue with your repro steps and Toolkit log.
