### ISSUE TITLE
Can't open AWS Publishing panel - Unable to Publish to AWS

### ISSUE THREAD

**Issue by bdiaze** [aws/aws-toolkit-visual-studio#194]
Hi :(,

I just enabled the new publish to AWS feature, but when I try to open the AWS publishing panel, from the option "Publish to AWS (Preview feature)..." I get a popup saying "There was a problem trying to open the Publish dialog: AWS Toolkit was unable to verify the contents of the aws.deploy.cli tool. Restart Visual Studio to try again.", and I can't re-enable previous publishing experience because it's done from the same publishing dialog I can't open...

**To Reproduce**
1.- Enable new publish to AWS feature
2.- Open publish dialog by "Publish to AWS (Preview feature)..." option.
3.- Feel the pain because of the error message...

**Expected behavior**
Been able to get into the publishing panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/32801359/141515777-4e14e298-23cd-47bc-8e22-01632a3361e8.png)
![image](https://user-images.githubusercontent.com/32801359/141515816-02a2af70-a967-424d-bf38-00e313f7c55e.png)

**Computer (please complete the following information):**

- Windows Version: Windows 10 Education - Version 21H1
- Visual Studio Version: Microsoft Visual Studio Community 2019 Versión 16.11.1
- AWS Toolkit for Visual Studio Version: 1.23.1.0

**Additional context**
I tried to unistall/install the extension multiple times trying to get the previous publishing experience but it won't change or fix the problem...

**Comment by awschristou** [comment]
Hi @bdiaze , thank you for reaching out with your issue. Can you please look in the log files under `%localappdata%\AWSToolkit\logs\visualstudio` to see if there is any clue why the validation failed?

Aside from that, to get out of this situation where you cannot access the more established publishing experience, delete the file `%localappdata%\AWSToolkit\PublishSettings.json` and try opening the project's context menu again.

**Comment by bdiaze** [comment]
Hi  @awschristou, I can see the next error in the log file:
![image](https://user-images.githubusercontent.com/32801359/141518340-c5bf7ced-6031-4d1f-8191-f6cf43f60b64.png)

My user in windows is:
![image](https://user-images.githubusercontent.com/32801359/141518428-ee0fb05e-0716-4e54-9605-806a9326c02d.png)
It looks like the space is in my username is the problem?

Here a bigger part of the error:
`2021-11-12 12:49:00,128 [1] DEBUG Amazon.AWSToolkit.PluginServices.Activators.PluginActivatorUtilities - Finished Loading Toolkit Plugins
2021-11-12 12:49:00,129 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - Registering Toolkit Plugins in the AWS Explorer...
2021-11-12 12:49:00,130 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... Initializing CloudFormation
2021-11-12 12:49:00,130 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... registering CloudFormation
2021-11-12 12:49:00,131 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... Initializing CloudFront
2021-11-12 12:49:00,131 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... registering CloudFront
2021-11-12 12:49:00,132 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... Initializing CodeArtifact
2021-11-12 12:49:00,132 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... registering CodeArtifact
2021-11-12 12:49:00,132 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... Initializing CodeCommit
2021-11-12 12:49:00,132 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... registering CodeCommit
2021-11-12 12:49:00,132 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... Initializing DynamoDB
2021-11-12 12:49:00,132 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... registering DynamoDB
2021-11-12 12:49:00,134 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... Initializing EC2
2021-11-12 12:49:00,134 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... registering EC2
2021-11-12 12:49:00,136 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... Initializing ECS
2021-11-12 12:49:00,136 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... registering ECS
2021-11-12 12:49:00,137 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... Initializing Beanstalk
2021-11-12 12:49:00,137 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... registering Beanstalk
2021-11-12 12:49:00,138 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... Initializing IdentityManagement
2021-11-12 12:49:00,138 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... registering IdentityManagement
2021-11-12 12:49:00,140 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... Initializing Lambda
2021-11-12 12:49:00,140 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... registering Lambda
2021-11-12 12:49:00,140 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... Initializing RDS
2021-11-12 12:49:00,140 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... registering RDS
2021-11-12 12:49:00,142 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... Initializing S3
2021-11-12 12:49:00,142 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... registering S3
2021-11-12 12:49:00,143 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... Initializing SimpleDB
2021-11-12 12:49:00,143 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... registering SimpleDB
2021-11-12 12:49:00,144 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... Initializing SNS
2021-11-12 12:49:00,144 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... registering SNS
2021-11-12 12:49:00,144 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... Initializing SQS
2021-11-12 12:49:00,145 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - ... registering SQS
2021-11-12 12:49:00,145 [1] DEBUG Amazon.AWSToolkit.ToolkitFactory - Finished Registering Toolkit Plugins in the AWS Explorer...
2021-11-12 12:49:00,155 [1] DEBUG Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterEventListener - Initializing Lambda Tester event listener
2021-11-12 12:49:00,158 [1] INFO  Amazon.AWSToolkit.ToolkitFactory - ToolkitFactory initialized
2021-11-12 12:49:00,158 [1] INFO  Amazon.AWSToolkit.ToolkitFactory - ToolkitFactory SignalShellInitializationComplete
2021-11-12 12:49:00,158 [1] INFO  Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - AWSToolkitPackage InitializeAsync complete
2021-11-12 12:49:00,500 [8] DEBUG Amazon.AWSToolkit.Telemetry.TelemetryService - Telemetry service disabled
2021-11-12 12:49:01,055 [1] INFO  Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - Received __VSSPROPID4.VSSPROPID_ShellInitialized property change, new value True
2021-11-12 12:49:01,058 [1] DEBUG Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - Toolkit considers VS to be initialized now
2021-11-12 12:49:01,116 [1] DEBUG Amazon.AWSToolkit.Publish.Install.VerifyDeployCli - error: "C:\Users\Benjamin" no es un archivo de paquete v lido.
error: Este no es un archivo nupkg v lido. Ruta de acceso del archivo: C:\Users\Benjamin
error:   End of Central Directory record could not be found.
error: Could not find a part of the path 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Diaz\AppData\Local\AWSToolkit\aws.deploy.cli\2019'.


Usage: dotnet nuget verify [arguments] [options]

Arguments:
  <package-paths>  Especifique la ruta de acceso al paquete

Options:
  --all                      Especifica que todas las comprobaciones posibles se deben realizar en los paquetes.
  --certificate-fingerprint  Compruebe que el certificado del firmante coincide con una de las huellas digitales SHA256 especificadas. Una huella digital SHA256 de certificado es un hash SHA256 del certificado que se usa para identificar el certificado. Las entradas m£ltiples deben estar separadas por un espacio.
  -v|--verbosity             Establezca el nivel de detalle del comando. Los valores permitidos son q[uiet], m[inimal], n[ormal], d[etailed] y diag[nostic].
  -h|--help                  Show help information

2021-11-12 12:49:06,387 [1] DEBUG Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterEventListener - Registering Debugger events
2021-11-12 12:49:06,481 [1] DEBUG Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities - Configuring Solution with Lambda Tester
2021-11-12 12:49:06,483 [1] ERROR Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities - Error configuring Lambda Tester on project. FileName: , FullName: , UniqueName: <MiscFiles>
System.Exception: Unable to determine project FileName
   en Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities.EnsureLambdaTesterConfigured(Project project, IAWSLambda lambdaPlugin)
2021-11-12 12:49:06,484 [1] DEBUG Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities - Finished configuring Solution with Lambda Tester
2021-11-12 12:49:25,617 [23] ERROR Amazon.AWSToolkit.Publish.Package.PublishToAws - Failed to open the Publish document
System.InvalidOperationException: AWS Toolkit was unable to verify the contents of the aws.deploy.cli tool.
Restart Visual Studio to try again.
   en Amazon.AWSToolkit.Publish.Install.ProcessExitHandler.Execute()
   en Amazon.AWSToolkit.Publish.Install.VerifyDeployCli.<ExecuteAsync>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Install.DeployCli.<VerifyDeployCliAsync>d__5.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Install.DeployCli.<InitializeAsync>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<WaitForCliInitializationToCompleteAsync>d__6.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<InstallDeployToolAsync>d__5.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<>c__DisplayClass4_0.<<ShowPublishToAwsDocument>b__0>d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Models.PublishDialogStepProcessor.<ProcessStepsAsync>d__0.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<ShowPublishToAwsDocumentAsync>d__9.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<ShowPublishToAwsDocument>d__4.MoveNext()
2021-11-12 13:28:15,435 [39] INFO  Amazon.AWSToolkit.Credentials.Core.ProfileCredentialProviderFactory - Reloaded AWS Credential Profiles
Profiles found: 1
2021-11-12 13:49:02,361 [134] INFO  Amazon.AWSToolkit.Credentials.Core.ProfileCredentialProviderFactory - Reloaded AWS Credential Profiles
Profiles found: 1
2021-11-12 15:03:20,708 [215] INFO  Amazon.AWSToolkit.Credentials.Core.ProfileCredentialProviderFactory - Reloaded AWS Credential Profiles
Profiles found: 1
2021-11-12 15:04:34,816 [232] ERROR Amazon.AWSToolkit.Publish.Package.PublishToAws - Failed to open the Publish document
System.InvalidOperationException: AWS Toolkit was unable to verify the contents of the aws.deploy.cli tool.
Restart Visual Studio to try again.
   en Amazon.AWSToolkit.Publish.Install.ProcessExitHandler.Execute()
   en Amazon.AWSToolkit.Publish.Install.VerifyDeployCli.<ExecuteAsync>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Install.DeployCli.<VerifyDeployCliAsync>d__5.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Install.DeployCli.<InitializeAsync>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<WaitForCliInitializationToCompleteAsync>d__6.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<InstallDeployToolAsync>d__5.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<>c__DisplayClass4_0.<<ShowPublishToAwsDocument>b__0>d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Models.PublishDialogStepProcessor.<ProcessStepsAsync>d__0.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<ShowPublishToAwsDocumentAsync>d__9.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<ShowPublishToAwsDocument>d__4.MoveNext()
2021-11-12 15:05:01,550 [236] ERROR Amazon.AWSToolkit.Publish.Package.PublishToAws - Failed to open the Publish document
System.InvalidOperationException: AWS Toolkit was unable to verify the contents of the aws.deploy.cli tool.
Restart Visual Studio to try again.
   en Amazon.AWSToolkit.Publish.Install.ProcessExitHandler.Execute()
   en Amazon.AWSToolkit.Publish.Install.VerifyDeployCli.<ExecuteAsync>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Install.DeployCli.<VerifyDeployCliAsync>d__5.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Install.DeployCli.<InitializeAsync>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<WaitForCliInitializationToCompleteAsync>d__6.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<InstallDeployToolAsync>d__5.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<>c__DisplayClass4_0.<<ShowPublishToAwsDocument>b__0>d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Models.PublishDialogStepProcessor.<ProcessStepsAsync>d__0.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<ShowPublishToAwsDocumentAsync>d__9.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<ShowPublishToAwsDocument>d__4.MoveNext()
2021-11-12 15:13:18,596 [227] ERROR Amazon.AWSToolkit.Publish.Package.PublishToAws - Failed to open the Publish document
System.InvalidOperationException: AWS Toolkit was unable to verify the contents of the aws.deploy.cli tool.
Restart Visual Studio to try again.
   en Amazon.AWSToolkit.Publish.Install.ProcessExitHandler.Execute()
   en Amazon.AWSToolkit.Publish.Install.VerifyDeployCli.<ExecuteAsync>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Install.DeployCli.<VerifyDeployCliAsync>d__5.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Install.DeployCli.<InitializeAsync>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<WaitForCliInitializationToCompleteAsync>d__6.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<InstallDeployToolAsync>d__5.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<>c__DisplayClass4_0.<<ShowPublishToAwsDocument>b__0>d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Models.PublishDialogStepProcessor.<ProcessStepsAsync>d__0.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<ShowPublishToAwsDocumentAsync>d__9.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<ShowPublishToAwsDocument>d__4.MoveNext()
2021-11-12 15:20:13,924 [123] ERROR Amazon.AWSToolkit.Publish.Package.PublishToAws - Failed to open the Publish document
System.InvalidOperationException: AWS Toolkit was unable to verify the contents of the aws.deploy.cli tool.
Restart Visual Studio to try again.
   en Amazon.AWSToolkit.Publish.Install.ProcessExitHandler.Execute()
   en Amazon.AWSToolkit.Publish.Install.VerifyDeployCli.<ExecuteAsync>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Install.DeployCli.<VerifyDeployCliAsync>d__5.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Install.DeployCli.<InitializeAsync>d__3.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<WaitForCliInitializationToCompleteAsync>d__6.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<InstallDeployToolAsync>d__5.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<>c__DisplayClass4_0.<<ShowPublishToAwsDocument>b__0>d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Models.PublishDialogStepProcessor.<ProcessStepsAsync>d__0.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<ShowPublishToAwsDocumentAsync>d__9.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.AWSToolkit.Publish.Package.PublishToAws.<ShowPublishToAwsDocument>d__4.MoveNext()
`

**Comment by bdiaze** [comment]
Btw, removing the file PublishSettings.json allowed me to go back to the previous publishing experience, thanks a lot!

**Comment by awschristou** [comment]
We're currently seeing that this behavior happens when the user profile path contains a space. We are investigating a fix for this.

This is similar to #188
Related: #185 (associating with Publish experience known issues)

**Comment by awschristou** [comment]
We are still looking into improvements that are preventing the "Publish to AWS" experience from starting up. The latest version of the Toolkit (1.24.0.0) will attempt to re-enable the older publish experience if an error occurs, to reduce the likelihood of getting in a situation where neither publishing experience is available.

**Comment by AravindMakam** [comment]
I am facing this issue too. Do you have any update as the last update seems to be couple of months ago? I am not able to deploy the app because of this issue.

**Comment by awschristou** [comment]
Hi @AravindMakam , thanks for asking about this. We are preparing a set of fixes for this issue. In the meantime, if you are blocked, a workaround is mentioned in https://github.com/aws/aws-toolkit-visual-studio/issues/188#issuecomment-952047088 that will allow you to access the older publishing experience.

**Comment by awschristou** [comment]
Version 1.25.0.0 of the Toolkit has two changes that address this issue:
- the "Publish to AWS" experience now starts up properly if your profile folder contains a space
- you can now access the newer "Publish to AWS" experience and the more established publishing experiences without having to opt in/out from them
