### ISSUE TITLE
"An update is in progress for resource" failure when publishing NodeJs Lambda functions

### ISSUE THREAD

**Issue by ScottDellinger** [aws/aws-toolkit-visual-studio#197]
**Describe the bug**
Suddenly, AWS has stopped allowing me to publish Lambda functions from Visual Studio 2019 with the following error:

Starting to zip up F:\Projects\IntegrityProjects\AWS\Lambda\Integrity
Finished zipping up directory to C:\Users\Scott\AppData\Local\Temp\tmp3D5E.tmp.zip with file size 562991 bytes.
Starting upload of Lambda function zip file.
The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:XXXXXXXXXXIntegrity
Upload stopped.

I have updated to the most recent version of the AWS Toolkit and have even installed Visual Studio 2022 with the most recent AWS toolkit for that IDE.

**To Reproduce**
- Right click Project name in Visual Studio Solution Explorer
- Select Publish to AWS Lambda
- Select name of function I wish to publish to
- Click "Upload"
- Error is encountered:

Starting to zip up F:\Projects\IntegrityProjects\AWS\Lambda\Integrity
Finished zipping up directory to C:\Users\Scott\AppData\Local\Temp\tmp3D5E.tmp.zip with file size 562991 bytes.
Starting upload of Lambda function zip file.
The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:XXXXXXXXXXIntegrity
Upload stopped.

**Expected behavior**
Deployment package should be uploaded to function

**Comment by awschristou** [comment]
Hi @ScottDellinger , thanks for reaching out. Can you please share what kind of Lambda functions you are deploying? For example, managed runtime dotnetcore3.1, .NET 5 on image based lambdas, custom runtime based lambdas with .NET 6.

**Comment by ScottDellinger** [comment]
@awschristou Nothing so fancy... just Node.js v12

**Comment by awschristou** [comment]
@ScottDellinger ok, also are you seeing this problem when you create new functions, update existing functions, or both?

**Comment by ScottDellinger** [comment]
@awschristou Creating new functions seems to work fine, but updating existing ones is where the issue is. It's not limited to just one function... I can't update any.

I contacted AWS support and received the following info:

---------------------------------------

Hi there,

Thank you for contacting AWS Premium Support. My name is Palesa and I will be assisting you today on this case.

From the case notes I understand that you haven’t made any changes to your deployment method and that when trying to update your Lambda functions by uploading your code through a zip package you are getting the error “The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:ca-central-1:XXXXXXX:function:DEV-Integrity has stopped”. Please let me know if I may have misunderstood you in anyway.


This error is caused by calling the ‘UpdateFunctionConfiguration’, which provision resources for your function. It is recommend to call the ‘GetFunctionConfiguration’ API that will tell you the state of the function - which should be ‘Active’ as well as the ‘LastUpdateStatus ‘ which would be ‘successful’. Calling the ‘GetFunctionConfiguration’ before calling the ‘UpdateFunctionCode’ will help resolve the error and subsequently lead to a successful code update [1].

When you making changes to your function the first API that is called is the you would need to call the ‘GetFunctionConfiguration’ API, which will provide information on whether the update is complete and is in an ‘Active’ before call the ‘UpdateFunctionCode’. 

The workaround for as mentioned would be to check to function state before making any updates to the functions. 

1. You can use the below command the check your functions state:
aws lambda get-function --function-name my-function --query 'Configuration.[State, LastUpdateStatus]'

2. If you are using an earlier SDK version as well as an AWS toolkit, please update it to the latest versions.

3. Additionally, you have the option to delay this change to 5th December 2021, you can do so by opting out of the change by adding a special string to your Lambda function’s “Description” parameter. This parameter is processed at create or update in accordance with the requested action. To delay the update, add below string to the “Description parameter” of Lambda functions in the AWS management console aws:states:opt-out. Kindly note that delaying configuration mechanism does not have an impact after the end of the Delayed Update (December 6, 2021). For detailed step approach please refer to link [2], that has UI screenshots.

Should you have additional questions, please don't hesitate to reach out to me and I will gladly assist you further. 

References:
1. Function States - https://docs.aws.amazon.com/lambda/latest/dg/functions-states.html 
2. Expansion of AWS Lambda States to all functions - https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/ 

We value your feedback. Please share your experience by rating this correspondence using the AWS Support Center link at the end of this correspondence. Each correspondence can also be rated by selecting the stars in top right corner of each correspondence within the AWS Support Center.

Best regards,
Palesa T.
Amazon Web Services

**Comment by awschristou** [comment]
@ScottDellinger thank you for helping me narrow down the problem space. I am able to reproduce the issue.

**Comment by ScottDellinger** [comment]
@awschristou Fantastic! Glad to be able to help!

**Comment by awschristou** [comment]
@ScottDellinger , I have made a change that [accounts for Function state](https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/) when publishing NodeJs Lambda functions. In case you're interested in trying it out, I have attached a build of the toolkit below.

[AWSToolkitPackage.zip](https://github.com/aws/aws-toolkit-visual-studio/files/7610840/AWSToolkitPackage.zip)
Version: 1.23.3.11260
SHA386: `B9BAD6E10CCDE2FC21AE8493CE19FCB89B45D9EA58E04664FD8B874EA521147E7B8E1E53E70FAE5393798BD6552AB2A1`

**Comment by ScottDellinger** [comment]
@awschristou I can confirm that this has resolved the issue. Thanks for the quick response!

**Comment by awschristou** [comment]
@ScottDellinger thank you for helping track the issue and verify the fix

**Comment by awschristou** [comment]
A fix for this issue has been released in the 1.24.0.0 version of the Toolkit
