### ISSUE TITLE
AWS.CodeArtifact.NuGet.CredentialProvider dotnet 6 support

### ISSUE THREAD

**Issue by blundell89** [aws/aws-toolkit-visual-studio#200]
**Is your feature request related to a problem? Please describe.**
Currently, after installing `AWS.CodeArtifact.NuGet.CredentialProvider` via:

`dotnet tool install -g AWS.CodeArtifact.NuGet.CredentialProvider`

When you subsequently run:

`dotnet codeartifact-creds install`

I get an error message informing me that the tool is targeted at dotnet framework version 3.1.0 (as I don't have 3.1.0 installed).

**Describe the solution you'd like**
It would be great to see the tool targeted at dotnet framework version 6.0.0.

**Describe alternatives you've considered**
Installing dotnet 3.1.0 would resolve the issue.

**Additional context**
NA

**Comment by kevbite** [comment]
This should be a simple fix by changing the csproj of the tool to incude multiple targets
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp3.1;net5.0;net6.0</TargetFrameworks>
  </PropertyGroup>
</Project>
```

**Comment by sankalpbhandari** [comment]
Thanks for bringing this to our notice. We are working on it and will add support for dotnet6 by Jan 15th.

**Comment by blundell89** [comment]
Thanks @sankalpbhandari. It doesn't look like the update has been released yet, do you have any idea when it will be? I'd be happy to make the change myself and PR it in but I can't seem to find the code repository.

**Comment by fwhenin** [comment]
Any updates on this?

**Comment by detam-amazon** [comment]
We are now targeting 3/31 to deploy these changes. I will post another update if the status changes.

**Comment by blundell89** [comment]
Hey, any further update please? Is the 31st still the target? Thanks

**Comment by detam-amazon** [comment]
Our team will be starting work on this shortly, and will post another status update next week.

**Comment by avlsmnl** [comment]
Hi @detam-amazon, any update regarding this issue?

**Comment by detam-amazon** [comment]
Our team has prioritized this work and started code changes earlier this week. Code changes have now been built, and we're starting testing and preparing to go through our release process. We're looking at releasing by middle of next week, if not sooner.

**Comment by juliocri** [comment]
> We are now targeting 3/31 to deploy these changes. I will post another update if the status changes.

middle next week seems the deploy target is delayed :/

**Comment by kevbite** [comment]
I really don't get why this is taking so long, the change is minimal. 🙄

**Comment by sankalpbhandari** [comment]
Hello Folks, we released the AWS CodeArtifact NuGet credential provider v1.0.1 which supports net6 and SSO profiles.
