### ISSUE TITLE
Unable to publish to Jakarta Region with Publish to AWS experience

### ISSUE THREAD

**Issue by achmadmulyadi** [aws/aws-toolkit-visual-studio#206]
**Describe the bug**
Publish window failed to open when Jakarta region is selected as region deployment target. 

**To Reproduce**
1. Select Asia Pacific (Jakarta) as region in AWS explorer.
2. In Solution Explorer, right-click on main project and select Publish to AWS 

**Expected behavior**
Publish to AWS wizard should be opened.

**Screenshots**
![awstoolkiterror](https://user-images.githubusercontent.com/15142909/147038595-0fa08a08-685e-421f-ad8a-2ef2ea717c4e.png)

**Log**
[Log.txt](https://github.com/aws/aws-toolkit-visual-studio/files/7760149/Log.txt)

**Computer (please complete the following information):**

- Windows Version: 11
- Visual Studio Version: 2022
- AWS Toolkit for Visual Studio Version: 1.24.0.0

**Additional context**

**Comment by awschristou** [comment]
Thank you for reporting this issue @achmadmulyadi - Do you get the same behavior when you use other regions, or only Jakarta?

**Comment by achmadmulyadi** [comment]
Only Jakarta, I've tried other regions as well without any issue.

**Comment by awschristou** [comment]
Thank you for narrowing that down @achmadmulyadi - the Toolkit knows about the new region, but the "Publish to AWS" feature does not know about the new region yet. We'll look into updating that.

**Comment by awschristou** [comment]
Version 1.25.0.0 of the Toolkit supports opt-in regions like Jakarta from the "Publish to AWS" experience.
