### ISSUE TITLE
AWS Fargate deployment fails without much details

### ISSUE THREAD

**Issue by dflyers** [aws/aws-toolkit-visual-studio#207]
Hi, 
I am trying to deploy a simple ASP.NET (dot NET Core 6.0) app to AWS, i see it creating the ECS tasks etc.. but towards the end the process spins for a while and ends up with an error without much details. 

Steps,
Publish->New Traget->Choose Fargate->Edit Settings to use an existing VPC. ( everything else remains as default).->Click Publish.

**Expected behavior**

**Screenshots**

**Computer (please complete the following information):**

- Windows Version: Windows 10
- Visual Studio Version: VS2022
- AWS Toolkit for Visual Studio Version:  The 2022 preview version.

**Additional context**
Copying the file output

[aws deployment log.txt](https://github.com/aws/aws-toolkit-visual-studio/files/7769514/aws.deployment.log.txt)

**Comment by awschristou** [comment]
Hi @dflyers , can you try the latest version of the Toolkit (currently 1.27.0.0), to see if this gives you more details about your deployment failure? We would be interested in hearing if the experience has improved in a newer version.
