### ISSUE TITLE
Ability to upload image to ECR from Publish to AWS experience

### ISSUE THREAD

**Issue by chaseaucoin** [aws/aws-toolkit-visual-studio#211]
**Is your feature request related to a problem? Please describe.**
Yes. in the Toolkit's previous publishing experience we could upload images to ECR with the tool.
This was my primary use case: deploying images for testing during development in EKS. Having this integrated workflow in the toolkit is valuable.

**Describe the solution you'd like**
I'd like to be able to upload my application/project image to ECR from the Toolkit's new "Publish to AWS" experience.

**Describe alternatives you've considered**
Using docker directly, but why then have the toolkit installed?

**Comment by awschristou** [comment]
To make sure I understand, are you requesting that the new "Publish to AWS" experience allow you to publish images to ECR, where the previous "Publish Container to AWS" menu item would allow you to do this?

As a workaround, you can re-enable the older publishing experience from within the "Publish to AWS" dialog. This will allow you to access both the new and old publishing experiences from the project's context menu.
![image](https://user-images.githubusercontent.com/39839589/148974473-8b892901-cd47-43d1-bfe5-5792b22c613f.png)

**Comment by chaseaucoin** [comment]
Previous experience had the following deployment target:
![image](https://user-images.githubusercontent.com/11601228/149044930-7ccae71b-b8db-4a1a-ab1c-b2dc61076f79.png)

Current version deployment targets:
![image](https://user-images.githubusercontent.com/11601228/149045117-22845d3e-82f3-45c8-b97c-52721ce81740.png)

![image](https://user-images.githubusercontent.com/11601228/149045163-ce539d14-c1e8-4256-84c4-58a46357e84a.png)

Use Case:
Deploying images for testing during development in EKS. Can obviously be done in CLI but all of these things could. The value of having this in the toolkit is the integrated workflow.

**Comment by awschristou** [comment]
Thank you for the clarification. I will update the issue title and description to help track this against the newer Publish to AWS experience.

**Comment by awschristou** [comment]
In version 1.28.0.0 of the Toolkit, the Publish to AWS experience can now be used to publish images to ECR Repositories.
