### ISSUE TITLE
PruebaWS

### ISSUE THREAD

**Issue by kractos26** [aws/aws-toolkit-visual-studio#214]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Computer (please complete the following information):**

- Windows Version:
- Visual Studio Version:
- AWS Toolkit for Visual Studio Version:

**Additional context**

**Comment by kractos26** [comment]
m

**Comment by awschristou** [comment]
Issue appears to be a random entry. Closing.
