### ISSUE TITLE
Publish to AWS Lambda is not honoring the VPC configuration in aws-lambda-tools-defaults.json

### ISSUE THREAD

**Issue by solidstore** [aws/aws-toolkit-visual-studio#218]
**Describe the bug**
Publish to AWS Lambda is not honoring the VPC related settings in the aws-lambda-tools-defaults.json file.

**To Reproduce**
In my aws-lambda-tools-defaults.json file I have the following set.

` "function-subnets"    : "subnet-12345, subnet-5678",`
`  "function-security-groups" : "sg-1234, sg-5678"`

**Expected behavior**
Api Gateway and Lambda should have been associated with the VPC and security-groups/subnets.

**Screenshots**

**Computer (please complete the following information):**

- Windows Version: Windows Server 2019 Standard (1809)
- Visual Studio Version: Microsoft Visual Studio Professional 2019 (16.11.9)
- AWS Toolkit for Visual Studio Version: 1.26.0.0

**Additional context**
referenced: https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/LambdaToolsDefaults.cs

**Comment by awschristou** [comment]
This sounds like it is related to #198, which a fix has been released for in version 1.29.0.0. Please re-open this issue if you are still having issues publishing VPC settings to Lambda functions in the latest Toolkit version.
