### ISSUE TITLE
latest version on aws-toolkit-visual-studio does not have amazon RDS

### ISSUE THREAD

**Issue by rhtaylor** [aws/aws-toolkit-visual-studio#219]
aws-toolkit veriosn 1.35 does not have amazon RDS. I want to launch a database instance but cannot. What is the problem? I see articles that have amazon RDS in the toolkit to do so.

**Comment by awschristou** [comment]
Hi @rhtaylor , are you using the AWS Toolkit for Visual Studio, or the AWS Toolkit for VS Code? Which Toolkit is being used by the articles you mentioned?

**Comment by rhtaylor** [comment]
It's says AWS Toolkit. I do not see the AWS Toolkit for VS Code in the marketplace.

**Comment by rhtaylor** [comment]
I did download the package on the amazon website however when I try to install from VSIX it tells me the error "extension/package.json not found inside package"

**Comment by awschristou** [comment]
It sounds like you are trying to use VS Code. Are you trying to use VS Code or Visual Studio?

Both VS Code and Visual Studio have AWS Toolkit extensions. To help disambiguate:
* the VS Code extension: https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode
  * the GitHub repo for this extension: https://github.com/aws/aws-toolkit-vscode
* the Visual Studio 2022 extension: https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2022
  * this is the GitHub repo for this extension (https://github.com/aws/aws-toolkit-visual-studio)

**Comment by rhtaylor** [comment]
Thank you so much. I see the issue. I was attempting to use Visual Studio Code as Visual Studio. I had not realized they were separate IDEs.
