### ISSUE TITLE
aws-lambda-tools-defaults.json not being used by Publish AWS Serverless Application

### ISSUE THREAD

**Issue by genifycom** [aws/aws-toolkit-visual-studio#224]
**Describe the bug**

It does not appear the the AWS Publish to Lambda is using the aws-lambda-tools-defaults.json file.

For example, my aws-lambda-tools-defaults.json contains my profile and region but the dialog is showing a different profile and region. Even if I switch my profile back to the one in aws-lambda-tools-defaults.json the region is left untouched.

If you are working with multiple profiles (representing different clients) then it is critical that the publish goes to the correct AWS account.

The Publish AWS Serverless Application MUST use the aws-lambda-tools-defaults.json

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS:
-   Visual Studio Code Version:
-   AWS Toolkit Version:

**Additional context**

**Comment by awschristou** [comment]
Hi @genifycom , thank you for your patience on this request, and for the context behind the request.

Version 1.27.0.0 of the Toolkit is now available. When you publish serverless projects or lambda projects, the publish wizard will now initialize to the credentials profile and region that are configured in `aws-lambda-tools-defaults.json`. If that file is not found (or the properties are not found), the wizard will initialize to the profile and region that are selected in the AWS Explorer.
