### ISSUE TITLE
Cannot open CloudFormation project in Visual Studio 2022

### ISSUE THREAD

**Issue by jvrooyen** [aws/aws-toolkit-visual-studio#227]
Visual studio 2022 shows a pop-up suggesting upgrading the project to .Net Framework 4.8 when opening a CloudFormation project.

**To Reproduce**
1. Create a new CloudFormation project in Visual Studio 2022 using the AWS toolkit template
2. Use default names for the solution and project
3. Note that the project and file do not have the CloudFormation icons in Solution Explorer
![image](https://user-images.githubusercontent.com/28042104/159045029-c23aa759-9ddf-4bb4-a1c2-242ba32c082a.png)

4. Save everything and close Visual Studio
5. Try to open the project again with Visual Studio
6. The pop-up is shown by Visual Studio
![CloudFormation Popup](https://user-images.githubusercontent.com/28042104/159042883-c34ffaa2-abf5-46ab-8323-a557580006e0.PNG)
7. After clicking continue, the project is "unloaded"
![image](https://user-images.githubusercontent.com/28042104/159045671-bd58f25e-ed8d-4751-ae53-64463dad1061.png)

**Expected behavior**
The project should load

**Computer:**

- Windows Version: 10.0.19043
- Visual Studio Version: 17.1.1
- AWS Toolkit for Visual Studio Version: 1.26.0.0

**Additional context**
.Net 4.0 targeting packs are [not supported in Visual Studio 2022](https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers) anymore.

 I have the ASP.Net and web, Node.js and the .Net desktop workloads installed for Visual Studio. 
.Net targeting packs:
- .Net 5.0 Runtime
- .Net 6.0 Runtime
- .Net Core 3.1 Runtime
- .Net Framework 4.7.2 targeting pack & SDK
- .Net Framework 4.8 targeting pack & SDK

**Comment by fayeg21** [comment]
I'm getting this too.

**Comment by firecrestsystems** [comment]
Same issue. Any advice or work around's?

**Comment by firecrestsystems** [comment]
Thanks for the update. 
I agree it is strange.

**Comment by awschristou** [comment]
Thank you for reporting the issue. I was able to reproduce this.

If you previously used Visual Studio 2019 (or earlier) you likely would have had the .NET Framework 4.0 targeting pack installed, and wouldn't have been impacted by this. Now that 4.0 is out of support, you're more likely to see this happen if you are only working with Visual Studio 2022.

We are investigating a fix so that CloudFormation projects can be loaded without issue.

**Comment by awschristou** [comment]
Version 1.39.0.0 of the Toolkit has been released. With this version, the Toolkit no longer thinks that CloudFormation projects require .NET Framework 4.0. Instead, they will use .NET Framework 4.7.2, which is installed as part of Visual Studio 2019 and 2022.
