### ISSUE TITLE
KeySpec property is not recognized for KMS keys in CloudFormation templates

### ISSUE THREAD

**Issue by rpmrmartin** [aws/aws-toolkit-visual-studio#228]
**Describe the bug**

When adding the `KeySpec` property to an `AWS::KMS::Key` resource in a CloudFormation template, an error appears in the error list.

**To Reproduce**

1. Create a CloudFormation project
2. Add a CloudFormation template to the project
3. Add an `AWS::KMS::Key` resource to the template
4. Add the `KeySpec` property to the resource

For example:
```json
{
	"AWSTemplateFormatVersion" : "2010-09-09",

	"Description" : "",

	"Parameters" : {
	},

	"Resources" : {
		"EncryptionKey": {
			"Type": "AWS::KMS::Key",
			"Properties": {
				"KeyPolicy": {
					"Version": "2012-10-17",
					"Statement": {
						"Sid": "Enable IAM policies",
						"Effect": "Allow",
						"Principal": {
							"AWS": {
								"Fn::Sub": "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
							}
						},
						"Action": "kms:*",
						"Resource": "*"
					}
				},
				"KeySpec": "RSA_2048",
				"KeyUsage": "ENCRYPT_DECRYPT"
			}
		}
	},

	"Outputs" : {
	}
}

```

**Expected behavior**

The `KeySpec` property is recognized as a valid property of an `AWS::KMS::Key` resource.

**Screenshots**

![image](https://user-images.githubusercontent.com/49652977/159354607-a6c7c4cd-f400-475a-9beb-960d13f942df.png)

**Computer (please complete the following information):**

- Windows Version: Windows 10 Pro for Workstations 20H2
- Visual Studio Version: Visual Studio Professional 2022 17.1.1
- AWS Toolkit for Visual Studio Version: 1.26.0.0

**Additional context**

The `KeySpec` property is documented at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html#cfn-kms-key-keyspec

**Comment by awschristou** [comment]
We've updated the definitions used by the Toolkit. The next time you start Visual Studio, the Toolkit should download the updated definitions file, and these fields should no longer be classified as an error.
