### ISSUE TITLE
How can I build a solution containing a CloudFormation project on Linux?

### ISSUE THREAD

**Issue by rpmrmartin** [aws/aws-toolkit-visual-studio#229]
I have a solution containing a C# class library, a C# Lambda function project, a unit test project, and a CloudFormation project.

The CI pipeline for this app runs on Linux. When it runs `dotnet test`, it fails with the following error:
> The imported project "/cloudformation.targets" was not found. Confirm that the expression in the Import declaration "/cloudformation.targets" is correct, and that the file exists on disk.

The CloudFormation project does not appear in the VS configuration manager, so I cannot create a new configuration that does not build the CloudFormation project.

As far as I know, there is no support for installing Visual Studio extensions on Linux so that MSBuild could find cloudformation.targets.

I would prefer not to specify the unit test project to the `dotnet test` command in case we add more test projects later on. So, what is the best way to get this solution to build on Linux?

**Comment by JamesSozoLabs** [comment]
Did you ever resolve this?
I'm having the same issue now.

**Comment by rpmrmartin** [comment]
@JamesSozoLabs No, we ended up removing the CloudFormation project from the solution.

**Comment by awschristou** [comment]
The CloudFormation project is a custom project that is defined and powered through the AWS Toolkit. Unfortunately this custom project is only functional from within instances of Visual Studio that have the AWS Toolkit installed. As you've seen, other tooling (like command line tools) do not know how to work with this project type.

The main benefits to the custom CloudFormation project are:
- it provides a context menu within Visual Studio to deploy a CloudFormation template to a development environment
- it surfaces schema validation checks as compiler-style errors within the IDE

The workarounds are as you've found, you can remove (or exclude) the CloudFormation project when working with your repo from other tooling like continuous integration systems. The CloudFormation template files could be relocated into a solution folder (as an example), and you can still run command line tooling against the actual template files.

I close this issue and label it as a general guidance.
