### ISSUE TITLE
Existing targets not displaying in AWS Toolkit 

### ISSUE THREAD

**Issue by KhumaloM** [aws/aws-toolkit-visual-studio#230]
**Describe the bug**
When i try to publish my app to beanstalk the existing targets that i already have dont appear in the new experience

 
![image](https://user-images.githubusercontent.com/13219753/160473760-5f9a16bb-1cdd-4ed5-bb41-74872119f332.png)

old publish expirience:

![image](https://user-images.githubusercontent.com/13219753/160473878-2ea9b49b-7f8f-4d60-a8b1-1b254be3c80e.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Computer (please complete the following information):**

- Windows Version:
- Visual Studio Version:
- AWS Toolkit for Visual Studio Version:

**Additional context**

**Comment by awschristou** [comment]
Hi @KhumaloM , 
- what version of the Toolkit are you using? Version 1.25.0.0 and newer has support for listing existing Beanstalk Environments
- Does your application use .NET Framework or .NET Core/.NET 5+? .NET Framework based environments are not supported in the new Publish experience at this time

**Comment by KhumaloM** [comment]
Hi @awschristou  - Thank you for your response. I am using:

- AWS Toolkit for Visual Studio 2022
- .Net 5
Thank you!

**Comment by awschristou** [comment]
I am closing this issue as stale. If the issue persists on the latest version of the Toolkit, please open a new issue.
