### ISSUE TITLE
AWS::SNS::Topic Cloudformation validation incorrect

### ISSUE THREAD

**Issue by firecrestsystems** [aws/aws-toolkit-visual-studio#236]
"ContentBasedDeduplication": "true",     
"FifoTopic" : "true",

i.e. 
        "MySNS" : {
            "Type" : "AWS::SNS::Topic",
            "Properties" : {
                "TopicName" : "MySNS", 
                "ContentBasedDeduplication": "true",
                "FifoTopic" : "true",
                "DisplayName" : "MySNS", 
}

is not accepted.

The use of these are not available and classified as an error in the template.

This was confirmed with AWS Support

**Comment by awschristou** [comment]
We've updated the definitions used by the Toolkit. The next time you start Visual Studio, the Toolkit should download the updated definitions file, and these fields should no longer be classified as an error.
