### ISSUE TITLE
Adding Docker Support on an Existing 4.7.2 application does not change deploy options

### ISSUE THREAD

**Issue by w-penberthy** [aws/aws-toolkit-visual-studio#245]
I had an existing .NET 4.7.2 web application that I was going to containerize. I went through the built-in "Add Docker Support" option in Visual Studio 2019, and that worked great. It added the Docker file and I can debug in the container. However, when I looked to publish the image to ECR I realized that I do not have any of the expected AWS container support, and the only AWS publish option is to Elastic Beanstalk.

Thinking this was because of something in the app, I retried it with a sample ASP.NET 4.7.2 application created from VS template. Same behavior. Even though the application is now "container-bound" it is not treated as such by the Toolkit. 

Edit: The same behavior is happening when using an already containerized 4.7.2 application. However, this means that I can not easily get these containers into ECR and that's a problem.

![Figure1303](https://user-images.githubusercontent.com/7268143/166124661-2accb04a-8d7a-4695-8d18-06e86f1b70ff.png)
![Figure1306](https://user-images.githubusercontent.com/7268143/166124663-5d81445b-455b-4e66-b1bc-35ced2985149.png)
![Publish options](https://user-images.githubusercontent.com/7268143/166124709-0c6e80ae-737d-42ed-bc10-36d783eda36c.png)

**Comment by awschristou** [comment]
Hi @w-penberthy , the "Publish Container to AWS" feature in the Toolkit only has support for publishing .NET Core applications in Linux based containers. This is similar to the [dotnet extensions for ECS tooling](https://github.com/aws/aws-extensions-for-dotnet-cli#aws-extensions-for-net-cli).
