### ISSUE TITLE
AWS Explorer - Amazon S3 bucket folder with double slashes has no folder name and is inaccessible

### ISSUE THREAD

**Issue by tauheedul** [aws/aws-toolkit-visual-studio#248]
**Describe the bug**
When a filename uploaded contains extra double slashes, it causes AWS explorer to detect the extra slash as an empty file directory name. So a folder will exist in AWS Explorer with no filename, and clicking on the folder name does not allow the directory to be opened. It simply refreshes the bucket and does not open the child directory.

It is not possible to rename the incorrect folder name in AWS Explorer. The only option is delete and reupload all of them, this is not practical. It should be possible to fix the path where there are extra slashes. There is only an option to MOVE the file in S3 Management Console

**To Reproduce**
Steps to reproduce the behavior
1. Upload file with filename containing extra double slash e.g. /bucket//child_directory/anything.txt using the S3 Upload API
2. The S3 Bucket explorer in Visual Studio will display a directory with no filename
3. It is not possible to open the directory from AWS Explorer S3 Bucket directory explorer
4. It is only possible to select the folder on AWS Console online 
5. It is not possible to rename a directory with no filename in AWS Explorer. 

**Expected behavior**
- In AWS Explorer S3 Bucket viewer it should be possible to access the folder with no name the same as S3 Management Console.
- In AWS Explorer, we should be able to rename the folder name if it has none or fix the file path to remove the extra slash.

**Screenshots**
In AWS Explorer
![image](https://user-images.githubusercontent.com/9335220/167607329-77287b9e-0b32-40cc-96aa-bfb69ecd3147.png)

In S3 Management Console
![image](https://user-images.githubusercontent.com/9335220/167608268-231933d9-c40a-428e-b170-f9e23bbf922d.png)

**Computer (please complete the following information):**

- Windows Version: N/A
- Visual Studio Version: Visual Studio 2019 16.11.11
- AWS Toolkit for Visual Studio Version: 1.28.0.0

**Additional context**
S3 Uri from AWS S3 Management Console
File Properties: s3://examplebucket name//anotherfolder/

**Comment by awschristou** [comment]
Version 1.33.0.0 of the Toolkit is now available. In this version, The S3 bucket browser can now navigate through paths containing subsequent slash characters. These are shown in the browser as folders that are named as `/`.
