### ISSUE TITLE
'Method not found: 'Void Amazon.S3.AmazonS3Client During Deployment

### ISSUE THREAD

**Issue by benmorris44** [aws/aws-toolkit-visual-studio#249]
I'm receiving this error randomly during deployment.  It takes sometimes 5-10 tries for the project to begin uploading and skip the error.  

AWS Toolkit Version 1.28.0.0
Microsoft Visual Studio Community 2019
Version 16.9.4

.net framework 4.8.04084

..deployment package created at X:\sites\IonCommerce\IonCommerce\obj\Release\Package\IonCommerce.zip
...starting redeployment to AWS Elastic Beanstalk environment 'IonWeb-Live'
Attempt to create deployment upload bucket caught Exception, Message 'Method not found: 'Void Amazon.S3.AmazonS3Client..ctor(Amazon.Runtime.AWSCredentials, Amazon.RegionEndpoint)'.'
Publish to AWS Elastic Beanstalk failed with exception: Detected error in deployment bucket preparation; abandoning deployment
Error publishing application: Unhandled error during deployment
Publish to AWS Elastic Beanstalk environment 'IonWeb-Live' did not complete successfully

**Comment by awschristou** [comment]
What type of credentials are you using with the toolkit, are they short lived like MFA or SSO, or are they a standard access key + secret key pairing?

Can you please share some more details about your deployment. Are you using the new "Publish to AWS" experience, or the older "Publish to AWS Elastic Beanstalk" experience? What framework is the project you are trying to deploy targeting? Are you publishing to a Windows or Linux image (if your project is not .NET Framework based)?

**Comment by awschristou** [comment]
If you can share your Toolkit log from `%localappdata%\AWSToolkit\logs\visualstudio`, we would be interested in seeing if that reveals any causes. 

Have you got any other AWS related extensions installed into Visual Studio? There's a chance that the Toolkit is not using the AWS SDK dlls that were bundled with the Toolkit.  There are some steps that can help diagnose this (or rule this possibility out) written in https://github.com/aws/aws-toolkit-visual-studio/issues/138#issuecomment-756930669 . Would you be able to to try that and share what DLLs are loaded and from where?

**Comment by benmorris44** [comment]
I haven't been able to find the reason it begins to work, I usually keep trying the publish and it will eventually work.  I have previously restarted VS, restarted PC, and still had the issue.  I have noticed on occasion something appears to reset in the publishing wizard because although my credentials are still there my previous selected settings are reset, most notably the project build configuration is set back to debug rather release.  When this is reset is generally works the first try without the error.

[log.txt](https://github.com/aws/aws-toolkit-visual-studio/files/8670086/log.txt)

![Capture](https://user-images.githubusercontent.com/1420881/167856514-f78f45fc-2ec4-44ea-9ad2-15820a0ace2b.PNG)

**Comment by awschristou** [comment]
Hi @benmorris44 , I have made a change that may help the Toolkit use the bundled AWS SDK dll files. If you're willing to try an experimental build, I would like to know if this addresses your situation. Please try installing the attached Toolkit for Visual Studio 2019, perform a few deployments, and share your results.

[AWSToolkitPackage.zip](https://github.com/aws/aws-toolkit-visual-studio/files/8671620/AWSToolkitPackage.zip)
Version: 1.28.0.5110
Sha384 hash: `D0246A4CC4A22EA51CA599D5C3F28A92CD02E73DB9DCF352EA3F74AF19A0BA97F80B2A3AB68C15780B444C412E60169E`

**Comment by benmorris44** [comment]
I will give this a try it may take a few days or a week before I can say for certain it fixed it.  I will report back though

**Comment by benmorris44** [comment]
I've done 4-5 actual deploys and so far no issues.  Will continue to use and report back.

**Comment by awschristou** [comment]
Thanks for the update @benmorris44 - If you're able to share that it is working for you after a couple more days of use, I'll commit that fix.

**Comment by benmorris44** [comment]
Just wanted to follow up again, I have done quite a few production deploys now and still haven't received the error.

**Comment by awschristou** [comment]
Thank you for the follow up. I will prepare that change for an upcoming release.

**Comment by awschristou** [comment]
This change is now available in the 1.32.0.0 release of the Toolkit
