### ISSUE TITLE
How to publish the lambda with different aws-lambda-tools-xxx.json for different environment (prod, staging, dev)?

### ISSUE THREAD

**Issue by xiaohui-gsv** [aws/aws-toolkit-visual-studio#250]
We have three environments (prod, staging, dev), is there a way that we can use different `aws-lambda-tools-xxx.json` to publish to different environments in VS2022? If not, is there any other way we can achieve this goal? thank you.

**Comment by xiaohui-gsv** [comment]
Hi, does anyone knows this? thank you.

**Comment by awschristou** [comment]
Hi @xiaohui-gsv , the Toolkit does not allow you to publish using an alternate configuration file. The AWS Toolkit's Lambda deployment features are intended to help the development and iteration loop. Once your system is ready to be deployed to another environment (like staging or prod), performing a deployment through more automated means is recommended. This reduces the likelihood of introducing unintended changes in those environments.

It's great that you have different json files configured for your different environments. You can use the AWS .NET CLI extensions to deploy your code to Lambda from the command line (and from CI systems). The [AWS Lambda](https://github.com/aws/aws-extensions-for-dotnet-cli#aws-lambda-amazonlambdatools) extension knows how to work with the `aws-lambda-tools-xxx.json` files, and performs the same deployment as the Toolkit. You will need to pass your specific json file in through a command line argument, and this should help you achieve your goal of deploying to different environments.

**Comment by xiaohui-gsv** [comment]
@awschristou thank you, I can use the `dotnet lambda deploy-function --config-file xxxx.json` to publish to the different environment.
