### ISSUE TITLE
Cannot create or update Lambda functions with runtime Node.js 16.x

### ISSUE THREAD

**Issue by mau4gdp** [aws/aws-toolkit-visual-studio#252]
When support for creating/updating Lambda functions with runtime Node.js 16.x will be added?
thanks

**Comment by awschristou** [comment]
Support for NodeJS Lambda development and deployment has been removed from the AWS Toolkit for Visual Studio, starting in version [1.50.0.0](https://github.com/aws/aws-toolkit-visual-studio/blob/main/CHANGELOG.md#15000-2024-03-28). See https://github.com/aws/aws-toolkit-visual-studio/issues/286 for more details.
