### ISSUE TITLE
Pre and Post Lambda Publish Scripts (Node.js)

### ISSUE THREAD

**Issue by git-atg137** [aws/aws-toolkit-visual-studio#261]
**Is your feature request related to a problem? Please describe.**
some npm packages have different dependencies based on environment. for example dev is win32, lambda is linux - but when I install certain npm libraries they install based on the dev (win32) environment, then when I publish lambda is missing dependencies because it's a linux environment.

**Describe the solution you'd like**
could be solved if able to customize "pre/post lambda deployment" scripts that would trigger so I can run something like this with deployment:

PRE lambda deployment script
   npm remove sharp
   npm install --arch=x64 --platform=linux --libc=glibc sharp
POST lambda deployment script
   npm remove sharp
   npm install --arch=x64 --platform=win32 sharp

**Describe alternatives you've considered**
above is the only way I can think of for seamless development & deployment

**Additional context**
none

**Comment by awschristou** [comment]
Support for NodeJS Lambda development and deployment has been removed from the AWS Toolkit for Visual Studio, starting in version [1.50.0.0](https://github.com/aws/aws-toolkit-visual-studio/blob/main/CHANGELOG.md#15000-2024-03-28). See https://github.com/aws/aws-toolkit-visual-studio/issues/286 for more details.
