### ISSUE TITLE
Deploy service on Amazon ECS using Fargate

### ISSUE THREAD

**Issue by bilal-mic** [aws/aws-toolkit-visual-studio#262]
Having issue on deploying service on ECS, it contains a private nuget package, credentials given in nuget config, still giving error 401. Please see the screenshot.
Build/Publish done, even container image is there but at the end there is some issue with AWS CDK.

![image](https://user-images.githubusercontent.com/101135434/174197232-4e00d0d9-e886-4800-8c63-61ad72960f6d.png)

**Comment by ashovlin** [comment]
It may be in either the hidden portion or off the right side of your screenshot, but is the package that failed to restore either `Amazon.CDK.Lib` and `Microsoft.Extensions.Configuration.Json`?

These are references from the CDK project that is generated behind-the-scenes to deploy your service to ECS, which is the step of the deployment you were on. [Here is the template](https://github.com/aws/aws-dotnet-deploy/blob/5b78ecaec217908c19d92fabbdfcf1963821194a/src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/ConsoleAppEcsFargateService.csproj#L28-L29).

If that's the case, then I'm wondering if those references aren't working with your private package source. Is your `nuget.config` at the [user or computer level](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses)?
