### ISSUE TITLE
Node.Js lambda container support for Visual Studio?

### ISSUE THREAD

**Issue by Nigrimmist** [aws/aws-toolkit-visual-studio#264]
Hello! Can i somehow deploy nodejs lambda code from visual studio in case of docker image source?

I have : 
Microsoft Visual Studio Professional 2019
Version 16.11.13

AWS toolkit 1.31

I trying to add a new project, but see only nodejs as a zip package. Do I have something wrong? Or maybe vs code supporting has this feature (automate deploy without cli)? For example, using C# project - I can select container, with nodejs project - no.

Thanks in advance!

**Comment by awschristou** [comment]
The AWS Toolkit for Visual Studio has support for publishing .NET Lambda function images, but not for other languages like NodeJs. I will mark this as a feature request.

To help my understanding, are you mainly using Visual Studio to develop your NodeJs code, or another editor?

**Comment by Nigrimmist** [comment]
I mainly use VS Code for writing nodejs, but currently, I need to mix C# and JS projects. Thanks for fast answer

**Comment by Nigrimmist** [comment]
Will try it, thanks a lot
