### ISSUE TITLE
Unable to connect to AWS via SSO - AWSSDK.SSOOIDC could not be found or loaded

### ISSUE THREAD

**Issue by lifedesignanalysis** [aws/aws-toolkit-visual-studio#267]
**Describe the bug**
I recently updated AWS Toolkit for Visual Studio 2022 to version 1.32.0 and now when trying to login in through AWS Explorer an error is occurring.

**To Reproduce**

1. Launch Visual Studio 2022.
2. Go to AWS Explorer.
3. Click on a profile that is configured to use SSO credentials.
4. Click 'Retry' below the "AWS login needed" prompt.
5. Wait.
6. See error

**Expected behavior**
A prompt to login using AWS SSO should appear and redirect the user to the AWS SSO login page.

**Screenshots**
Retry login: 
![Screenshot 2022-06-22 165916](https://user-images.githubusercontent.com/86081073/175135278-0e0a96b3-f88e-4311-8da4-580b7e389eda.png)

Error message:
![Screenshot 2022-06-22 170126](https://user-images.githubusercontent.com/86081073/175135384-726568ea-701f-4acc-a45b-9662d273675c.png)

**Computer (please complete the following information):**

- Windows Version: Window 11 Pro, 22000.739
- Visual Studio Version: 17.2.5
- AWS Toolkit for Visual Studio Version: 1.32.0.0

**Comment by grahamcoleborn** [comment]
Same issue here

**Comment by butekx** [comment]
> I got the same error.  Is there anyway to downgrade the extension to a previous version like 1.29?  I could only find [1.27 for VS2019](https://github.com/aws/aws-toolkit-visual-studio/releases/tag/v1.27.0.0) in this repo but I can't find the previous version for VS2022.
> 
> Thanks!

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/AmazonWebServices/vsextensions/AWSToolkitforVisualStudio2022/1.31.0.0/vspackage

**Comment by lifedesignanalysis** [comment]
Thanks @butekx, that worked!

**Comment by charithjj** [comment]
So is this a bug in the latest toolkit on VS 2022?

**Comment by floralph** [comment]
Thank you for bringing this issue to our attention.  I was able to reproduce the issue and we are investigating further.

**Comment by Zombiesmith** [comment]
I am experiencing this exact same behavior in VS 2019 with the latest version of AWS Toolkit.

**Comment by awschristou** [comment]
We have a fix for this issue. If you would like to try out an advance build containing the fix, please download and install one of these Toolkits, and let us know if you are able to connect in the Toolkit using SSO based credentials.

- [AWS Toolkit for Visual Studio 2019](https://github.com/aws/aws-toolkit-visual-studio/files/9015164/AwsToolkit-vs2019.zip)
  - Sha384 Hash: `BA44A75906E6A71B076FE61BB8B3A1AF1245D1AF05B269DE8DDE83057F7F81C4B45FF8A7256B1FAB11ECBAC8FC10A469`
- [AWS Toolkit for Visual Studio 2022](https://github.com/aws/aws-toolkit-visual-studio/files/9015167/AwsToolkit-vs2022.zip)
  - Sha384 Hash: `0222F7878653270DD12E005D4B09DE68736E0B14F36AE7BF06387749AA839F1A964AA7118A08679B834E21592AE5E58A`

**Comment by awschristou** [comment]
Version 1.34.0.0 of the Toolkit is now available. SSO based credentials are working in this version of the Toolkit.

**Comment by Zombiesmith** [comment]
I figured out my problem.  When I set up the AWS profile, I had typed in "JSON" as the output, changed it to lower case and that fixed it.  Upper case works everywhere else, like VS Code and the AWS CLI.
