### ISSUE TITLE
AWS Toolkit for Visual Studio

### ISSUE THREAD

**Issue by WagnerSG** [aws/aws-toolkit-visual-studio#270]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Computer (please complete the following information):**

- Windows Version:
- Visual Studio Version:
- AWS Toolkit for Visual Studio Version:

**Additional context**

**Comment by awschristou** [comment]
This issue appears to be created in error. I will close it, but feel free to open a new issue if you had a problem (or feature request) working with the Toolkit.
