### ISSUE TITLE
Publish to AWS - Unable to publish to Fargate - Unexpected character encountered while parsing value: s

### ISSUE THREAD

**Issue by purplesmash** [aws/aws-toolkit-visual-studio#271]
**Description**
I installed the latest version of the AWS Toolkit for Visual Studio 2022 since doing that I cannot deploy existing projects to ECS I can see everything in the AWS console for the deployment.

Following the latest update when I click Publish to AWS whilst I can select a new target or publish to an existing target the ability to edit the Target Configuration is not available and the details of the configuration is not available. The publish button is shown but does nothing on click.

I have a number of asp.net (version 6) applications that I have deployed to ECS using AWS Fargate but I am unable push updates through Visual Studio and cannot deploy a new service either.

**To Reproduce**
1. Right click the project being deployed
2. Select Publish to AWS
3. Publish to AWS opens with Publish to existing target tab loaded;
4. The recently deployed target is shown but none of the configuration is displayed clicking publish has no effect;

**Expected behavior**

I can see the configuration for the deployment and edit it if I need to

**Screenshots**
<img width="927" alt="image" src="https://user-images.githubusercontent.com/28702186/180468856-16646688-0b20-4bb5-a72e-79fc945f20a5.png">

**Computer (please complete the following information):**

- Windows Version: 11 21H2
- Visual Studio Version: 2022 (17.2.6)
- AWS Toolkit for Visual Studio Version: 1.35.0.0

**Additional context**

From the AWSToolKit visual studio logs

Status: 500
Response:
{"ErrorCode":"UnexpectedError","Message":"Unexpected character encountered while parsing value: s. Path \u0027\u0027, line 0, position 0.","ProcessExitCode":null}
at AWS.Deploy.ServerMode.Client.RestAPIClient.d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.d__179.MoveNext()
2022-07-22 13:39:09,100 [58] ERROR Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl - Error reloading configuration details
HTTP Response:

{"ErrorCode":"UnexpectedError","Message":"Unexpected character encountered while parsing value: s. Path \u0027\u0027, line 0, position 0.","ProcessExitCode":null}

AWS.Deploy.ServerMode.Client.ApiException: The HTTP status code of the response was not expected (500).

**Comment by awschristou** [comment]
Hi @purplesmash , this entry from the log looks interesting "Unexpected character encountered while parsing value: s. Path \u0027\u0027, line 0, position 0.", Could you please share what the full path to your project looks like (or a reasonable example path) - I'm interested what accented and non-alphabet characters are in the path...

**Comment by purplesmash** [comment]
Hi Thanks for getting back the path looks similar to this

C:\project\app-service\Project.App.Service

This was working with previous versions of the toolkit but I have added some features to the service and wanted to deploy those.

**Comment by awschristou** [comment]
Are you seeing this issue when selecting a new deployment? If so, is it before or after editing some of the publish settings? I'm interested to know which settings you have adjusted that could lead to this situation.

**Comment by purplesmash** [comment]
Hi it is on both so I couldn't publish it as a new target either, the only one of the options that seems to populate properly is Container Image to ECR.

<img width="927" alt="image" src="https://user-images.githubusercontent.com/28702186/180476062-c2e4061d-0568-4840-973b-a4dd4781e0af.png">

The option to configure the deployment is completely missing and has the different error from the logs

AWS.Deploy.ServerMode.Client.ApiException: The HTTP status code of the response was not expected (500).

Status: 500
Response: 
{"ErrorCode":"UnexpectedError","Message":"Source sequence doesn\u0027t contain any elements.","ProcessExitCode":null}
   at AWS.Deploy.ServerMode.Client.RestAPIClient.<SetDeploymentTargetAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<InvokeSetDeploymentTargetAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<SetDeploymentTargetAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<SetDeploymentTargetAsync>d__179.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl.<ReloadTargetConfigurationsAsync>d__41.MoveNext()

**Comment by awschristou** [comment]
Does the region you are deploying to have a default VPC? Here's how you can check from the AWS Explorer:
![image](https://user-images.githubusercontent.com/39839589/180482123-57d2a1f9-9a37-4983-ae94-61807b9b49fd.png)

If not, would it be possible for you to try setting up a default VPC (and default subnets), then re-open the Publish to AWS view and see if you still have these errors in the "Publish to new Target" targets? This might be a workaround for making new deployments, but might offer some clues around redeployments as well.
- https://docs.aws.amazon.com/vpc/latest/userguide/default-vpc.html

**Comment by purplesmash** [comment]
Hi, it looks like there isn't a default VPC setup or my role doesn't see it. However, this did work previously so does that mean something has changed with the deployments to require a default VPC?

**Comment by awschristou** [comment]
I don't know if the underlying deploy tool had a change that caused this to stop working in a more recent version, but it is possible, since improvements have been made to help improve the validation of different publish settings.

Two separate changes are being made to help with this issue:
- A fix (https://github.com/aws/aws-dotnet-deploy/pull/672) is being worked on in the deploy tool, so that it will not cause a 500 response error when there is no default VPC. Once this change is completed and released in a future version of the deploy tool, it will be added to a later version of the Toolkit
- A fix is being worked on in the Toolkit, so that when an error like this happens, the Publish to AWS experience will not leave the Publish button enabled, and will surface an error message (because this is confusing when the Publish button does not work)

**Comment by purplesmash** [comment]
Thanks for getting back to me, once adding a default VPC I could publish to a new target but existing targets were still unavailable. I therefore have been able to move forward and have deployed the new version of the service.

Thanks for your help

**Comment by awschristou** [comment]
Thank you for helping us track down this issue. Now that you have a default VPC, are you still seeing the error originally reported when working with the "Publish to Existing Target" section?
```
Status: 500
Response:
{"ErrorCode":"UnexpectedError","Message":"Unexpected character encountered while parsing value: s. Path \u0027\u0027, line 0, position 0.","ProcessExitCode":null}
```

**Comment by awschristou** [comment]
Version 1.35.1.0 of the Toolkit is now available from the marketplace. It contains a fix so that when this scenario happens, the Publish button is greyed out (rather than being able to click on it and have it do nothing).

We don't have a fix yet to support regions without a default VPC, so I will leave this issue open.

**Comment by purplesmash** [comment]
Hi I have installed the latest version, I am still seeing the same error when trying to publish to an existing target, but can confirm that the publish button is disabled.

**Comment by awschristou** [comment]
Thank you for the confirmation @purplesmash . 

I have an update on your initially reported error, where "Unexpected character encountered while parsing value: s." was logged. An incompatibility was introduced, which caused deployments made with an older version of the Toolkit (or deployment tooling) to be incorrectly interpreted by the current versions. We're actively working on addressing that, in addition to the scenario where a region does not have a default VPC.

**Comment by awschristou** [comment]
A new version of the deploy tool was released, which helps with the "Unexpected character encountered while parsing value: s." problem. This occurs when a project was deployed to Fargate with an older (pre-GA) version of the deploy tool, and is configured to use multiple security groups.

We don't have a new version of the Toolkit released yet, but until then you can try out a test build of the Toolkit (linked below) if you are interested. Now, these Fargate targets will show a validation error on the security group field, and will require re-configuring. Once that field has been adjusted in the "Edit Settings" view, it will be possible to publish to these existing Fargate targets.

Toolkit Version: 1.35.1.8080
Sha384: `2FE475D82A69D97378FBE8A7DBE613530806558D9099B49582DB46E873AE28D578BF83418DE6A606C6291299B845EA68`
Download: [AWSToolkitPackage.v17.vsix.zip](https://github.com/aws/aws-toolkit-visual-studio/files/9285278/AWSToolkitPackage.v17.vsix.zip)

**Comment by awschristou** [comment]
Version 1.35.2.0 of the Toolkit is now available. It fixes the problem where you would not be able to publish to Fargate in a region that did not have a default VPC. It used to log the error `Unexpected character encountered while parsing value: s. Path \u0027\u0027, line 0, position 0.`. With this new version, you are now able to publish to a region, even if it does not have a default VPC.
