### ISSUE TITLE
Cannot scaffold a new AWS  Lambda Function Project (NodeJS) on Visual Studio 2022 (preview)

### ISSUE THREAD

**Issue by realnsleo** [aws/aws-toolkit-visual-studio#272]
Hello,
Not sure if this is a bug but I can't seem to start a new Lambda Function project with NodeJS. Whenever I try I get the message:

`"Before using this project template, the NodeJS Tools for Visual Studio plugin must be installed."`

I have installed this tool from the Visual Studio installer and I have installed NodeJS on my computer but that message won't go away each time I try to scaffold a new project. Any ideas?

<img width="1280" alt="Screenshot 2022-07-28 162250" src="https://user-images.githubusercontent.com/1863115/181516997-ed41ec9a-15f1-4ce4-a213-5e56d34dd283.png">

**Comment by awschristou** [comment]
Please update to the latest version of the Toolkit (at this time, the current version is 1.35.1.0) from https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2022 . It contains a fix for detecting the NodeJs workload from Visual Studio, as well as an updated message when the workload cannot be found.

**Comment by awschristou** [comment]
I'm going to close this issue - please re-open it if you experience the same problem using the latest Toolkit version.

**Comment by realnsleo** [comment]
I'm sorry I didn't close this sooner. The latest version of the toolkit solved my error and I was able to scaffold s new project. Thank you @awschristou
