### ISSUE TITLE
Publish to AWS Lambda doesn't update artifact references

### ISSUE THREAD

**Issue by anking** [aws/aws-toolkit-visual-studio#276]
**Describe the bug**
I ran into an issue recently when update to a package in a referenced Assembly caused an issue with Lambda that still had previous versions of that same assembly. It almost looks like the toolkit is caching the assembly version and ignores the fact that is was updated. The only solution for me was to change configuration from Release to Debug which caused the new versions to appear in that config, but I can no londer use Release and this is annoying. Is there a way to clear the cache somehow to make it pull proper assembly versions?

**To Reproduce**
Compiling a lambda with a regular "Rebuild" produces correct versions of files, but AWS Deploy gets the old ones somehow

**Expected behavior**
Pull updated assemblies

**Screenshots**
![image](https://user-images.githubusercontent.com/9019734/186933449-d4f0c949-a1c1-4be5-ba15-5068ebd40ffc.png)

**Comment by awschristou** [comment]
Hi @anking , have you tried deleting the bin and obj folders and then attempting another publish?

**Comment by anking** [comment]
@awschristou Thanks a lot! Looks like deleting "obj" folder solved the problem! I've been only deleting bin folder every time and it did nothing
