### ISSUE TITLE
Incompatible command line options

### ISSUE THREAD

**Issue by inlandchris** [aws/aws-toolkit-visual-studio#277]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Computer (please complete the following information):**
Windows 11 
- Windows Version:Version	10.0.22000 Build 22000
- Visual Studio Version:2019 Enterprise
- AWS Toolkit for Visual Studio Version:1.35.2.0

**Additional context**

<img width="2160" alt="Screenshot 2022-08-26 23 25 04" src="https://user-images.githubusercontent.com/71764733/186950070-de90ac5d-cf05-4004-b89a-67f3c2d7f711.png">

**Comment by awschristou** [comment]
Hi @inlandchris this might not be the right repo to file an issue to. To help find the right place to direct this, what are you trying to accomplish?

**Comment by inlandchris** [comment]
Forgive me if I have the wrong room. I am trying to build AWS for C++ with libraries.  I have followed AWS's instructions to build but one caveat is, they mention VS2015 and I am on VS2019. I think there is a incompatibility with their instructions. The source where I pulled is AWS-SDK-CPP.

**Comment by awschristou** [comment]
Thanks for the details -- https://github.com/aws/aws-sdk-cpp/issues is the repo where you'll want to open an issue in. I don't have the ability to transfer this issue into that repo, so I will close this issue.
