### ISSUE TITLE
AWS Explorer not found after install

### ISSUE THREAD

**Issue by kboermeester00** [aws/aws-toolkit-visual-studio#28]
After a successful install of AWS Toolkit in Visual Studio 2017, AWS Explorer is not available

## Expected Behavior
After a successful installation, I should be able to open AWS Explorer by going to View -> AWS Explorer per https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/credentials.html

## Current Behavior
Install runs without error
AWS Toolkit for Visual Studio 2017 and 2019 appears in "Extensions and Updates" and is enabled
AWS Explorer is not found in any menu

## Your Environment

* AWSSDK.Core version used: 3.3.100.0
* Service assembly and version used: 1.15.2.1
* Operating System and version:  Windows 10 Build 15063
* Visual Studio version: 2017 15.7.5
* Targeted .NET platform: Various

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by kboermeester00** [comment]
Hi @normj, I have checked that and it is enabled (it's noted in the Current Behavior section of the ticket).   I have also tried disabling it and re-enabling it as well.

**Comment by normj** [comment]
@kboermeester00 Sorry I missed that in the current behavior. 

Are any of the features of the toolkit showing up. For example right clicking on an ASP.NET or ASP.NET Core project and seeing the option to publish to beanstalk? Or in the new project dialog do you see our AWS Lambda project templates?

Can I ask what other extensions you have installed? Curious if another extension is disrupting the toolkit registering the menu item.

Also can you check the toolkit's logs for any unusual errors. The log will be saved at `C:\Users\<user-id>\appdata\Local\AWSToolkit\logs\visualstudio`

**Comment by kboermeester00** [comment]
@normj, no worries.  I don't see publish to beanstalk as an option.  I also noticed that while trying fix the issue by reading through other tickets and forums, the AWSToolkit path is referenced by other uses, but I do not have that path on my machine.

Here are some screenshots of the extensions I have
[Extensions.zip](https://github.com/aws/aws-toolkit-visual-studio/files/3453282/Extensions.zip)

**Comment by kboermeester00** [comment]
@normj, I just noticed this in the install logs.  The UI reports a successful install and the log that is displayed doesn't have any errors making it appear like a successful install.  

When looking in the temp folder to send you install logs, I noticed there are two VSIXInstaller logs related to the install. The second log has the following error, which appears to be permissions related.  This didn't get displayed to me for any of my install attempts.

"7/31/2019 3:02:51 PM - The extension with ID '12ed248b-6d4a-47eb-be9e-8eabea0ff119' is not installed to Visual Studio Professional 2017.
7/31/2019 3:02:51 PM - Microsoft.VisualStudio.ExtensionManager.RequiresAdminRightsException: You must have administrative privileges to install using the /admin switch.
   at VSIXInstaller.ProcessRestartInformation.ThrowIfRestartRequired()
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()"

I am a local admin on this computer.  I also tried to set VSIXInstaller.exe to run as admin but got an error immediately when launching AWSToolkitPackage.vsix

Hopefully this information helps.

[AWSToolKit_InstallLogs.zip](https://github.com/aws/aws-toolkit-visual-studio/files/3453512/AWSToolKit_InstallLogs.zip)

**Comment by normj** [comment]
Sorry I'm not sure what is going on based on the logs. I did notice you version of VS 2017 is a bit out of date. I would recommend patching that to the latest.

I think the next step to get the toolkit install is, preferable after updating to the latest patch version of VS 2017, is clean all of previous install artifacts and then force VS to register extensions.

**Clean Up Previous Installs**
* In Windows Explorer navigate to `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\common7\IDE\Extensions`
* In the search windows in the upper corner enter AWSToolkit
* Click on a result and select Open File Location
* Delete the parent folder that looks like a short guid
* Repeat search until nothing shows up for AWSToolkit

Now that all of the previous installs have been deleted lets force VS to rerun the extension register to not leave VS in any weird state. 

* Open Console window as Admin
* Navigate to `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\common7\IDE`
* Run the command `devenv /setup`

Now with all AWS bits removed attempt to reinstall the AWS Toolkit. If that still does not work please search `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\common7\IDE\Extensions` for any AWSToolkit dlls like you did during the clean up phase. If you do find AWSToolkit bits in the extensions folder try rerunning `devenv /setup` in the admin console.

**Comment by robertoenbarcelona** [comment]
Good afternoon, 
I have the latest version of VS 2017 and the same issue is shown, even if I install it, is not 
present then in VS.

* no Extension is present, 
* in C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\common7\IDE\Extensions after installtion there's no AWSToolkit present 
* in C:\Users\<user-id>\appdata\Local\ there's no AWSToolkit present.
* running it again, it does not show that is intalled and try to install it.

it seems that the installer really does not install anything. 


checking log there are a lot of waring and erros, notably the most important is the certificate of the same installer, is not valid.

El certificado no es válido: AWSToolkitPackage.vsix
04/11/2019 15:44:15 - Cache failed. Retrying download of '12ed248b-6d4a-47eb-be9e-8eabea0ff119,version=1.15.2.1'.
04/11/2019 15:44:15 - El certificado no es válido: AWSToolkitPackage.vsix
04/11/2019 15:44:15 - Skipping cache of package 'Component.12ed248b-6d4a-47eb-be9e-8eabea0ff119,version=1.15.2.1' since the package or a parent package had a vital failure.
04/11/2019 15:44:52 - Could not find a part of the path 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\EXTENSIONS\1QXD2JCD.YBX\AWSToolkitPackage.pkgdef'.
04/11/2019 15:44:52 - Install to Visual Studio Enterprise 2017 completed successfully. The extension has been installed to C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\EXTENSIONS\1QXD2JCD.YBX\


regards
Roberto

**Comment by normj** [comment]
The log file says it installed something in `C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\EXTENSIONS\1QXD2JCD.YBX\` can you let us know what is in that folder?

**Comment by awschristou** [comment]
Hi @tavisca-ASarupria , please try uninstalling, then re-installing the Toolkit. When the installer completes, open the installer log, and check for any log output of interest.

You will need administrator access to your computer to both install and use the Toolkit extension.

Afterwards, check the log file for details, in `%localappdata%\AWSToolkit\logs`

**Comment by awschristou** [comment]
I am closing this issue out due to lack of activity. Please try using the latest version of the AWS Toolkit for Visual Studio. If you are still experiencing a problem with the Toolkit, please file a new issue.
