### ISSUE TITLE
Publish to AWS: I could not deploy to an existing cloud app

### ISSUE THREAD

**Issue by v1ctorHB** [aws/aws-toolkit-visual-studio#282]
In Publish to AWS, the Existing Targets list did not show my project. I expected to see it there.

Toolkit: 1.35.2.0
Visual Studio: 17.3.3

**Comment by v1ctorHB** [comment]
Hi @awschristou It is a .net application that is already deployed in elastic beanstalk, but I changed computers and when trying to upload a new version of my project the aws toolkit tells me that it cannot find the project. I get the following:

Error publishing application: No .NET project found in directory 'C:\Users\project' linked to build.

**Comment by awschristou** [comment]
For the application that you already deployed, did you deploy it using "Publish to AWS", the older "Publish to AWS Elastic Beanstalk" experience, or some other tooling?

![image](https://user-images.githubusercontent.com/39839589/188748792-3e03c159-1752-4c05-b826-fcccc1f81df2.png)

**Comment by v1ctorHB** [comment]
When I tried to update the project I get the following

![1](https://user-images.githubusercontent.com/99686297/188750846-d7adba52-760b-41b9-869e-3971f140e166.png)
![2](https://user-images.githubusercontent.com/99686297/188750856-fc81092c-9e69-4562-a859-3806c6e1baf9.png)
![3](https://user-images.githubusercontent.com/99686297/188750865-961a6c9b-04c1-4627-acdc-a772af9cf2c9.png)

**Comment by awschristou** [comment]
Is the project running on a Windows or Linux beanstalk image? It appears to be a .NET 6 project, so it seems like this should appear in the new Publish to AWS experience, in the "N. Virginia" region under the "Publish to Existing Target" list.
