### ISSUE TITLE
Existing Elastic Beanstalk Environments using Windows images not showing in new Publish to AWS experience

### ISSUE THREAD

**Issue by ScottDellinger** [aws/aws-toolkit-visual-studio#285]
**Describe the bug**
I have multiple Elastic Beanstalk environments that I publish to using the existing "Publish to AWS Elastic Beanstalk" tool without issue. When I try to use the new Publish to AWS tool, those existing environments are not shown in the list.

**To Reproduce**
To reproduce this issue, I right-click on the project name and select "Publish to AWS". The existing environments do not show in the list of targets.

**Expected behavior**
Existing Elastic Beanstalk environments should show in the list of targets.

**Screenshots**
![image](https://user-images.githubusercontent.com/16200100/190925873-429fb3fc-8bb9-4fa8-9f23-cd0d97ae9590.png)
![image](https://user-images.githubusercontent.com/16200100/190925929-42080712-3e38-48d7-aee4-03db7b289e1d.png)

First screenshot shows my legacy list. Note that the second screen shot shows an environment that doesn't even exist anymore and does not show any of the ones on my legacy list.

**Computer (please complete the following information):**

- Windows Version: 11
- Visual Studio Version: 2022 Community
- AWS Toolkit for Visual Studio Version: 1.35.2.0

**Additional context**
This has been an ongoing issue since the Publish to AWS option first appeared and has not been resolved as of yet.

**Comment by awschristou** [comment]
Hi @ScottDellinger , thank you for reaching out. Are your existing Beanstalk deployments .NET Framework based applications that are running on Windows Beanstalk images? (If not, can you please describe your applications and the beanstalk compute)

**Comment by ScottDellinger** [comment]
Hi @awschristou ... that is correct... they are the default Windows images running in the Elastic Beanstalk environments with .NEt Core 3.1 applications.

**Comment by awschristou** [comment]
Thank you for the clarification. We've been getting a fair bit of feedback about Windows image based Beanstalk environments not appearing in the "Existing Target" list. We didn't have a specific issue filed for this scenario, so I've renamed this issue to represent it.

Work is currently in progress to add support for listing existing Windows based Beanstalk Environments in the underlying deploy tool - https://github.com/aws/aws-dotnet-deploy/pull/702. When this improvement becomes available in a future release of the deploy tool, we'll be able to onboard it to the Toolkit's Publish to AWS experience. I will pin this issue for visibility, given the interest it is receiving.

**Comment by awschristou** [comment]
The deploy tool has been updated to support deployments to existing Windows Beanstalk environments and released as [version 1.5.4](https://github.com/aws/aws-dotnet-deploy/releases/tag/1.5.4).

We have a test build of the Toolkit that integrates this new deploy tool release, see below for the download details. If you try it out, please leave a comment to share your experience with it.

File: [AWSToolkitPackage.v17.vsix.zip](https://github.com/aws/aws-toolkit-visual-studio/files/9728233/AWSToolkitPackage.v17.vsix.zip)
Version: 1.35.2.10060
Sha384 Hash: `A78EBF1E278CE3D1506BC10F153481D6B287FB099200E8A4DD86CF26B6F5B48B2CD97D520A5746DC9C054BC771EDDD10`

**Comment by awschristou** [comment]
Version 1.36.0.0 of the Toolkit is now available. It contains an update to the Publish to AWS experience that supports deploying .NET Core/5+ projects to existing Beanstalk environments that use Windows based images.
