### ISSUE TITLE
CodeArtifact uses old profile

### ISSUE THREAD

**Issue by roelvandenbranddvc** [aws/aws-toolkit-visual-studio#287]
Hi,

Recently we changed some accounts and credentials and so I updated the .credentials and .config file to reflect our changes. To make sure only the new profiles could be used. I removed the old ones.

This is where it gets a bit odd. The AWS Explorer works fine and uses the correct new profile and does not show the old profiles. But when I open a solution the first notification is that a profile could not be found (with an old profile name)

Where can I edit (or remove) those settings) because I cannot connect to our Code Artifact from VS anymore. It works fine from the CLI and the correct profile.

**Comment by awschristou** [comment]
Hi @roelvandenbranddvc , there are two ways you can update which credentials profile to use with your CodeArtifact repo. Both approaches update the same NuGet configuration:

- From the Toolkit, open AWS Explorer, right click on the CodeArtifact node, and click on "Select Profile...". You will then be presented with a dialog to select which profile Visual Studio should use when attempting to connect to CodeArtifact repositories. Selecting a profile and clicking OK will apply the setting.

![image](https://user-images.githubusercontent.com/39839589/192564103-8e2e40fb-4d4e-4c17-934d-8be8937410e6.png)

- From the command line, you can install the CodeArtifact NuGet Credential Provider, and configure which profile is used. See https://docs.aws.amazon.com/codeartifact/latest/ug/nuget-cli.html#nuget-configure-cli for instructions

**Comment by roelvandenbranddvc** [comment]
> Hi @roelvandenbranddvc , there are two ways you can update which credentials profile to use with your CodeArtifact repo. Both approaches update the same NuGet configuration:
> 
>     * From the Toolkit, open AWS Explorer, right click on the CodeArtifact node, and click on "Select Profile...". You will then be presented with a dialog to select which profile Visual Studio should use when attempting to connect to CodeArtifact repositories. Selecting a profile and clicking OK will apply the setting.
> 
> 
> ![image](https://user-images.githubusercontent.com/39839589/192564103-8e2e40fb-4d4e-4c17-934d-8be8937410e6.png)
> 
>     * From the command line, you can install the CodeArtifact NuGet Credential Provider, and configure which profile is used. See https://docs.aws.amazon.com/codeartifact/latest/ug/nuget-cli.html#nuget-configure-cli for instructions

Thank you very much, that did the trick. That was hard to find (for me)

**Comment by awschristou** [comment]
Thanks for letting us know that these steps worked for you. I've taken a note to see if we can make the error message more informative, and will close this issue out with the above steps as guidance.
