### ISSUE TITLE
Publish to AWS: I could not deploy to an existing cloud app

### ISSUE THREAD

**Issue by phsmiths** [aws/aws-toolkit-visual-studio#289]
In Publish to AWS, the Existing Targets list did not show my project. I expected to see it there.
I'm able to view and deploy via legacy method.

Toolkit: 1.35.2.0
Visual Studio: 17.3.5

**Comment by awschristou** [comment]
Hi @phsmiths , can you describe what type of project you are trying to deploy, and what existing AWS targets you were expecting to see in the Publish to AWS experience?

**Comment by awschristou** [comment]
I am closing this issue. Please re-open this issue to share details about your configuration. If you are working with pre-existing Windows Beanstalk deployments, please see #285 for details relating to the latest Toolkit release (v1.36.0.0)
