### ISSUE TITLE
Unable to update Lambda function in USGovCloudWest1

### ISSUE THREAD

**Issue by brpekin** [aws/aws-toolkit-visual-studio#290]
**Describe the bug**
When publishing an update to an existing Lambda function, it fails with the message, "Error creating function url config for function <Function-Name>: Unable to determine service/operation name to be authorized".  Upon researching online, I found the issue at https://github.com/aws/aws-lambda-dotnet/issues/1188.  It appears that this process requires the permission "GetFunctionURLConfig", but this permission/feature does not exist in USGovCloudWest1.  

**To Reproduce**
In the VS Solution Explorer, right-click on the Lambda project and select Publish to AWS Lambda.  Verify that the inputs are all correct (they are), and click on the Upload button.
-->

**Expected behavior**
The Lambda function gets updated.

**Computer (please complete the following information):**

- Windows Version:  Windows 10 Enterprise 21H2
- Visual Studio Version:  Enterprise 2022 64-bit 17.3.6
- AWS Toolkit for Visual Studio Version:  1.36.0.0

**Comment by awschristou** [comment]
Thank you for reaching out @brpekin - it looks like we need to propagate the changes from https://github.com/aws/aws-extensions-for-dotnet-cli/pull/221 (referenced by the issue you mentioned) into the Toolkit.

**Comment by brpekin** [comment]
Thanks for the update @awschristou . I'm glad I could provide the information to hopefully make this as easy as possible.

**Comment by awschristou** [comment]
Version 1.37.0.0 of the Toolkit is available, with a fix for the issue preventing Lambda deployments to GovCloud regions.
