### ISSUE TITLE
Extension is not installable on any currently installed product

### ISSUE THREAD

**Issue by mlvncnxx** [aws/aws-toolkit-visual-studio#291]
**Computer (please complete the following information):**

- Windows Version: Windows 11 Pro
- Visual Studio Version: Visual Studio 2022 Preview 17.4.0 Preview 4.0
- AWS Toolkit for Visual Studio Version: AWS Toolkit v17

**Install log**
10/21/2022 1:22:07 PM - Microsoft VSIX Installer
10/21/2022 1:22:07 PM - -------------------------------------------
10/21/2022 1:22:07 PM - vsixinstaller.exe version:
10/21/2022 1:22:07 PM - 17.4.2116
10/21/2022 1:22:07 PM - -------------------------------------------
10/21/2022 1:22:07 PM - Command line parameters:
10/21/2022 1:22:07 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,\\Mac\Home\Downloads\AWSToolkitPackage.v17.vsix
10/21/2022 1:22:07 PM - -------------------------------------------
10/21/2022 1:22:07 PM - Microsoft VSIX Installer
10/21/2022 1:22:07 PM - -------------------------------------------
10/21/2022 1:22:12 PM - Initializing Install...
10/21/2022 1:22:13 PM - Extension Details...
10/21/2022 1:22:13 PM - 	Identifier         : 0B82CB16-0E52-4363-9BC0-61E758689176
10/21/2022 1:22:13 PM - 	Name               : AWS Toolkit for Visual Studio 2022
10/21/2022 1:22:13 PM - 	Author             : Amazon Web Services
10/21/2022 1:22:13 PM - 	Version            : 1.36.0.0
10/21/2022 1:22:13 PM - 	Description        : The AWS Toolkit for Visual Studio is an extension for Microsoft Visual Studio on Windows that makes it easier for developers to develop, debug, and deploy .NET applications using Amazon Web Services.
10/21/2022 1:22:13 PM - 	Locale             : en-US
10/21/2022 1:22:13 PM - 	MoreInfoURL        : https://aws.amazon.com/visualstudio/
10/21/2022 1:22:13 PM - 	InstalledByMSI     : False
10/21/2022 1:22:13 PM - 	SupportedFrameworkVersionRange : [4.5,)
10/21/2022 1:22:13 PM - 
10/21/2022 1:22:17 PM - 	SignatureState     : ValidSignature
10/21/2022 1:22:17 PM - 	SignedBy           : Amazon.com, Inc.
10/21/2022 1:22:17 PM - 	Certificate Info   : 
10/21/2022 1:22:17 PM - 		-------------------------------------------------------
10/21/2022 1:22:17 PM - 		[Subject]       : CN="Amazon.com, Inc.", O="Amazon.com, Inc.", L=Seattle, S=Washington, C=US
10/21/2022 1:22:17 PM - 		[Issuer]        : CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1, O="DigiCert, Inc.", C=US
10/21/2022 1:22:17 PM - 		[Serial Number] : 0E4D3D377B5756257402C169EEED0D47
10/21/2022 1:22:17 PM - 		[Not Before]    : 9/26/2022 8:00:00 PM
10/21/2022 1:22:17 PM - 		[Not After]     : 9/27/2023 7:59:59 PM
10/21/2022 1:22:17 PM - 		[Thumbprint]    : ACFA520F8944C9B926BCDB567215434CD0201FDC
10/21/2022 1:22:17 PM - 
10/21/2022 1:22:17 PM - 	Supported Products : 
10/21/2022 1:22:17 PM - 		Microsoft.VisualStudio.Community
10/21/2022 1:22:17 PM - 			Version : [17.0,18.0)
10/21/2022 1:22:17 PM - 			ProductArchitecture : amd64
10/21/2022 1:22:17 PM - 
10/21/2022 1:22:17 PM - 	References         : 
10/21/2022 1:22:17 PM - 	Prerequisites      : 
10/21/2022 1:22:17 PM - 		-------------------------------------------------------
10/21/2022 1:22:17 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
10/21/2022 1:22:17 PM - 		Name         : Visual Studio core editor
10/21/2022 1:22:17 PM - 		Version      : [17.0,18.0)
10/21/2022 1:22:17 PM - 
10/21/2022 1:22:17 PM - Signature Details...
10/21/2022 1:22:17 PM - 	Extension is signed with a valid signature.
10/21/2022 1:22:17 PM - 
10/21/2022 1:22:17 PM - Searching for applicable products...
10/21/2022 1:22:17 PM - Found installed product - Global Location
10/21/2022 1:22:17 PM - Found installed product - Visual Studio Community 2022 Preview
10/21/2022 1:22:17 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Any other information**
I am using M1 Macbook Pro and using Parallels to use VS Studio 2022 Preview. The machine is newly built and no previous installment of AWS Toolkit

**Comment by awschristou** [comment]
Hi @mlvncnxx , two things to look into:
- are you able to install other extensions without issue? 
- are you running with administrative privileges on Windows? The Toolkit extension requires this in order to install

If you launch the Visual Studio Installer from the start menu, it might be worth trying to run a "Repair" to see if it adjusts anything, then rebooting, and trying to install the Toolkit again.

**Comment by mlvncnxx** [comment]
Hi @awschristou I've tried repairing the visual studio but nothing happened and still the same error. for other extensions, I actually just need the AWS Toolkit so I have not tried it. For my Windows, I'm running with administrative privileges as well.

I actually tried asking my other colleagues that are using m1 mac and parallel and they didn't encounter this error.

**Comment by awschristou** [comment]
Checking if another extension installs successfully could help see if there is an issue with your Visual Studio installation. You might want to try uninstalling, then reinstalling Visual Studio, and restarting Windows, then try to install the AWS Toolkit again.

If installing the Toolkit continues to fail, please attach the whole log provided by the VSIX installer. Maybe there are some more clues in there.

**Comment by davidscheidt** [comment]
Same issue.  Looks like the VSIX installer needs the ARM64 to be part of the productarchitecture in the extensions file.  It was working previously, but look like it's getting enforced with the latest install process.

See https://learn.microsoft.com/en-us/visualstudio/extensibility/arm64/target-arm64-visual-studio-extension?view=vs-2022

**Comment by awschristou** [comment]
It looks like there is a requested use case using the Toolkit from Arm based MacBooks running (Arm based) Windows on Parallels.

The Toolkit does not support Arm64 Visual Studio at this time. The Toolkit's feature set needs to be tested using an Arm based system in order to determine which features do and do not work out of the box. For features that do not work, we will have to figure out what changes are required in order to support Arm.

I have created a more generalized feature request #302 to collect interest in Arm support. Please add a reaction to that request.

I will close this issue to avoid having duplicated issues open.

**Comment by richardkeller411** [comment]
> Same issue. Looks like the VSIX installer needs the ARM64 to be part of the productarchitecture in the extensions file. It was working previously, but look like it's getting enforced with the latest install process.
> 
> See https://learn.microsoft.com/en-us/visualstudio/extensibility/arm64/target-arm64-visual-studio-extension?view=vs-2022

This is easy. Enough.   Bump +1 here
