### ISSUE TITLE
[dotnet] Unable to publish to cloundfront target when using central package management.

### ISSUE THREAD

**Issue by teddy-mindcompass** [aws/aws-toolkit-visual-studio#292]
**Describe the bug**
When using central package management in Dotnet solution, the AWS toolkit is unable to deploy web project to cloundfront target.

**To Reproduce**
1. Create a simple dotnet web project
2. Introduce package management (Directory.Packages.props)
3. Update the csproj the reference the packages (without version because they are in Directory.Packages.props)
4. Try to publish to a cloudfront target

**Expected behavior**
The behavior should be the same as when we are using a solution without central package management.

  
**Computer (please complete the following information):**

- Windows Version: 11 22H2
- Visual Studio Version: 2022 17.3.6
- AWS Toolkit for Visual Studio Version: 1.36.0.0

**Additional context**
Usage via visual studio, and command line
https://devblogs.microsoft.com/nuget/introducing-central-package-management/

**Comment by awschristou** [comment]
I'm going to close this issue since it hasn't received any updates in a while. If you are able to provide additional details, please re-open the issue and share an update.
