### ISSUE TITLE
Visual Studio Extension "AWS was not able to validate the provided access credentials"

### ISSUE THREAD

**Issue by alceuscardoso** [aws/aws-toolkit-visual-studio#294]
Hi,

I deployed my .net core application on AWS Fargate and everything was working perfectly, I had already made changes to the application and published it again.
But today when I went to do a new deploy I'm getting the message "AWS was not able to validate the provided access credentials". I tried to update the extension to the latest version but it didn't work.

The message says "Check the deployment output for more details" but I couldn't find any details about the error.

The error occurs deploying AWS CDK Project. The container image  to ECR is working.

**Extension message:**

[Error at /MY-APP/Recipe] AWS was not able to validate the provided access credentials

Found errors

MY-APP could not be published as ASP.NET Core App to Amazon ECS using AWS Fargate: We had an issue deploying your application to AWS. Check the deployment output for more details. Deployment took 72,68s.
WEB-API-PROJECT-NAME failed to publish to AWS.

**Visual Studio Output**

Publish targets found for WEB-API-PROJECT-NAME: 3
Republish targets found for WEB-API-PROJECT-NAME: 2
Starting to publish WEB-API-PROJECT-NAME
MY-APP could not be published as ASP.NET Core App to Amazon ECS using AWS Fargate: We had an issue deploying your application to AWS. Check the deployment output for more details. Deployment took 72,68s.
WEB-API-PROJECT-NAME failed to publish to AWS.

**Comment by shruti0085** [comment]
Hello @alceuscardoso, thanks for reaching out. 
A couple of questions to understand the situation:
* What type of credentials are you using - are they session based credentials?
* If you try reloading the publishing experience (after closing any existing open ones for the given project), is it successfully able to show publish targets for the given application?
