### ISSUE TITLE
Can't access npm packages hosted in CodeArtifact from "Install New npm packages" dialog

### ISSUE THREAD

**Issue by ScottDellinger** [aws/aws-toolkit-visual-studio#295]
I've followed these instructions closely and everything worked as expected while inputting settings:

https://docs.aws.amazon.com/codeartifact/latest/ug/nuget-visual-studio.html

![options](https://user-images.githubusercontent.com/16200100/200012049-bbf7d32c-c84e-4c57-8ad3-266cedef90d2.png)
![profile](https://user-images.githubusercontent.com/16200100/200012054-166051c1-e6fd-4b70-901b-39b58e98c8f2.png)

However, I have been unable to get my repo to show up in the NuGet package manager.

![image](https://user-images.githubusercontent.com/16200100/200012682-4763a54a-b559-4a9f-b401-f9d508acffcf.png)

Is there something I'm missing?

**Comment by awschristou** [comment]
The Toolkit provides assistance for connecting Visual Studio to CodeArtifact's NuGet packages. You are trying to access npm packages from CodeArtifact. The Toolkit doesn't have any assistance for npm packages. I'm not sure if Visual Studio is capable of accessing alternate package sources from their package manager dialog, but configuring your system with [Configure and use npm with CodeArtifact](https://docs.aws.amazon.com/codeartifact/latest/ug/npm-auth.html) should at least get you up and running from the command line.

**Comment by saurabhajmera** [comment]
closing this issue since @awschristou comment addresses the question
