### ISSUE TITLE
Publish to AWS: I could not deploy to an existing cloud app

### ISSUE THREAD

**Issue by babthamotharan** [aws/aws-toolkit-visual-studio#297]
In Publish to AWS, the Existing Targets list did not show my project. I expected to see it there.

Toolkit: 1.36.0.0
Visual Studio: 17.2.6

**Comment by ThamotharanTK** [comment]
Hi, I have created one EC2 account, And I installed .net core and deployed my code by WinSCP. 
But I would like to deploy the source using the AWS extension in Visual Studio 2022. 
Could explain to me how to deploy it?

**Comment by babthamotharan** [comment]
Hi, I have created one EC2 account, And I installed .net core and deployed my code by WinSCP.
But I would like to deploy the source using the AWS extension in Visual Studio 2022.
Could explain to me how to deploy it?

**Comment by awschristou** [comment]
Have a look at the user guide page that explains the Publish to AWS experience: https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/publish-experience.html

We would be interested to know if this helps you to deploy your application. If you have suggestions for improvements to the user guide, please let us know.

**Comment by saurabhajmera** [comment]
@babthamotharan, closing this issue, since the user guide should provide you the answer for your question. Please feel free to re-open this if you have further questions.
