### ISSUE TITLE
Feature request: Add support for using temporary credentials

### ISSUE THREAD

**Issue by srcno** [aws/aws-toolkit-visual-studio#30]
**Is your feature request related to a problem? Please describe.**
We primarily use SAML for authenticating developers to our AWS environment. We have tooling that can add those credentials to the .NET Credential Store and/or the ~/.aws/credentials files to ensure applications can interact with our AWS account. For most applications this works well. However, the AWS Toolkit for Visual Studio will load those credentials only at startup, so when those credentials expire a few hours later, Visual Studio must be restarted to continue to use them. Consequently, we must also give developers IAM User accounts.

**Describe the solution you'd like**
At the very least, we would like the AWS Toolkit to periodically reload the credentials either at an interval, when an operation fails due to expiring, at the request of the user, and/or at the request of an API call. It may be nice to have a UI where someone can call their third-party SSO provider and handle the loading of credentials automatically.

**Describe alternatives you've considered**
We are using IAM Users

**Comment by johnwc** [comment]
I second this issue. Our SAML provider only creates tokens that last an hour. So we must close and restart Visual Studio once an hour for it to use the new tokens that are stored in the profiles.

I'd expect that the tooling would read the tokens/keys in the profile upon usage, and not preload and cache them when VS starts.

**Comment by powersparks** [comment]
Aye! This feature doesn’t make sense.
My two factor authentication is based on my iam user, which is updated every 24 hours. I can not create stacks, but I can use a lot of other features. I thought the issue was permission, not a constraint in the tool.

**Comment by Rob-El** [comment]
We need this feature as well, and I imagine pretty much every major company does too.  Almost everyone uses SSO of some kind, and almost all in the Education world use SAML.

IAM users violates our security policy.  Everyone has to be centrally authenticated.

We also use AWS SSO, fwiw.

(If anyone has a good workaround, please post!)

**Comment by zuboje** [comment]
I have to add this is a major bummer. As an organization, we want to use SSO and any large organization does, it makes sense, but the fact that I have to daily update my tokens (and sometimes more than once per day) is a huge drawback. this is not visual studio tools but this is CLI too. The main reason is that the %USERPROFILE%\.aws\credentials file is not being updated, this my credentials constantly expire. what Amazon should do (like many other vendors did) simply if the token expired, do popup with the browser to authenticate the user again, update the credentials file on success and return back. Microsoft does this within VS with Microsoft accounts, I am sure this would not be that hard that if your tool detects expired credentials simply prompt to re-authenticate.

**Comment by awschristou** [comment]
Version 1.21.0.0 of the Toolkit contains support for AWS SSO based credentials.

Details can be found at:
* Blog post: https://aws.amazon.com/blogs/developer/introducing-aws-toolkit-for-visual-studio-support-for-aws-sso-and-assume-role-with-mfa/
* User docs: https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/sso-credentials.html
