### ISSUE TITLE
Cloud Watch does not appear in AWS Explorer

### ISSUE THREAD

**Issue by ppittle** [aws/aws-toolkit-visual-studio#300]
**Describe the bug**

 I'm trying to view my Amazon CloudWatch Logs in Visual Studio using the AWS Toolkit for Visual Studio and following this [announcement](https://aws.amazon.com/about-aws/whats-new/2022/06/aws-toolkit-visual-studio-amazon-cloudwatch-logs-integration/) which points to these instructions:  https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/cloudwatch-log.html

However, I don't see CloudWatch in the Services list. 
![image](https://user-images.githubusercontent.com/1190907/201270364-6592f8e6-6caa-48b8-9eb1-206dee76eca8.png)

**To Reproduce**

1. Open Visual Studio 2022
2. Open AWS Explorer
3. Ensure Crendentials drop down has a valid profile selected
4. Ensure Region is selecting a region with existing logs
5. Notice that Cloud Watch does not appear in Services List

**Expected behavior**

Expect a link to open Cloud Watch logs

**Screenshots**

![image](https://user-images.githubusercontent.com/1190907/201270364-6592f8e6-6caa-48b8-9eb1-206dee76eca8.png)

**Computer (please complete the following information):**

- Windows Version: 10 
- Visual Studio Version: 2022
- AWS Toolkit for Visual Studio Version: 1.35.2.0

**Additional context**

I can see my Cloud Watch Logs from AWS Console:
![image](https://user-images.githubusercontent.com/1190907/201270691-4e49d4b0-600f-4d8b-901c-10ec1c2b2f4c.png)

**Comment by awschristou** [comment]
Hi @ppittle , please try updating to the latest version of the Toolkit (currently, version 1.37.0.0). If it still does not appear for you, perhaps your Toolkit logs can help explain why it is missing. From that newer version of the toolkit, go to the Extensions menu > AWS Toolkit > View Toolkit Logs, then attach your logs to this issue.

**Comment by ppittle** [comment]
Upgraded to 1.37.0 and can now see Amazon CloudWatch!
