### ISSUE TITLE
Lambda JSON generation features a Typo (Simple S3 project)

### ISSUE THREAD

**Issue by sruchet** [aws/aws-toolkit-visual-studio#304]
BUG DESCRIPTION
When creating a Simple S3 Lambda in VS2022 with the 2022 toolkit, there is a missing letter in the JSON configuration regarding the function-handler declaration: the namespace "Function" is used when it should be "Functions", plural.

For example, creating my S3 Simple action "ActionUpload", I get this line in aws-lambda-tools-defaults.json:
    "function-handler"     : "AWSLambdaActionUpload::AWSLambdaActionUpload.Function::FunctionHandler",

whereas the correct line would be:
    "function-handler"     : "AWSLambdaActionUpload::AWSLambdaActionUpload.Functions::FunctionHandler",

REPRODUCTION
To reproduce: create any S3 Simple Lambda and check the created JSON.

I had to check with a default file to find out even it wouldn't pass S3 Put invoke for this reason.

Thanks for your work guys, this whole setup is very very nice! :)

SETUP
- Windows Version: 10
- Visual Studio Version: VS2022 Community, downloaded today 2022/11/26
- AWS Toolkit for Visual Studio Version: 2022, , downloaded today 2022/11/26

**Comment by shruti0085** [comment]
Thank you for bringing this to our attention @sruchet.
This is a bug and we have cut an issue over to AWS Lambda Tools https://github.com/aws/aws-lambda-dotnet/issues/1377
Once the fix has been made, we will update the toolkit to consume the updated lambda blueprints.

Meanwhile, we are glad to hear that you have found a workaround.

**Comment by sruchet** [comment]
That's great to hear! Thank you guys and keep up the good work. :)

**Comment by awschristou** [comment]
I've re-opened this issue. We'll keep it open until we have updated blueprints available in the Toolkit that fix the issue.

**Comment by sruchet** [comment]
Alright, thanks!

**Comment by awschristou** [comment]
The blueprints have been updated. The next time you create the "S3 Simple Lambda" project, it will have the correct filename and Lambda handler.
