### ISSUE TITLE
Terminated EC2 instances are showing in the toolkit.

### ISSUE THREAD

**Issue by roopeshkurian** [aws/aws-toolkit-visual-studio#306]
**Describe the bug**
I have terminated a few EC2 instances. But it's still displayed in "Publish to existing Target". If I try to use and publish to one of the terminated instances it gives an error.   

**To Reproduce**
Publish to a new EBS. 
Terminate the EBS and EC2 instances.
This terminated instance won't disappear from the toolkit list.
If we try to upload again to a terminated instance it is giving an error. 

Error: The stack named fujideveloper failed to deploy: UPDATE_ROLLBACK_FAILED (The following resource(s) failed to update: [RecipeBeanstalkEnvironment83CC12DE]. ): Resource handler returned message: "No Application named 'xxxxxxx' found. 

**Expected behavior**
Terminated EC2 or EBS instances should disappear from the toolkit list after a certain time. 
or should have a delete button to remove it from the toolkit listing. 

**Computer (please complete the following information):**

- Windows Version: Windows 10
- Visual Studio Version: 17.4.1 
- AWS Toolkit for Visual Studio Version:1.37.0.0

**Additional context**

**Comment by awschristou** [comment]
The deployment may have been managed with a CloudFormation stack. Can you look for a stack named fujideveloper? You will want to delete this stack in order to remove all resources associated with your deployment. Once the stack has been deleted, it will no longer appear in the "Publish to existing Target" list.

**Comment by roopeshkurian** [comment]
Thank you so much for your help. I have deleted the stacks. Now everything is perfect.
