### ISSUE TITLE
where are the log files for msbuild commands used in deployment?

### ISSUE THREAD

**Issue by gotmike** [aws/aws-toolkit-visual-studio#307]
i am trying to debug an [issue in aws-toolkit-azure-devops](https://github.com/aws/aws-toolkit-azure-devops/issues/492) and my deployment works fine here, so i'd like to mimic the msbuild parameters in azure devops.

where can i find the actual msbuild commands used during deployment?

i see the `echo off` output in the window, but i'm not seeing the actual commands used.

**Comment by awschristou** [comment]
Hi @gotmike , are you deploying with the newer Publish to AWS experience, or the legacy Beanstalk deployment feature?

![image](https://user-images.githubusercontent.com/39839589/205369735-22a3c029-123a-49b2-882b-eadedef5e7a8.png)

If you are using the legacy experience, the `dotnet publish` command that is used to package your project up for deployment can be found in the output pane. (View menu, Output, then show output from "Amazon Web Services".

Here's mine for example: 
![image](https://user-images.githubusercontent.com/39839589/205374028-c948de6a-5d7a-4d06-9c13-f6209b1e20bd.png)

If you are using the new experience, I don't believe this is logged, but you might be able to infer what the commands are from the underlying deploy tool code: https://github.com/aws/aws-dotnet-deploy/blob/main/src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs#L103

**Comment by gotmike** [comment]
i can actually use either, that's a great tip! i'll check it out! thx a ton!
