### ISSUE TITLE
AWS Elastic Beanstalk Launch Templates

### ISSUE THREAD

**Issue by jasonkhogan** [aws/aws-toolkit-visual-studio#308]
The load balancer deployment method seems to default to using Launch Configuration with is no longer supported by AWS, can you configure the deployment method to use Launch Templates instead?

**Comment by shruti0085** [comment]
@jasonkhogan can you elaborate on your issue with steps for reproduction?

**Comment by shruti0085** [comment]
Closing this issue since we haven’t heard back from you in a while. If you are still encountering this problem please open a new issue with detailed steps to reproduce it.
