### ISSUE TITLE
Feature Request: Add support for additional AWS regions in Visual Studio Toolkit

### ISSUE THREAD

**Issue by rsinghaws** [aws/aws-toolkit-visual-studio#31]
AWS toolkit for Visual Studio doesn't support the below AWS regions:

- "ap-east-1"
- "ap-northeast-3"
- "me-south-1"

When we navigate to Microsoft Visual Studio >> AWS Explorer >> Region , the mentioned regions doesn't appear in the drop down. 

Can we please include these regions as well ?

**Comment by rli** [comment]
This change has been pushed out and should be automatically fetched by the toolkit on the next restart of Visual Studio.

Please re-open this issue if that is not the case.
