### ISSUE TITLE
SSO token provider configuration with automatic authentication refresh does not work

### ISSUE THREAD

**Issue by mikereinhold** [aws/aws-toolkit-visual-studio#313]
**Describe the bug**
AWS Toolkit for Visual Studio does not recognize available profiles that use the sso-session configuration in the profile. This configuration is used to perform automatic token refresh for with AWS IAM Identity Center as described in the [AWS CLI documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html#sso-configure-profile-token). Recent versions of the AWS CLI (confirmed in 2.9.12, possibly starting in 2.9.0 per [changelog](https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst) entry for new feature `configure sso-session`)

Profiles containing the sso-session configuration are ignored and not shown as available AWS profiles in the AWS Toolkit for Visual Studio. 

**To Reproduce**
Using latest version of the AWS CLI (2.9.12)
1. Configure the AWS CLI using `aws configure sso`  and follow the prompts to configure an SSO profile for your AWS account. Edit: enter a session name when prompted to generate an automatic refresh SSO profile rather than a legacy manual refresh profile.
2. Open Visual Studio to any local folder or project.
3. Open the AWS Explorer extension component.
4. Credentials drop down will not include the new profile

To validate this is the issue, reconfigure the profile as a manual token refresh SSO profile instead of automatic refresh:
1. Remove the `sso-session` setting from under the profile in the credentials file
2. Remove the `sso-session` setting from under the profile in the config file
3. Copy the `sso_start_url` and `sso_region` settings from the `sso-session` section of the config file to the profile in question
4. Go back to Visual Studio and confirm the profile is now visible

**Expected behavior**
AWS profiles using automatic SSO token refresh should be found by the AWS Toolkit for Visual Studio to enable automatic authentication refresh for users. 

**Computer (please complete the following information):**

- Windows Version: Windows Server 2019
- Visual Studio Version: 17.4.1
- AWS Toolkit for Visual Studio Version: 1.38.0.0

**Additional context**

**Comment by awschristou** [comment]
Hi @mikereinhold , I tried using `aws configure sso` and was able to see this profile in the AWS Explorer.

Assuming you ran this command while Visual Studio was open, does the profile appear if you try closing and then re-opening Visual Studio?

The Toolkit has a better time working with the credentials file instead of the config file. Have you tried hand-creating a profile in the `credentials` file? The user guide has an illustration of the expected fields: https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/sso-credentials.html

**Comment by mikereinhold** [comment]
Hi @awschristou, 

A couple quick clarifications:
* Visual Studio was closed when modifying the profile configuration via the `aws configure sso` command
* When following the `aws configure sso` prompts, the CLI recommends you enter a Session Name, which I did (I should have clarified this in my reproduction notes above - will edit)
* Using a session name in the `aws configure sso` prompt flow results in the `config` file having an sso_session parameter, indicating that the SSO profile is automatically refreshed vs manually refreshed (this is the new default, preferred SSO configuration)
* I also manually created the profiles in the `credentials` file with the same results
* A quick comparison with the AWS Toolkit for Visual Studio Code indicates that the VS Code version of the toolkit properly handles the sso_session configuration in both the `config` and `credentials` files

From the user guide, there's no explicit mention of the Toolkit expecting the sso_session parameter as required for automatic credential refresh... So maybe this should be a feature request to bring the Toolkit for Visual Studio up to speed with the default cli workflow for generating SSO profiles

**Comment by awschristou** [comment]
Thank you for the clarification. I hadn't updated my AWS CLI to a version newer than 2.9.0. Once I updated to the latest, I am able to reproduce the issue.

I named my profile "zzzzzzz" and the Toolkit log reports the following:
> ERROR Amazon.AWSToolkit.Credentials.Core.ProfileCredentialProviderFactory - The following credentials could not be loaded: 
> zzzzzzz: zzzzzzz cannot reference an SSO Session and assign an SSO Region or SSO StartUrl

We should be able to investigate this now.

**Comment by awschristou** [comment]
Version 1.39.0.0 of the Toolkit has been released, containing a fix for this issue.

Credential profiles created with the AWS CLI command `aws configure sso` are supported in this version of the Toolkit.
