### ISSUE TITLE
Can't open the "Publish to AWS" window

### ISSUE THREAD

**Issue by rlucasfm** [aws/aws-toolkit-visual-studio#315]
Trying to use the AWS Toolkit to publish a .NET application on EC2, when I try to use the "Publish to AWS" button, it returns me the following error: 
![image](https://user-images.githubusercontent.com/28231563/213492829-4567c4cd-91e3-4b9a-9b60-3bf733af885c.png)
I can use the "Publish container to AWS (Legacy)" though.

**Comment by awschristou** [comment]
I'm going to close this issue since it hasn't received any updates in a while. If you are able to provide additional details, please re-open the issue and share an update.
