### ISSUE TITLE
I don't see AWS Project Templates when creating new projects - VS 2022 Community edition

### ISSUE THREAD

**Issue by eliassal** [aws/aws-toolkit-visual-studio#317]
**Describe the bug**
Installed the AWS Toolkit for VS 2022 CE, I can see

![image](https://user-images.githubusercontent.com/8447864/215067626-8de9980f-e1db-4d62-84dd-d627b9a08a62.png)

**To Reproduce**

Steps to reproduce the behavior

1. Install VS 2022 CE
2. Add AWS toolkit for VS 2022
3. File > New Project
4. Type AWS
5.  No  aws projects templates

![image](https://user-images.githubusercontent.com/8447864/215068811-954b6220-70e1-4d92-8770-b9c589f242bf.png)

**Expected behavior**
Have more than 1 aws templates
**Screenshots**
see above

**Computer (please complete the following information):**

- Windows Version:  Microsoft Windows 10 Enterprise - Version	10.0.19044 Build 19044
- Visual Studio Version: Microsoft Visual Studio Community 2022 (2) (64-bit) - Current Version 17.4.3

- AWS Toolkit for Visual Studio Version: Installed yesterday using add extension inside VS

**Comment by awschristou** [comment]
Hi @eliassal , thank you for reaching out. Visual Studio's "New Project" dialog has three separate filter dropdowns: language, platform, and project type (circled in the image below). In your screenshot, you are filtered to the "Web" project type. If you clear your project filter dropdowns, you should be able to filter down to AWS templates, as shown here:

![image](https://user-images.githubusercontent.com/39839589/215156286-029b52cc-c19a-49b3-b414-453ec11c61fc.png)

**Comment by eliassal** [comment]
Thanks, my bad
