### ISSUE TITLE
Can I install the toolkit on a virtual machine on Apple Silicon ?

### ISSUE THREAD

**Issue by joseines** [aws/aws-toolkit-visual-studio#318]
Using windows parallels, I installed windows 11 and downloaded VS 2022 professional. I tried looking for the aws toolkit on the extensions manager, and it doesn't appear. I also tried downloading it directly and I get an error _"The extension is not installable on any currently installed products."_
I also saw on the aws page for the toolkit that it requires VS 2002 (AMD64), does this mean it requires an AMD64 chip?
Any help would be greatly appreciated.

This is the installation log:
2/10/2023 7:43:39 PM - Microsoft VSIX Installer
2/10/2023 7:43:39 PM - -------------------------------------------
2/10/2023 7:43:39 PM - vsixinstaller.exe version:
2/10/2023 7:43:39 PM - 17.4.2120
2/10/2023 7:43:39 PM - -------------------------------------------
2/10/2023 7:43:39 PM - Command line parameters:
2/10/2023 7:43:39 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,\\Mac\Home\Downloads\AWSToolkitPackage.v17.vsix
2/10/2023 7:43:39 PM - -------------------------------------------
2/10/2023 7:43:39 PM - Microsoft VSIX Installer
2/10/2023 7:43:39 PM - -------------------------------------------
2/10/2023 7:43:40 PM - Initializing Install...
2/10/2023 7:43:41 PM - Extension Details...
2/10/2023 7:43:41 PM - 	Identifier         : 0B82CB16-0E52-4363-9BC0-61E758689176
2/10/2023 7:43:41 PM - 	Name               : AWS Toolkit for Visual Studio 2022
2/10/2023 7:43:41 PM - 	Author             : Amazon Web Services
2/10/2023 7:43:41 PM - 	Version            : 1.38.0.0
2/10/2023 7:43:41 PM - 	Description        : The AWS Toolkit for Visual Studio is an extension for Microsoft Visual Studio on Windows that makes it easier for developers to develop, debug, and deploy .NET applications using Amazon Web Services.
2/10/2023 7:43:41 PM - 	Locale             : en-US
2/10/2023 7:43:41 PM - 	MoreInfoURL        : https://aws.amazon.com/visualstudio/
2/10/2023 7:43:41 PM - 	InstalledByMSI     : False
2/10/2023 7:43:41 PM - 	SupportedFrameworkVersionRange : [4.5,)
2/10/2023 7:43:41 PM - 
2/10/2023 7:43:45 PM - 	SignatureState     : ValidSignature
2/10/2023 7:43:45 PM - 	SignedBy           : Amazon.com, Inc.
2/10/2023 7:43:45 PM - 	Certificate Info   : 
2/10/2023 7:43:45 PM - 		-------------------------------------------------------
2/10/2023 7:43:45 PM - 		[Subject]       : CN="Amazon.com, Inc.", O="Amazon.com, Inc.", L=Seattle, S=Washington, C=US
2/10/2023 7:43:45 PM - 		[Issuer]        : CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1, O="DigiCert, Inc.", C=US
2/10/2023 7:43:45 PM - 		[Serial Number] : 0E4D3D377B5756257402C169EEED0D47
2/10/2023 7:43:45 PM - 		[Not Before]    : 9/26/2022 6:00:00 PM
2/10/2023 7:43:45 PM - 		[Not After]     : 9/27/2023 5:59:59 PM
2/10/2023 7:43:45 PM - 		[Thumbprint]    : ACFA520F8944C9B926BCDB567215434CD0201FDC
2/10/2023 7:43:45 PM - 
2/10/2023 7:43:45 PM - 	Supported Products : 
2/10/2023 7:43:45 PM - 		Microsoft.VisualStudio.Community
2/10/2023 7:43:45 PM - 			Version : [17.0,18.0)
2/10/2023 7:43:45 PM - 			ProductArchitecture : amd64
2/10/2023 7:43:45 PM - 
2/10/2023 7:43:45 PM - 	References         : 
2/10/2023 7:43:45 PM - 	Prerequisites      : 
2/10/2023 7:43:45 PM - 		-------------------------------------------------------
2/10/2023 7:43:45 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2/10/2023 7:43:45 PM - 		Name         : Visual Studio core editor
2/10/2023 7:43:45 PM - 		Version      : [17.0,18.0)
2/10/2023 7:43:45 PM - 
2/10/2023 7:43:45 PM - Signature Details...
2/10/2023 7:43:45 PM - 	Extension is signed with a valid signature.
2/10/2023 7:43:45 PM - 
2/10/2023 7:43:45 PM - Searching for applicable products...
2/10/2023 7:43:45 PM - Found installed product - Visual Studio Professional 2022 (2)
2/10/2023 7:43:45 PM - Found installed product - Global Location
2/10/2023 7:43:45 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by awschristou** [comment]
Hi @joseines this sounds like you are running on ARM based CPU. You'll want to follow https://github.com/aws/aws-toolkit-visual-studio/issues/302 for updates on ARM support.

> I also saw on the aws page for the toolkit that it requires VS 2002 (AMD64), does this mean it requires an AMD64 chip?

This means it is expecting to be running on an x86 based chip. It could be intel for example, it is not restricted to AMD.

**Comment by joseines** [comment]
Thank you @awschristou ! I'll close the issue and follow 302!
