### ISSUE TITLE
error while publishing docker image to ecr repository

### ISSUE THREAD

**Issue by fpranadi** [aws/aws-toolkit-visual-studio#320]
Pushing the docker image to ECR repository...
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error saving credentials: error storing credentials - err: exit status 1, out: `error storing credentials - err: exit status 1, out: `The stub received bad data.``

wanotif1balisoketcom could not be published as ASP.NET Core App to Amazon ECS using AWS Fargate: Failed to login to Docker due to the following reason:
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error saving credentials: error storing credentials - err: exit status 1, out: `error storing credentials - err: exit status 1, out: `The stub received bad data.``

wanotif1.balisoket.com failed to publish to AWS.

- Windows Version: 10
- Visual Studio Version 2019:
- AWS Toolkit for Visual Studio Version:

**Comment by ashovlin** [comment]
I've created https://github.com/aws/aws-dotnet-deploy/issues/754. The Visual Studio Toolkit wraps the .NET Deployment Tool, so any changes to behavior here will have to originate in that repository.

https://stackoverflow.com/questions/60807697/docker-login-error-storing-credentials-the-stub-received-bad-data does mention a possible workaround for the same error message involving Docker configuration.

How are your AWS credentials configured?

**Comment by ashishdhingra** [comment]
Issue with similar error is reported at https://github.com/aws/aws-cli/issues/5636.

**Comment by ashishdhingra** [comment]
Based on testing with `Get-ECRLoginCommand` PowerShell Cmdlet, the token/password obtained:
- For non-SSO based profile is approx. `2165` characters long.
- For SSO based profile (after `aws sso login`) is approx. `2277` characters long.

`(Get-ECRLoginCommand -ProfileName <<SSO-Profile-Name>>).Password | docker login --username AWS --password-stdin <<account-id>>.dkr.ecr.us-east-2.amazonaws.com` works fine.

Tried using SSO profile with `dotnet aws deploy --profile sso-profile-name --region us-east-1`, worked fine.

**Comment by ashishdhingra** [comment]
@fpranadi Good evening. Could you please review https://github.com/aws/aws-toolkit-visual-studio/issues/320#issuecomment-1433723105 and respond with requested information. If this is no longer an issue, please share the root cause so that it is helpful to other users experiencing similar error and confirm if this issue could be closed.

**Comment by awschristou** [comment]
This issue has grown stale. Without additional steps to reproduce or supporting details, we aren't able to investigate this issue further. If you are still encountering this problem, please open a new issue and provide supporting details.
