### ISSUE TITLE
After upgrading to version 1.39.0.0 - Unable to start a deployment session

### ISSUE THREAD

**Issue by timothy-m-allen** [aws/aws-toolkit-visual-studio#322]
After upgrading to AWS Toolkit for Visual Studio 2022 version 1.39.0.0, I'm unable to start a deployment session.

- Windows Version: Windows 11
- Visual Studio Version: VS Studio Community 2022 Version 17.4.5 
- AWS Toolkit for Visual Studio Version: 1.39.0.0

Screenshot
![2023-02-18_08-38-24](https://user-images.githubusercontent.com/125709297/219821701-31a0e31d-8796-4a88-8ba8-f7dea34f8d43.png)

Log output
[log_2023-02-18_08-20-28_18524.txt](https://github.com/aws/aws-toolkit-visual-studio/files/10772638/log_2023-02-18_08-20-28_18524.txt)

**Comment by awschristou** [comment]
Hi @timothy-m-allen can you check that you have .NET 6 (or newer) installed by running `dotnet --info` from the command line?

Based on the log, did you happen to hit cancel on the progress dialog while the Publish dialog was starting up? If you close Visual Studio and re-launch it, I'm wondering this issue happens again.

**Comment by timothy-m-allen** [comment]
I'm not hitting a cancel button, it just seems to time out after about 90 seconds.

![2023-02-18_09-28-38](https://user-images.githubusercontent.com/125709297/219824473-ffd84a84-3919-4908-a48f-a63545210eab.png)

Is it possible for me to revert back to the older version of the Toolkit?

I've tried:
1. Restarting visual studio
2. Restarting my computer
3. Uninstalling AWS toolkit
4. Reinstalling AWS toolkit

**Comment by awschristou** [comment]
Thanks for sharing your dotnet info.

Under the hood, the Publish to AWS experience relies on the [.NET Deployment Tool](https://github.com/aws/aws-dotnet-deploy). Here are two things to try, which may help locate the problem:

1. Allow the Toolkit to re-install the deploy tool

It could be that the Toolkit wasn't able to update its copy of the deploy tool, resulting this bad state.

Close all running instances of Visual Studio. Then open Windows Explorer to the `%localappdata%\AWSToolkit\aws.deploy.tools` folder, and remove the contents of this folder. Re-launch Visual Studio. At start up, the Toolkit will re-install the deploy tool into this folder. See if you are able to start a deployment session.

2. Try running the deploy tool directly

It would be useful to verify that the same version of the deploy tool is able to properly work with your project.

From a command prompt, run `dotnet tool install -g aws.deploy.tools` to install the deploy tool outside the context of the Toolkit. Then change directories into the folder with your project's .csproj file. Now try to start the deployment process using the cli by running `dotnet aws deploy`. See if this is able to bring you to the prompts asking you to perform a new or existing deployment, and if it offers you the list of deployment targets to choose from. (You don't need to actually perform the deployment if you aren't interested, it will be enough to know if there is a problem getting to that stage).

(In case you're curious, additional details about the steps involved in this approach can be seen at https://aws.github.io/aws-dotnet-deploy/)

**Comment by timothy-m-allen** [comment]
I updated the aws.deploy.tools by using `dotnet tool update -g aws.deploy.tools`, that has resolved this issue.
