### ISSUE TITLE
Publish to AWS: I could not deploy to an existing cloud app

### ISSUE THREAD

**Issue by takasugitut** [aws/aws-toolkit-visual-studio#328]
In Publish to AWS, the Existing Targets list did not show my project. I expected to see it there.

Toolkit: 1.40.0.0
Visual Studio: 17.5.2

**Comment by awschristou** [comment]
Hi @takasugitut , can you please explain what type of project you are trying to publish? Is it .NET Framework, .NET Core, or .NET 5+, and what version? Is it an executable or a class library, etc -- what other details can you share about your project?

**Comment by awschristou** [comment]
We haven't received new information, and will close the issue. If you have specifics you can share, please re-open the issue and describe the project you are working with, and the deployment you were expecting to see.
