### ISSUE TITLE
Obscure Secret Access Key from the New Profile Settings

### ISSUE THREAD

**Issue by marciogmorales** [aws/aws-toolkit-visual-studio#33]
**Is your feature request related to a problem? Please describe.**

After installing the AWS Toolkit for Visual Studio, you must configure a new profile to start using the toolkit. During the first page, you must import the Credential.csv file from the IAM Page to the Visual Studio.

The concern is that after the file has been imported, the Secret Access Key field is in plain text.

Visual Studio 2019 Community Build: 16.2.2
AWS Toolkit for Visual Studio 1.15.2.1

**Describe the solution you'd like**
Obscure Secreat Access Key from the New Profile Settings

**Describe alternatives you've considered**

**Additional context**

**Comment by awschristou** [comment]
This feature request has been available in Toolkits since version 1.21.0.0 (2021-04-21).
