### ISSUE TITLE
Installation Falied Windows Version: 21H2 AWS Toolkit for Visual Studio Version : 17

### ISSUE THREAD

**Issue by Monika1235** [aws/aws-toolkit-visual-studio#330]
**Computer (please complete the following information):**

- Windows Version: 21H2
- Visual Studio Version: 17

**Install log**

**Comment by rbbarad** [comment]
Hi @Monika1235, could you please attach the installation logs so we can help debug this further?

**Comment by saurabhajmera** [comment]
Closing this issue since we haven’t heard back from you in a while. If you are still encountering this problem please open a new issue with detailed steps to reproduce it.
