### ISSUE TITLE
Error during installation of Toolkit for VS 2022: "The file is not a valid VSIX package"

### ISSUE THREAD

**Issue by PetrusJKruger** [aws/aws-toolkit-visual-studio#334]
![image](https://user-images.githubusercontent.com/61282927/231726290-12fccd5b-fb14-407d-a030-474996d7dc03.png)

Please note that the latest download of version 1.40.0.0 gives the following error.

13 Apr 2023 11:59:08 - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionPackageException: The file is not a valid VSIX package. ---> System.IO.FileFormatException: File contains corrupted data.

**Comment by awschristou** [comment]
Hi @PetrusJKruger can you check if your download was corrupted? Try producing a sha384 hash of your file, for version 1.40.0.0 it should be:
- For VS 2022: `3B0711839D082EEB185BE3295EBA5B2DC049CDF707251A25ED7D344C1B65EB25774BE57B85457CB620C997DB684022F4`
- For VS 2019: `27C2A337F514478D4F5F3679387DFA8336E4C3A25797820574313823696315CAE1295890B285E73C892FEC0A238336A4`

If the hash value of your file does not match, you'll want to try downloading it again, either directly from the marketplace, or by using the extension manager within Visual Studio.
