### ISSUE TITLE
Publish to AWS: I could not deploy to an existing cloud app

### ISSUE THREAD

**Issue by danbergman** [aws/aws-toolkit-visual-studio#345]
In Publish to AWS, the Existing Targets list did not show my project. I expected to see it there.

My project is visible in the legacy version and publishes fine. I am using the same credentials and region as legacy.

Toolkit: 1.42.0.0
Visual Studio: 17.6.2

**Comment by rbbarad** [comment]
Hi @danbergman, can you please explain what type of project you are trying to publish? Is it .NET Framework, .NET Core, or .NET 5+, and what version? Is it an executable or a class library, etc -- what other details can you share about your project?

**Comment by danbergman** [comment]
Hi @rbbarad, thanks for getting back. Using Visual Studio 2022 17.6.2, this is a .NET 7 ASPNET Core application in US East (N. Virginia) region. Please let me know any other information that may be relevant and I can share.

**Comment by shruti0085** [comment]
Hi @danbergman, Can you describe the target you are publishing this to? For example - Is your application running on Windows Beanstalk images?

**Comment by danbergman** [comment]
Good news it appears to be resolved as it's showing the list of existing targets. For the record it'IIS 10 on 64 bit Windows Server 2019. Thanks for your help

**Comment by rbbarad** [comment]
Great to hear that the issue has been resolved! I will go ahead and close this issue. Please feel free to create a new issue if you run into this again.
