### ISSUE TITLE
Error when I deploy ASP.NET Core APP to AWS from VS2022

### ISSUE THREAD

**Issue by fullstact69** [aws/aws-toolkit-visual-studio#346]
C:\Program Files\dotnet\sdk\7.0.304\Microsoft.Common.CurrentVersion.targets(2977,5): error MSB4803: The task "ResolveComReference" is not supported on the .NET Core version of MSBuild. Please use the .NET Framework version of MSBuild. See https://aka.ms/msbuild/MSB4803 for further details.

How to resolve this issue?

**Comment by floralph** [comment]
Hello, this appears to be a general build error.  If this is related to the AWS Toolkit for Visual Studio, please provide more detail on what you were doing with the toolkit that lead to this error, solution details, and build output.

**Comment by fullstact69** [comment]
There is no error when I build it in vs2022. When I try to publish, it is showed.

**Comment by fullstact69** [comment]
When I select Legacy option, 
... dotnet publish: C:\Program Files\dotnet\sdk\7.0.306\Microsoft.Common.CurrentVersion.targets(2977,5): error MSB4803: The task "ResolveComReference" is not supported on the .NET Core version of MSBuild. Please use the .NET Framework version of MSBuild. See https://aka.ms/msbuild/MSB4803 for further details. [F:test.csproj]
Error executing "dotnet publish"
Error publishing application: Error executing "dotnet publish"

**Comment by floralph** [comment]
Do you see this error for all of your ASP.NET Core App (is this Web or API?) projects when you attempt to deploy?  If you create a new ASP.NET Core App of the same project type without making any changes, does the same error occur?

When you say "legacy option" are you referring to the "Publish to AWS Elastic Beanstalk (Legacy)..." context menu item or something else?
