### ISSUE TITLE
AWS explorer doesn't reflect the refreshed security token credentials via AWSCLI until I close and re-open the VS

### ISSUE THREAD

**Issue by AshokAndani** [aws/aws-toolkit-visual-studio#348]
Refreshed security token credentials via AWSCLI will not reflect in visual studio until I close and re-open the visual studio.

* security credentials are expired
1) refresh the security credentials from AWS cli command prompt
2) open AWS Explorer in VS2022
3) ERROR: The Security Token included in the request is Expired.
4) close and re-open the VS and then navigate to AWS Explorer
5) now it is able to retrieve the information of my account.....
![Screenshot 2023-07-17 084304](https://github.com/aws/aws-toolkit-visual-studio/assets/60642640/5f8da259-1ba4-4fc8-9af8-7f795aeea631)

**Comment by floralph** [comment]
Hi, thank you for bringing this issue to our attention.  Please provide details for this profile from your ~/.aws/config file (redact any confidential information if needed) and any pertinent messages in the toolkit logs.  To access the toolkit logs, click Extensions / AWS Toolkit / View Toolkit Logs.  If the issue just occurred, you will typically find it towards the end of the last log (filenames are timestamped) in the logs folder.

**Comment by AshokAndani** [comment]
as toolkit logs are having lot of confidential information traces hence cannot provide them
here is the config file:
![image](https://github.com/aws/aws-toolkit-visual-studio/assets/60642640/0652dcc9-04e6-4a92-823a-280aa529ef52)

**Comment by floralph** [comment]
Can you also redact and post the contents of the ~/.aws/credentials file that are pertinent to the profile in question?  The posted contents of the config file alone are insufficient to be used as a credential.  It's unclear how you have your credential that isn't working properly defined.

**Comment by AshokAndani** [comment]
here is the /credentials file details
![image](https://github.com/aws/aws-toolkit-visual-studio/assets/60642640/ce20ea96-7eac-4f94-af6b-25f25d2908cf)

but I would request to read the steps mentioned above again...
all the aws stuffs seems fine
I'm guessing Visual Studio is caching the creds hence it is not able to load the new refreshed creds after previous creds expiry until I close and re-open Visual Studio...

**Comment by shruti0085** [comment]
Hello @AshokAndani, a couple questions:
* Can you confirm if you are using the latest version of the toolkit 1.43.0.0?
* Instead of closing VS, what happens if you hit "Retry" (as seen in your screenshot) after you have refreshed session token using the CLI? Does switching between credentials selected lead to the same failed connection state?
