### ISSUE TITLE
After a new update, API Proxy Lambdas are just failing.

### ISSUE THREAD

**Issue by UmidMuzrapov** [aws/aws-toolkit-visual-studio#350]
**Describe the bug**
The application is developed in SAM. The lambda is accessed from API Gateway. After yesterday's update, all services fail.

**To Reproduce**
1. Choose a SAM application with lambda that accepts APIProxyResponse.
2. Try to debug it.

**Comment by shruti0085** [comment]
Hello @UmidMuzrapov, can you share the version of the toolkit you are on and the platform/OS?
