### ISSUE TITLE
Publish to AWS - Won't load within Visual Studio 2022

### ISSUE THREAD

**Issue by Reynolds80** [aws/aws-toolkit-visual-studio#352]
**Describe the bug**
Publish to AWS will not load within Visual Studio 2022, It still works in VS 2019.
If I click on Edit It says the connection is Valid.
After a while I get "Unable to start a deployment session"
and an error in Output of : 
Publish to AWS failed to load publish details using the current credentials:
I can still use the legacy "Publish to Elastic Beanstalk"

**To Reproduce**
Try and Publish To AWS by right clicking the project in Solution Explorer "

**Expected behavior**
To get Targets to publish to rather than an error.

**Screenshots**
NA

**Computer (please complete the following information):**

- Windows Version:  Win 10 Pro
- Visual Studio Version:  Problem with  2022 (17.6.5)
- AWS Toolkit for Visual Studio Version: 1.42

**Additional context**
Works using the legacy deployment, and has worked fine before. not sure how to correct.

I get this from the logs :

2023-08-01 13:56:26,074 [71] DEBUG Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Starting a deployment session
2023-08-01 13:58:06,435 [10] ERROR Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl - Error refreshing publish state
Amazon.AWSToolkit.Publish.SessionException: Unable to start a deployment session:
A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AWS.Deploy.ServerMode.Client.RestAPIClient.<StartDeploymentSessionAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<StartSessionAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<StartDeploymentSessionAsync>d__162.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<StartDeploymentSessionAsync>d__162.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<RestartDeploymentSessionAsync>d__160.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl.<RestartDeploymentSessionAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl.<OnTerminalConnectionManagerStateAsync>d__27.MoveNext()

**Comment by awschristou** [comment]
Thank you for reaching out. Something you could try is removing the underlying deployment tool, and letting the Toolkit re-download it:
- close all running instances of VS 2022
- delete the folder `%localappdata%\AWSToolkit\aws.deploy.tools\2022`
- restart VS 2022. The Toolkit will attempt to re-download the deployment tool.
- then try to deploy your project again

**Comment by Reynolds80** [comment]
Hi I tried this, and it downloaded, but just got the same progress bar for a few minutes and it failed with the same error.

**Comment by awschristou** [comment]
Thank you for following up. Would you be able to attach a larger portion of the Toolkit log from your most recent attempt? This might help to troubleshoot the problem.

**Comment by Reynolds80** [comment]
Hi here is the log from my attempt this morning.
[log_2023-08-02_08-13-40_18272.txt](https://github.com/aws/aws-toolkit-visual-studio/files/12237182/log_2023-08-02_08-13-40_18272.txt)
Thanks

**Comment by floralph** [comment]
There wasn't any additional detail in the log beyond what you posted above unfortunately.  Can I ask a few more questions to try to narrow down the issue here:

1. When you said that this has worked before fine, do you know if that was with the 1.42 version of the AWS Toolkit for Visual Studio that you're running now or a prior version?
2. Do you have any other solutions you deploy through Publish to AWS?  If so, do you have any issues with those or is this the only solution that presents the issue?
3. If you attempt to use the AWS dotnet deploy tool ([install instructions](https://github.com/aws/aws-dotnet-deploy#installing-the-tool)) to deploy the same solution, does it deploy successful or result in failure?

**Comment by Reynolds80** [comment]
Hi sorry for late reply I've been away.
1. I was using version 1.40 quite happily until the problems occurred.  I updated to version 1.42 just in case that was the issue, but the problem still persisted.
2. I used the legacy version (Publish to Elastic Beanstalk) this worked.
3. I will have a look at this tool, but believe that I can use the legacy (Elastic Beanstalk) method until this is sorted.
Cheers

**Comment by dhruv0127** [comment]
[Reynolds80](https://github.com/Reynolds80) I have the same problem did you find any solution?


![image](https://github.com/aws/aws-toolkit-visual-studio/assets/110829154/b234af72-a1cd-4e0d-8535-244b1d4b9fb9)


But i can able to upload from AWS legecy
 
![image](https://github.com/aws/aws-toolkit-visual-studio/assets/110829154/ba44891a-e41d-45c9-ad30-f663467ba7a7)

**Comment by Reynolds80** [comment]
After a few months of VS updates and just using the legacy method to update, I gave it another try and it just worked.  I have not tried on all of my projects, I just thought it had sorted itself out.  
As commented I updated to 1.42 then have just done VS updates ever since.  I wonder If a file gets out of sync somewhere along the line.  Cant be sure what the actual issue was though Sorry.

**Comment by floralph** [comment]
> [Reynolds80](https://github.com/Reynolds80) I have the same problem did you find any solution?
> 
> ![image](https://private-user-images.githubusercontent.com/110829154/289375627-b234af72-a1cd-4e0d-8535-244b1d4b9fb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjkwOTUsIm5iZiI6MTcwMjY2ODc5NSwicGF0aCI6Ii8xMTA4MjkxNTQvMjg5Mzc1NjI3LWIyMzRhZjcyLWExY2QtNGUwZC04NTM1LTI0NGIxZDRiOWZiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxOTMzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWJjNTYyZThhNDM5ZjEyYjQ3N2RiMWI3YjVkZjlkMGE4MDA3N2FjODE4NTVkMzcyYmViMGNmYWZiNTgxMDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uhNbxWt1nolkU1q034BY76WPdy9plfvo1ugheF8G044)
> 
> But i can able to upload from AWS legecy
> 
> ![image](https://private-user-images.githubusercontent.com/110829154/289375668-ba44891a-e41d-45c9-ad30-f663467ba7a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjkwOTUsIm5iZiI6MTcwMjY2ODc5NSwicGF0aCI6Ii8xMTA4MjkxNTQvMjg5Mzc1NjY4LWJhNDQ4OTFhLWU0MWQtNDVjOS1hZDMwLWY2NjM0NjdiYTdhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxOTMzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzIzYmQ3MDBiYjk2YjE5YjY1MmU3OTNlYjNjM2NlMGEzNDU1MjZlZWRiYjRjYmM3ZjMwMzBjMTlhNzJkN2Q3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uXDCW1njYMc77k6tbcTU0APHvUCo-v2bMroE7HmNfNY)

If you update to the latest version of the AWS Toolkit for Visual Studio, 1.46.0.0 as of this writing, do you encounter the same issue?

**Comment by floralph** [comment]
@dhruv0127 

If you update to the latest version of the AWS Toolkit for Visual Studio, 1.46.0.0 as of this writing, do you encounter the same issue?

**Comment by Reynolds80** [comment]
This is now happening again,  its very frustrating.  Did any of you get to the root cause of this issue.

**Comment by Reynolds80** [comment]
ok I think with the help of AWS support I got to the bottom of this (for me anyway)  I was missing some permissions from my Instance profile role (aws-elasticbeanstalk-ec2-role) associated with the EC2 instance.
AWSElasticBeanstalkWebTier
AWSElasticBeanstalkWorkerTier
AWSElasticBeanstalkMulticontainerDocker

Hope this assists someone else.

Cheers

**Comment by floralph** [comment]
That is great that you appear to have resolved the issue.  We are closing this issue now as it is resolved.  If you continue to experience issues, please re-open this issue and add new details or create a new issue.

**Comment by JasonParrNexteq** [comment]
I also had the same errors appear, but for me it was because I had renamed the "default"  AWS profile in the AWS explorer.
Changing the name back fixed the problem
