### ISSUE TITLE
Debug executable specified in the Mock Lambda Test Tool debug profile does not exist

### ISSUE THREAD

**Issue by mattibosAhead** [aws/aws-toolkit-visual-studio#353]
I found a problem while using the Preview version of the AWS Toolkit for Arm64 Visual Studio.

The Mock Lambda Test Tool option in the run/debugger dropdown does not currently function. There is an executable that is not being included with the installation of the AWS Toolkit that is needed to run the Mock Lambda Test Tool "dotnet-lambda-test-tool-6.0.exe" is the name of the file the debugger is looking for.

After installing AWS ToolKit for Visual Studio, I opened a new project "AWS Serverless Application with Tests (.NET Core - C#)"  and chose "ASP.NET Core Web API" as the blueprint. The project builds fine and runs locally, but when changing to the Mock Lambda Test Tool in the debugger dropdown, it cannot fine the above executable. I verified the file does not exist by following the file path. 

<img width="1044" alt="Screenshot 2023-08-02 at 4 59 33 PM" src="https://github.com/aws/aws-toolkit-visual-studio/assets/109746528/c25f26b1-7169-4f90-9d9a-b401ef3ce910">
<img width="1044" alt="Screenshot 2023-08-02 at 4 58 36 PM" src="https://github.com/aws/aws-toolkit-visual-studio/assets/109746528/846fa4dc-a8a8-4ec7-84dd-9f7eaf131898">
<img width="1044" alt="Screenshot 2023-08-02 at 4 58 18 PM" src="https://github.com/aws/aws-toolkit-visual-studio/assets/109746528/04ef52c7-4f03-40f3-886e-3bc1681b53ef">
<img width="1044" alt="Screenshot 2023-08-02 at 4 57 42 PM" src="https://github.com/aws/aws-toolkit-visual-studio/assets/109746528/2cea6da2-6fd9-4b2c-819a-49463e837936">

Toolkit: 1.42.0.0
Visual Studio: 17.4.3

**Comment by awschristou** [comment]
Hi @mattibosAhead , thanks for reaching out.
Would you be able to share the Toolkit log from your session in case it has some additional details? 

You can get to the logs from the "Extensions" menu, then "AWS Toolkit", "View Toolkit Logs". There is a log file per IDE session, so you'll want to find the one that related to when you took the screenshots above.

As a workaround, can you try running the following from a command line, to install the testing tool? This should allow you to debug using the Toolkit afterwards.
```
dotnet tool install amazon.lambda.testtool-6.0 -g
```

**Comment by mattibosAhead** [comment]
Yes absolutely. I'll include it with this comment.  

I tried running the commend manually, but it looks to be getting the same error that is in the logs. 

"C:\Users\matthew.ibos\AppData\Local\Temp\5068aece-6328-44ce-8d28-7dc101e4be0f\restore.csproj : error NU1301: Unable to
load the service index for source https://pkgs.dev.azure.com/iRecordModernization/a2e250b1-683b-4e5a-87e9-739178d5960f/
_packaging/wsi.libraries/nuget/v3/index.json.
The tool package could not be restored.
Tool 'amazon.lambda.testtool-6.0' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool"

[log_2023-08-02_16-59-07_12668.txt](https://github.com/aws/aws-toolkit-visual-studio/files/12251485/log_2023-08-02_16-59-07_12668.txt)

**Comment by awschristou** [comment]
It looks like your system doesn't know how to access the main NuGet repository. Can run `dotnet nuget list source` from the command line to see what NuGet sources you have configured? This is what mine looks like for example:
```
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

You'd want to have a nuget.org source added and enabled. Then, the Toolkit and the "dotnet tool install" command should be able to obtain the test tool.

**Comment by mattibosAhead** [comment]
Turns out I had a third party nuget package source that was blocking me. I removed it and was able to debug with the Mock Lambda Test Tool selected. I have the same two Registered Sources as you do now. Thank you for helping me sort this out!
