### ISSUE TITLE
AWS_DOTNET_DEPLOYTOOL_WORKSPACE were do we configure this parameter

### ISSUE THREAD

**Issue by esosam3** [aws/aws-toolkit-visual-studio#358]
I;m trying to deploy an app and I get this error:

could not be published as ASP.NET Core App to Amazon ECS using AWS Fargate: The USERPROFILE path (C:\Users\Test User) contains a whitespace character and cannot be used as a workspace by the deployment tool. Please refer to the troubleshooting guide for setting the AWS_DOTNET_DEPLOYTOOL_WORKSPACE that specifies an alternative workspace directory.

so I go over the documentation and yes it says create a workspace but how do I change the parameter, were ??, I have when over the Windows Env Vars and other possible paths, I have tried to change the Deploy process env vars when configuring the deploy process to something like this image: 

![image](https://github.com/aws/aws-toolkit-visual-studio/assets/134656058/639b0911-3877-43aa-b4e0-89b57971b00e)

but no luck, so were do you change it ? or any example on how to do it?, this is in windows 11.

**Comment by awschristou** [comment]
Hi @esosam3 , 

Under the hood, the Publish to AWS experience is using the [.NET Deploy tool](https://github.com/aws/aws-dotnet-deploy), which is a command line tool that performs the deployments. It sounds like you are referring to the guidance in https://aws.github.io/aws-dotnet-deploy/docs/getting-started/custom-workspace/ , which largely revolves around directly using the CLI.

In your scenario, try closing Visual Studio, and setting the environment variable in your Windows system. Once you've set the environment variable, launch Visual Studio, and try deploying your application again.

**Comment by esosam3** [comment]
This works, yes I was referring to the guide you mention, and yes doing that works perfectly, super thanks.

![image](https://github.com/aws/aws-toolkit-visual-studio/assets/134656058/fe158c7a-fb81-475e-a562-2890212fc568)
