### ISSUE TITLE
Elastic Beanstalk Deployment to EC2 Linux Container type

### ISSUE THREAD

**Issue by aws-savajja** [aws/aws-toolkit-visual-studio#36]
**Is your feature request related to a problem? Please describe.**
At the moment, i don't see an option to deploy to Linux based EC2 instance using the Visual Studio Deploy to Elastic Beanstalk option. 

**Describe the solution you'd like**
Can you add option to deploy to Linux based EC2 instances.

**Describe alternatives you've considered**
At the moment, hosting on ECS looks like a possible option.

**Additional context**

**Comment by awschristou** [comment]
Version 1.18.0.0 added support to deploy .NET Core applications to Linux based Beanstalk platforms
https://github.com/aws/aws-toolkit-visual-studio/blob/master/CHANGELOG.md#11800-2020-06-23
