### ISSUE TITLE
Aws

### ISSUE THREAD

**Issue by Shindemukund** [aws/aws-toolkit-visual-studio#360]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Computer (please complete the following information):**

- Windows Version:
- Visual Studio Version:
- AWS Toolkit for Visual Studio Version:

**Additional context**

**Comment by awschristou** [comment]
This issue appears to have been created in error. I will close it.

If you have an issue to report, please create a new issue and provide details.
