### ISSUE TITLE
Package not found during publish

### ISSUE THREAD

**Issue by webstrandsdev** [aws/aws-toolkit-visual-studio#361]
I recently updated my dev machine and now I am running Visual Studio and Windows 11.  Whenever I try to publish I keep getting the message that the package can not be found.  When I watch the temp location I don't see the zip file being created.  I am running Visual Studio as an Administrator.

I was able to setup my credentials and it sees my application environment, but the zip file is not created.  Not sure what I am doing wrong, any help would be appreciated.

This is what I see in the logs

Publishing 'http://dev.webstrands.design' to Amazon Web Services
...building deployment package 'C:\Users\tkemory\AppData\Local\Temp\AWSDeploymentArchive_http://dev.webstrands.design_v20230908205602.zip'
...invoking 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe -verb:sync -source:manifest="C:\Users\tkemory\AppData\Local\Temp\tmp633.tmp" -dest:package="C:\Users\tkemory\AppData\Local\Temp\AWSDeploymentArchive_http://dev.webstrands.design_v20230908205602.zip" -declareParam:name="IIS Web Application Name",kind="ProviderPath",scope="IisApp",match="^C:\\inetpub\\wwwroot\\Webstrands\.design",defaultValue="webstrands/",tags=IisApp -declareParam:name="IIS Web Application Name",kind="ProviderPath",scope="setAcl",match="^C:\\inetpub\\wwwroot\\Webstrands\.design",tags=IisApp', working folder 'C:\inetpub\wwwroot\Webstrands.design'
...error, package 'C:\Users\tkemory\AppData\Local\Temp\AWSDeploymentArchive_http://dev.webstrands.design_v20230908205602.zip' could not be found
..build fail, unable to find expected deployment package.
..build of project archive failed, abandoning deployment
Reloaded AWS Credential Profiles
Profiles found: 1

**Comment by awschristou** [comment]
Hi @webstrandsdev , it looks like the system is trying to produce an invalid filename. The path it appears to be using `C:\Users\tkemory\AppData\Local\Temp\AWSDeploymentArchive_http://dev.webstrands.design_v20230908205602.zip` contains "://" which is suspect.

Is there anything unusual about your project name/location? What steps are you taking to perform the publish?

**Comment by webstrandsdev** [comment]
Excellent catch, thanks so much.  I will change my project name.  Thank you @awschristou !
