### ISSUE TITLE
Publish to AWS: I could not deploy to an existing cloud app

### ISSUE THREAD

**Issue by soletteadm** [aws/aws-toolkit-visual-studio#365]
In Publish to AWS, the Existing Targets list did not show my project. I expected to see it there.

Toolkit: 1.43.0.0
Visual Studio: 17.7.3

**Comment by awschristou** [comment]
Hi @soletteadm , can you please provide details about the project you are trying to deploy, and what you were expecting to see as a deployment target in the Publish to AWS experience?
