### ISSUE TITLE
Error when creating node Lambda project through wizard.

### ISSUE THREAD

**Issue by whelen-cchevalier** [aws/aws-toolkit-visual-studio#37]
Recreation Steps:

1) New Project
2) Select AWS Lambda FUnction Project (Node.js)
3) Click Ok
4) Create a simple project (occurs when I create from existing project as well)
5) Finish

When I try to create a node.js lambda project I receive the following error:

`System.IO.FileLoadException: Could not load file or assembly 'ICSharpCode.SharpZipLib, Version 0.86.518... The located assembly's manifest definition does not match the assembly reference.`

![image](https://user-images.githubusercontent.com/48066691/65628069-b3731000-df9e-11e9-93eb-fa785fa194d8.png)

**Comment by whelen-cchevalier** [comment]
It will create a project, but it only has the readme and no sample code.

**Comment by awschristou** [comment]
Hi @whelen-cchevalier can you please share your version of Visual Studio and the AWS Toolkit you are using?

Also, can you please mention if you are trying to do this immediately after installing the toolkit, or if you have restarted Visual Studio since installing the AWS Toolkit?

**Comment by whelen-cchevalier** [comment]
AWS Toolkit for Visual Studio 2017 and 2019: 1.15.2.1

Visual Studio 2017: 15.9.16

I have restarted visual studio a few times trying to resolve the issue.
