### ISSUE TITLE
Publish to AWS: I could not deploy to Beanstalk targets using Amazon Linux 2023

### ISSUE THREAD

**Issue by palavikrishna** [aws/aws-toolkit-visual-studio#371]
In Publish to AWS, the Existing Targets list did not show my project. I expected to see it there.

Toolkit: 1.43.0.0
Visual Studio: 17.5.3

**Comment by awschristou** [comment]
Hi, can you please provide details about the project you are trying to deploy, and what you were expecting to see as a deployment target in the Publish to AWS experience?

**Comment by coanpape** [comment]
I encountered the same behavior and compared a working case to a non-working case. I noted that the non working case was using Linux 2023 as opposed to Linux 2... Linux 2023 environment is new default behavior, via the AWS create environment wizard. I tried creating a new environment using ".NET Core running on 64bit Amazon Linux 2/2.6.2" and that worked. I also tried creating an environment via the AWS toolkit and noted that the created environment was Linux 2, supporting my suspicion that this version of the AWS toolkit is not supporting Linux 2023.
AWS toolkit version: 1.43.0.0
Visual Studio: 17.7.7
Hope this helps somebody

**Comment by shruti0085** [comment]
Thanks @coanpape for bringing this issue to our attention.
I've created https://github.com/aws/aws-dotnet-deploy/issues/806 to track the feature request to add Amazon Linux 2023 beanstalk platform support. The AWS Toolkit for Visual Studio wraps the .NET Deployment Tool(which powers the Publish to AWS experience), so any changes to behavior here will have to originate in that repository.

We'll leave this issue open as well, and as improvements are made to the .NET Deploy tool, we will look at integrating them into the Publish to AWS experience, and update this issue.

**Comment by awschristou** [comment]
Version 1.49.0.0 of the Toolkit is now available. With this update, you can now deploy to Beanstalk targets that support .NET on Amazon Linux 2023.
