### ISSUE TITLE
Fail to install AWS Toolkit for Visual Studio 2017

### ISSUE THREAD

**Issue by FinleyInfoTechSys** [aws/aws-toolkit-visual-studio#372]
**Computer (please complete the following information):**

- Windows Version:  10
- Visual Studio Version: 2017
- AWS Toolkit for Visual Studio Version:  2017

**Install log**
10/31/2023 11:20:24 AM - Microsoft VSIX Installer
10/31/2023 11:20:24 AM - -------------------------------------------
10/31/2023 11:20:24 AM - vsixinstaller.exe version:
10/31/2023 11:20:24 AM - 17.5.4074+g1de9468fa7
10/31/2023 11:20:24 AM - -------------------------------------------
10/31/2023 11:20:24 AM - Command line parameters:
10/31/2023 11:20:24 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,/logfile:C:\users\mfinley\documents\awstool.log,C:\Users\mfinley\Downloads\awstoolkitPackage.vsix
10/31/2023 11:20:24 AM - -------------------------------------------
10/31/2023 11:20:24 AM - Microsoft VSIX Installer
10/31/2023 11:20:24 AM - -------------------------------------------
10/31/2023 11:20:25 AM - Initializing Install...
10/31/2023 11:20:25 AM - Extension Details...
10/31/2023 11:20:25 AM - 	Identifier         : 12ed248b-6d4a-47eb-be9e-8eabea0ff119
10/31/2023 11:20:25 AM - 	Name               : AWS Toolkit for Visual Studio 2017 and 2019
10/31/2023 11:20:25 AM - 	Author             : Amazon Web Services
10/31/2023 11:20:25 AM - 	Version            : 1.43.0.0
10/31/2023 11:20:25 AM - 	Description        : The AWS Toolkit for Visual Studio is an extension for Microsoft Visual Studio on Windows that makes it easier for developers to develop, debug, and deploy .NET applications using Amazon Web Services. With the AWS Toolkit for Visual Studio, you'll be able to get started faster...
10/31/2023 11:20:25 AM - 	Locale             : en-US
10/31/2023 11:20:25 AM - 	MoreInfoURL        : https://aws.amazon.com/visualstudio/
10/31/2023 11:20:25 AM - 	InstalledByMSI     : False
10/31/2023 11:20:25 AM - 	SupportedFrameworkVersionRange : [4.6,)
10/31/2023 11:20:28 AM - 	SignatureState     : ValidSignature
10/31/2023 11:20:28 AM - 	SignedBy           : Amazon Web Services, Inc.
10/31/2023 11:20:28 AM - 	Certificate Info   : 
10/31/2023 11:20:28 AM - 		-------------------------------------------------------
10/31/2023 11:20:28 AM - 		[Subject]       : CN="Amazon Web Services, Inc.", OU=AWS IDEs, O="Amazon Web Services, Inc.", L=Seattle, S=Washington, C=US, SERIALNUMBER=4152954, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.2=Delaware, OID.1.3.6.1.4.1.311.60.2.1.3=US
10/31/2023 11:20:28 AM - 		[Issuer]        : CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1, O="DigiCert, Inc.", C=US
10/31/2023 11:20:28 AM - 		[Serial Number] : 0B88817145BF1E6A3B03CCC272CE7D40
10/31/2023 11:20:28 AM - 		[Not Before]    : 7/30/2023 8:00:00 PM
10/31/2023 11:20:28 AM - 		[Not After]     : 7/30/2024 7:59:59 PM
10/31/2023 11:20:28 AM - 		[Thumbprint]    : 200433DEF52C553E7B4CFF3D3DDBE017B1322328
10/31/2023 11:20:28 AM - 	Supported Products : 
10/31/2023 11:20:28 AM - 		Microsoft.VisualStudio.Community
10/31/2023 11:20:28 AM - 			Version : [16.0,17.0)
10/31/2023 11:20:28 AM - 			ProductArchitecture : x86
10/31/2023 11:20:28 AM - 	References         : 
10/31/2023 11:20:28 AM - 	Prerequisites      : 
10/31/2023 11:20:28 AM - 		-------------------------------------------------------
10/31/2023 11:20:28 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
10/31/2023 11:20:28 AM - 		Name         : Visual Studio core editor
10/31/2023 11:20:28 AM - 		Version      : [16.0,17.0)
10/31/2023 11:20:28 AM - Signature Details...
10/31/2023 11:20:28 AM - 	Extension is signed with a valid signature.
10/31/2023 11:20:28 AM - Searching for applicable products...
10/31/2023 11:20:28 AM - Found installed product - Visual Studio Professional 2017
10/31/2023 11:20:28 AM - Found installed product - Global Location
10/31/2023 11:20:28 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)

**Any other information**I have a LICENCED version of Visual Studio 2017 and a valid credentials file at users/me/.aws/credential

**Comment by awschristou** [comment]
Hi @FinleyInfoTechSys , the latest versions of the AWS Toolkit are not available for Visual Studio 2017. At this time, they are available for Visual Studio 2019 and 2022. For more details, and possible options, please see https://github.com/aws/aws-toolkit-visual-studio/issues/221
