### ISSUE TITLE
Streamline SSO login process

### ISSUE THREAD

**Issue by aberus** [aws/aws-toolkit-visual-studio#377]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I need to extend a SSO session inside Visual Studio. Other AWS clients (AWS Toolkit for VS Code, AWS Toolkit for JetBrains, AWS Cli/boto) have a better experience.

**Describe the solution you'd like**

Make Login with AWS IAM Identity Center equivalent to other AWS Toolkits:
- [x] No need to manually copy the user code into the Authorization requested (use `VerificationUriComplete` instead of `VerificationUri`)
- [x] ~~Make OIDC client name nicer (no need to have a date in the name) https://github.com/aws/aws-toolkit-vscode/commit/2f126ec7a830e1eccf270adf74b3182d7d62d585~~
- [x] Use scope `sso:account:access` for a better reconnection experience [aws/aws-toolkit-jetbrains SonoConstants.kt](https://github.com/aws/aws-toolkit-jetbrains/blob/main/jetbrains-core/src/software/aws/toolkits/jetbrains/core/credentials/sono/SonoConstants.kt#L12)

**Comment by awschristou** [comment]
Thank you for sharing your experience and suggestions around the SSO experience.

We do have plans to update the login flow to avoid copying the user code, as you see in the other clients.

The OIDC client name is currently "decorated" by the AWS SDK for .NET, we will have to investigate opportunities for improving what you see in the login flow there.

The sso scope is something we've more recently realized is different between the Toolkits. We'll look into this as well.

**Comment by shruti0085** [comment]
Hello @aberus,

> No need to manually copy the user code into the Authorization requested (use VerificationUriComplete instead of VerificationUri)

We have released version 1.47.0.0 of the toolkit that addresses this issue. The AWS Builder Id and IAM Identity Center (SSO) login flow has been improved to confirm that the device code in the Toolkit and browser match.

**Comment by aberus** [comment]
Thank you for the login flow improvement!

**Comment by aberus** [comment]
Thank you so much for taking the time to streamlining SSO login process. 🥳 Closing this ticket.

<img width="542" alt="image" src="https://github.com/aws/aws-toolkit-visual-studio/assets/2404410/cc916e51-b197-4bea-ba02-9bd3b5f94cb5">
