### ISSUE TITLE
AWS Toolkit installation fails for Visual Studio 2022 Enterprise Edition

### ISSUE THREAD

**Issue by dasdebjit** [aws/aws-toolkit-visual-studio#378]
**Computer (please complete the following information):**

- Windows Version: Windows 10
- Visual Studio Version: Visual Studio 2022 Enterprise Edition
- AWS Toolkit for Visual Studio Version: v17

**Install log**
12/18/2023 2:37:04 PM - Microsoft VSIX Installer
12/18/2023 2:37:04 PM - -------------------------------------------
12/18/2023 2:37:04 PM - vsixinstaller.exe version:
12/18/2023 2:37:04 PM - 17.0.5226-preview5
12/18/2023 2:37:04 PM - -------------------------------------------
12/18/2023 2:37:04 PM - Command line parameters:
12/18/2023 2:37:04 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,D:\AWSToolkitPackage.v17.vsix
12/18/2023 2:37:04 PM - -------------------------------------------
12/18/2023 2:37:04 PM - Microsoft VSIX Installer
12/18/2023 2:37:04 PM - -------------------------------------------
12/18/2023 2:37:04 PM - Initializing Install...
12/18/2023 2:37:05 PM - Extension Details...
12/18/2023 2:37:05 PM - 	Identifier         : 0B82CB16-0E52-4363-9BC0-61E758689176
12/18/2023 2:37:05 PM - 	Name               : AWS Toolkit for Visual Studio 2022
12/18/2023 2:37:05 PM - 	Author             : Amazon Web Services
12/18/2023 2:37:05 PM - 	Version            : 1.46.0.0
12/18/2023 2:37:05 PM - 	Description        : The AWS Toolkit for Visual Studio is an extension for Microsoft Visual Studio on Windows that makes it easier for developers to develop, debug, and deploy .NET applications using Amazon Web Services.
12/18/2023 2:37:05 PM - 	Locale             : en-US
12/18/2023 2:37:05 PM - 	MoreInfoURL        : https://aws.amazon.com/visualstudio/
12/18/2023 2:37:05 PM - 	InstalledByMSI     : False
12/18/2023 2:37:05 PM - 	SupportedFrameworkVersionRange : [4.5,)
12/18/2023 2:37:05 PM - 
12/18/2023 2:37:07 PM - 	SignatureState     : ValidSignature
12/18/2023 2:37:07 PM - 	SignedBy           : Amazon Web Services, Inc.
12/18/2023 2:37:07 PM - 	Certificate Info   : 
12/18/2023 2:37:07 PM - 		-------------------------------------------------------
12/18/2023 2:37:07 PM - 		[Subject]       : CN="Amazon Web Services, Inc.", OU=AWS IDEs, O="Amazon Web Services, Inc.", L=Seattle, S=Washington, C=US, SERIALNUMBER=4152954, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.2=Delaware, OID.1.3.6.1.4.1.311.60.2.1.3=US
12/18/2023 2:37:07 PM - 		[Issuer]        : CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1, O="DigiCert, Inc.", C=US
12/18/2023 2:37:07 PM - 		[Serial Number] : 0279F5F9911BB19A7BBA37FFFFE6175A
12/18/2023 2:37:07 PM - 		[Not Before]    : 7/31/2023 5:30:00 AM
12/18/2023 2:37:07 PM - 		[Not After]     : 7/31/2024 5:29:59 AM
12/18/2023 2:37:07 PM - 		[Thumbprint]    : 57F85A48C0884E1B46F7D0CD6E069DB4C699C017
12/18/2023 2:37:07 PM - 
12/18/2023 2:37:07 PM - 	Supported Products : 
12/18/2023 2:37:07 PM - 		Microsoft.VisualStudio.Community
12/18/2023 2:37:07 PM - 			Version : [17.7,18.0)
12/18/2023 2:37:07 PM - 			ProductArchitecture : amd64
12/18/2023 2:37:07 PM - 		Microsoft.VisualStudio.Community
12/18/2023 2:37:07 PM - 			Version : [17.7,18.0)
12/18/2023 2:37:07 PM - 			ProductArchitecture : x86
12/18/2023 2:37:07 PM - 
12/18/2023 2:37:07 PM - 	References         : 
12/18/2023 2:37:07 PM - 	Prerequisites      : 
12/18/2023 2:37:07 PM - 		-------------------------------------------------------
12/18/2023 2:37:07 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
12/18/2023 2:37:07 PM - 		Name         : Visual Studio core editor
12/18/2023 2:37:07 PM - 		Version      : [17.7,18.0)
12/18/2023 2:37:07 PM - 
12/18/2023 2:37:07 PM - Signature Details...
12/18/2023 2:37:07 PM - 	Extension is signed with a valid signature.
12/18/2023 2:37:07 PM - 
12/18/2023 2:37:07 PM - Searching for applicable products...
12/18/2023 2:37:07 PM - Found installed product - Global Location
12/18/2023 2:37:07 PM - Found installed product - Visual Studio Enterprise 2022
12/18/2023 2:37:07 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Any other information**
Visual Studio 2022 Enterprise is installed bot the installer reports "No compatible with any installed products"

**Comment by shruti0085** [comment]
Hello,
AWS Toolkit for Visual Studio 2022 requires a minimum Visual Studio 2022 version of 17.7 as per [this announcement](https://github.com/aws/aws-toolkit-visual-studio/issues/375) 
Can you confirm if your enterprise version is equal to or higher than 17.7?

**Comment by mlcl-chenglien-oh** [comment]
I am having installing AWS Toolkit on Visual Studio 2022 Enterprise Version 17.9.2
Error:
One or more extensions could not be installed because the following errors occurred: AWS Toolkit Visual Studio 2022: The underlying connection was closed: An unexpected error occurred on a send.
