### ISSUE TITLE
Source Code controllet Frameworks process by the Secret Socket *

### ISSUE THREAD

**Issue by Astrabacus** [aws/aws-toolkit-visual-studio#379]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Toolkit Logs**

**Development System (please complete the following information):**
- Windows Version:
- Visual Studio Version:
- AWS Toolkit for Visual Studio Version:

**Additional context**

**Comment by awschristou** [comment]
Hi, I am unable to assist with this issue as-is. If you are able to share more details about your problem, please re-open it and provide a full description of your experience.
