### ISSUE TITLE
Can't publish Lambda/ECS etc to me-south-1 region

### ISSUE THREAD

**Issue by Noplace** [aws/aws-toolkit-visual-studio#38]
It seems the URL maintained in AWS toolkit for Middle East region IAM is wrong

when inspecting it shows its trying to connect to iam.me-south-1.amazonaws.com which I believe should be iam.amazonaws.com

![image](https://user-images.githubusercontent.com/680892/65874505-82278500-e38e-11e9-9698-19732a596c64.png)

**Comment by awschristou** [comment]
When you deploy a lambda function, the second dialog has a dropdown that lets you select a role for the Lambda that you are deploying. The Toolkit is not correctly retrieving IAM roles for this dropdown.

I will take a look at this.

**Comment by Noplace** [comment]
Hi, any update please? we are looking forward to start utilizing our region in AWS properly

**Comment by awschristou** [comment]
Hi @Noplace , the toolkit version 1.16.0.0 is now out with this fix. Please try it out.

**Comment by Noplace** [comment]
confirmed working with 1.16.0.0
