### ISSUE TITLE
Unable to install AWSToolkitPackage.v17

### ISSUE THREAD

**Issue by gmsilvey** [aws/aws-toolkit-visual-studio#380]
**Computer (please complete the following information):**

- Windows Version: 10 Version 22H2
- Visual Studio Version: Microsoft Visual Studio Professional 2022 (64-bit) - Current
- AWS Toolkit for Visual Studio Version: Trying to install AWSToolkitPackage.v17.vsix
- 
[dd_VSIXInstaller_20240112100825_3898.log](https://github.com/aws/aws-toolkit-visual-studio/files/13922638/dd_VSIXInstaller_20240112100825_3898.log)
[dd_VSIXInstaller_20240112100825_3898.log](https://github.com/aws/aws-toolkit-visual-studio/files/13922650/dd_VSIXInstaller_20240112100825_3898.log)

**Install log**

**Comment by awschristou** [comment]
Hi @gmsilvey , it sounds like you are running a version of Visual Studio 2022 that is lower than 17.7. You will need to update your instance of Visual Studio to the latest version, and you will then be able to install the Toolkit.

See https://github.com/aws/aws-toolkit-visual-studio/issues/375 for details.

**Comment by shruti0085** [comment]
Hello @gmsilvey,
Closing this since it sounds like you were able to resolve the issue by upgrading your installation. If it did not resolve your issue, please feel free to reopen this and add relevant details that would help us dig further.
