### ISSUE TITLE
Publish to AWS: I could not deploy to an existing cloud app

### ISSUE THREAD

**Issue by PurushotamSharma** [aws/aws-toolkit-visual-studio#388]
In Publish to AWS, the Existing Targets list did not show my project. I expected to see it there.

Toolkit: 1.46.0.0
Visual Studio: 17.8.5

**Comment by awschristou** [comment]
Hi @PurushotamSharma , this issue does not contain specific details about your issue, so I will close it.

From the issue template: 

>Explain why your project should have been listed. Please include any project details and how you previously deployed it.

If you are able to explain your issue, please re-open the issue and add more details.
