### ISSUE TITLE
Unable to use deployment buckets due to region error

### ISSUE THREAD

**Issue by jesshannon** [aws/aws-toolkit-visual-studio#390]
**Describe the bug**
When deploying an update to an existing Lambda app, I've selected the existing Stack Name and S3 bucket. Under the bucket selector I get the error: Bucket is not in the same region EU as currently selected region eu-west-1

The bucket is definitely in eu-west-1, all of our buckets are.

On another machine I have version 1.24.0.0 of the AWS Toolkit installed and this works fine deploying the same update to the same bucket.

**Expected behavior**
I expected it to allow a deployment

**Screenshots**

![image](https://github.com/aws/aws-toolkit-visual-studio/assets/673246/526d1f1e-474d-49b3-9c4d-b919c5d2b824)

**Toolkit Logs**

Nothing is logged when this error shows

**Development System (please complete the following information):**
- Windows Version: Win 11 Pro
- Visual Studio Version: VS 2022 ARM64 Version 17.8.5
- AWS Toolkit for Visual Studio Version: 1.46.0.0

**Additional context**

**Comment by rbbarad** [comment]
@jesshannon Thanks for bringing this issue to our attention. I was able to reproduce this issue and am investigating further

**Comment by rbbarad** [comment]
A fix for this issue has been released with version 1.47.0.0 of the Toolkit!
