### ISSUE TITLE
Failed to publish to AWS

### ISSUE THREAD

**Issue by zilla-hue** [aws/aws-toolkit-visual-studio#401]
I keep getting this error when i try to Publish my .NET app on AWS. ```CSC : error CS2001: Source file 'C:\Users\Tek\source\repos\OniInvestmentDrive\OniInvestmentDrive\obj\Debug\net6.0\OniInvestmentDrive.MvcApplicationPartsAssemblyInfo.cs' could not be found. [C:\Users\Tek\source\repos\OniInvestmentDrive\OniInvestmentDrive\OniInvestmentDrive.csproj]```

**Comment by rbbarad** [comment]
Hi @zilla-hue, thanks for bringing this issue to our attention. 

I'd like to understand a bit more about your project/publish configuration to help investigate this issue further:

- Is there anything unusual about your project name/location? 
- What steps are you taking to perform the publish? 
- Where are you attempting to publish this app to (Elastic Beanstalk, Fargate, etc.)? 
- What version of the Toolkit are you on? 
- Would you mind sharing your [Toolkit Logs](https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/general-troubleshoot.html#general-troubleshoot-procedure-logs) - this may provide additional details on this error to help us troubleshoot
