### ISSUE TITLE
Missing requirements:  Node.js

### ISSUE THREAD

**Issue by rmasonjr** [aws/aws-toolkit-visual-studio#409]
![image](https://github.com/aws/aws-toolkit-visual-studio/assets/11462627/f8320fda-59ac-4e35-8825-ff535137871a)

I'm getting a message that Node.js needs to be installed.  I installed Node.js and restarted the IDE and I still get the message.

VS Professional 2022 17.9.4
Node.js v20.11.1
AWS Toolkit for Visual Studio 2022 v1.49.0.0

**Comment by 96malhar** [comment]
We shell out to the Node CLI by invoking `node --version` and check it's output to verify whether the minimum version of Node is installed or not - https://github.com/aws/aws-dotnet-deploy/blob/741dff6bc2ae1aa63a26bc6a9bc35e62bcce18eb/src/AWS.Deploy.Orchestration/SystemCapabilityEvaluator.cs#L75

@rmasonjr Can you paste the output of `node --version` from you terminal. That will help us narrow down the issue.

**Comment by rbbarad** [comment]
@rmasonjr Glad to hear its working for you! Closing this issue
