### ISSUE TITLE
Allow to publish to AWS Lambda using different aws-lambda-tools-??.json files from same project

### ISSUE THREAD

**Issue by johnwc** [aws/aws-toolkit-visual-studio#41]
Within a single VS AWS Lambda project, we can have several different function classes and handlers. We need the ability to have a way to publish each function within the project. I'd think having the ability to right click on the aws-lambda-tools-??.json files to choose what settings to publish with would work. We then would create individual files for each handler in the project.

**Comment by awschristou** [comment]
We recommend using deployment tooling that is also compatible with CI/CD systems for working with different environments. Please see #250 for more details.

**Comment by johnwc** [comment]
This was three years ago... way before you guys had any way of using it in CI/CD.
