### ISSUE TITLE
vs 2022 Running Suggestions：Recommendation failure: NetworkingError: unable to verify the first certificate

### ISSUE THREAD

**Issue by Z-kawa** [aws/aws-toolkit-visual-studio#410]
runtime error：Recommendation failure: NetworkingError: unable to verify the first certificate
When prompted while using "Generate Code Suggestions," how should this be resolved?

**Comment by awschristou** [comment]
Please have a look at #403 and see if your issue is a duplicate. You may need to look through your logs and share additional details.

**Comment by Z-kawa** [comment]
Thank you for your answer. I suspect it was a network issue, because it is working normally now without any changes made.
