### ISSUE TITLE
NodeJS 20.x Template

### ISSUE THREAD

**Issue by cacowen** [aws/aws-toolkit-visual-studio#412]
I was expecting a template for a NodeJS 20.x lambda, but all I see are .Net runtime options. I have Node installed, but am I missing anything else?

**Comment by awschristou** [comment]
Hi @cacowen , with the most recent version of the Toolkit (1.50.0.0), we have removed support for deploying Node related Lambda functions from the AWS Toolkit for Visual Studio (and the accompanying project templates). This is mentioned in the [changelog](https://github.com/aws/aws-toolkit-visual-studio/blob/main/CHANGELOG.md#15000-2024-03-28), and has been discussed in https://github.com/aws/aws-toolkit-visual-studio/issues/286.

Please see https://github.com/aws/aws-toolkit-visual-studio/issues/286#issuecomment-2030555106 for AWS Toolkits in other IDEs that can help you develop NodeJS based lambda functions.
