### ISSUE TITLE
Publish to AWS: I could not deploy to an existing cloud app

### ISSUE THREAD

**Issue by PubliDesk** [aws/aws-toolkit-visual-studio#416]
In Publish to AWS, the Existing Targets list did not show my project. I expected to see it there.

Toolkit: 1.42.0.0
Visual Studio: 17.9.6

**Comment by awschristou** [comment]
Hi, can you please provide details about the project you are trying to deploy, and what you were expecting to see as a deployment target in the Publish to AWS experience?

It looks like you are using an older version of the Toolkit as well. You may want to update to the latest version, to see if that supports your project.
