### ISSUE TITLE
No option to create an AWS Lambda Node.js project on Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.10.1

### ISSUE THREAD

**Issue by MLNR** [aws/aws-toolkit-visual-studio#426]
**Describe the bug**

Missing the feature to create AWS Lambda **Node.js** project on **Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.10.1** and **Microsoft Visual Studio Professional 2022 (64-bit) - Preview
Version 17.11.0 Preview 1.1**

**To Reproduce**

Go to **File/New/Project**
Select Languages-**JavaScript**
Select Platforms-**AWS**

**Expected behavior**

There should be an option to create **AWS Lambda Function Project (Node.js)** 

**Screenshots**

![VS2022](https://github.com/aws/aws-toolkit-visual-studio/assets/20323551/9ff55b2d-0b3e-40df-94e6-2fcd34e5c077)

**Toolkit Logs**

[log_2024-06-09_01-15-43_844.txt](https://github.com/user-attachments/files/15767214/log_2024-06-09_01-15-43_844.txt)

**Development System (please complete the following information):**
- Windows Version:  Windows Server 2022 Datacenter 21H2 20348.2402
- Visual Studio Version: 17.10.1
- AWS Toolkit for Visual Studio Version: 2022 1.53.0.0

**Additional context**

**Comment by awschristou** [comment]
Hi @MLNR , starting with version 1.50.0.0 of the Toolkit, we have removed support for deploying Node related Lambda functions from the AWS Toolkit for Visual Studio (and the accompanying project templates). This is mentioned in the [changelog](https://github.com/aws/aws-toolkit-visual-studio/blob/main/CHANGELOG.md#15000-2024-03-28), and has been discussed in https://github.com/aws/aws-toolkit-visual-studio/issues/286.

Please see https://github.com/aws/aws-toolkit-visual-studio/issues/286#issuecomment-2030555106 for AWS Toolkits in other IDEs that can help you develop NodeJS based lambda functions.
