### ISSUE TITLE
Publish to Existing Target - can't modify

### ISSUE THREAD

**Issue by rmasonjr** [aws/aws-toolkit-visual-studio#428]
Publish to Existing Target is referencing an Environment Name that doesnt exist anymore:

![image](https://github.com/aws/aws-toolkit-visual-studio/assets/11462627/4eaaeb35-4fce-466e-8f72-e1bd45a8b945)

When I click on Edit Settings, everything is grayed-out and I cant change the environment name:

![image](https://github.com/aws/aws-toolkit-visual-studio/assets/11462627/c2d17890-3513-40f0-b5da-51de0a84e637)

How can I just remove the target and start over?

**Comment by awschristou** [comment]
Hi @rmasonjr , this existing deployment target represents a previous deployment, which is performed through CloudFormation. If you want to remove this Beanstalk environment from your account, you can look through your CloudFormation stacks to find the deployment associated with this Beanstalk environment, and tear down the stack. Keep in mind this will remove any other resources associated with that deployment stack.

**Comment by rmasonjr** [comment]
ah - thanks - I was so focused on the environment I didnt consider CloudFormation.
That worked!
