### ISSUE TITLE
Why is "Create new Elastic Beanstalk application" grayed-out?

### ISSUE THREAD

**Issue by rmasonjr** [aws/aws-toolkit-visual-studio#429]
Under "Publish to Existing Target" it wants to Create a new Elastic Beanstalk application.  
I dont want a new one, I want to just deploy over the existing one, so I hit "Edit Settings"

![image](https://github.com/aws/aws-toolkit-visual-studio/assets/11462627/9d99a7d7-2998-4822-ad75-607ce4ae41ea)

Why is the checkbox grayed-out so I can edit the settings?

![image](https://github.com/aws/aws-toolkit-visual-studio/assets/11462627/83050948-6f65-40a8-a151-e83218814aa6)

**Comment by ScottDellinger** [comment]
@rmasonjr I'm guessing because you are on the Publish to Existing Target tab and are looking at the settings for an existing system. That option becomes available for new apps.

**Comment by rmasonjr** [comment]
Well, when I tried to publish to new target, it says the application name is already in use:

![image](https://github.com/aws/aws-toolkit-visual-studio/assets/11462627/85679603-35de-4871-a982-714526925ab9)

So how do I deploy an existing app to an existing target?
Why would I want to create a new application each time I deploy?  I literally want to update the existing app.

**Comment by ScottDellinger** [comment]
The interface may be confusing, I guess. If you want to publish to the
existing app, that's the one you select and it will publish to the existing
app.

**Comment by rmasonjr** [comment]
Thanks - I started completely over and was eventually able to create a target that allows me to redeploy my app.

**Comment by awschristou** [comment]
Hi @rmasonjr , thank you for reaching out. I can see how this would be confusing. If you deploy to the existing target, it will deploy to that existing Beanstalk Application. The configuration just happens to have the text "Create new ...". I've [filed a ticket with the deploy tool](https://github.com/aws/aws-dotnet-deploy/issues/834) that powers the Publish to AWS experience, to see if this can be improved.
