### ISSUE TITLE
visual studio delpoyment problem

### ISSUE THREAD

**Issue by proper77** [aws/aws-toolkit-visual-studio#430]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Toolkit Logs**

**Development System (please complete the following information):**
- Windows Version:
- Visual Studio Version:
- AWS Toolkit for Visual Studio Version:

**Additional context**

**Comment by shruti0085** [comment]
Hello, can you please share some details about the issue you are facing? Any logs would be helpful to troubleshoot this further.

**Comment by proper77** [comment]
![image](https://github.com/aws/aws-toolkit-visual-studio/assets/116689306/88e5dae9-7a33-4635-b8d6-db833e2ffb82)

**Comment by shruti0085** [comment]
Hi @proper77, can you please share your toolkit log from the session where you saw this issue? You can get to your logs by navigating to the Extensions / AWS Toolkit / View Toolkit Logs menu.
