### ISSUE TITLE
How to view stack without publishing first?

### ISSUE THREAD

**Issue by Soundman32** [aws/aws-toolkit-visual-studio#437]
When a Publish to AWS is completed, there is a link on the form to open the stack (under CloudFormation Stack).

It appears the only way to access the stack page is AFTER publishing.  If I want to view the stack, I have to keep the publish window open.

_Is there a way to view the stack without publishing first?_

(obviously I mean after the stack has been created, how can I re-view the stack).

**Comment by awschristou** [comment]
Hi @Soundman32 , you can look at the active CloudFormation stacks in your account (and region) by using the AWS Explorer. From the View menu in Visual Studio, look for "AWS Explorer". This will open up a ToolWindow where you can explore some of your account's resources, including CloudFormation Stacks. 

Here's mine as an example
![image](https://github.com/aws/aws-toolkit-visual-studio/assets/39839589/5a7a9a45-c281-4296-8848-730b8c288ae2)

**Comment by Soundman32** [comment]
Thanks.  Never looked there.
