### ISSUE TITLE
Publishing to Elastic Beanstalk fails for region me-south-1

### ISSUE THREAD

**Issue by Noplace** [aws/aws-toolkit-visual-studio#44]
**Describe the bug**
we are trying to deploy apps through the publish to Elastic wizard and when we try it with me-south1 , it fails due to Applications Roles not loading, i have traced the issue to be when the wizard tries to fetch roles while in 'me-south-1' it accesses wrong iam url which iam.me-south-1.amazonaws.com instead of proper iam.amazonaws.com

**To Reproduce**
1. Open any .NET Web project
2. Right click and select 'Publish to AWS Elastic Beanstalk'
3. Select region 'Middle East (Bahrain)'
4. On Permissions page Deployed Application  Permissions will fail to load and you can't select any role.
5. The publish can still continue and succeeds but fails and terminates once you view in console, due to same reason

- Windows Version: Windows 10 (latest as of today)
- Visual Studio Version: 2019
- AWS Toolkit for Visual Studio Version: 1.15.2.1

**Comment by awschristou** [comment]
Hi, this is a duplicate of #38. I'm going to close this issue, but this has good commentary to complement the other issue.

**Comment by awschristou** [comment]
My apologies... it is not a duplicate issue, but is affected by the same root cause.

**Comment by Noplace** [comment]
no worries, looking forward to the next release =)

**Comment by awschristou** [comment]
Hi @Noplace , the toolkit version 1.16.0.0 is now out. Can you please try it and report if this now works for you?

**Comment by Noplace** [comment]
confirmed working, many thanks!
