### ISSUE TITLE
Error occurred while attempting to determine if WebView2 runtime is installed

### ISSUE THREAD

**Issue by leigh-pointer** [aws/aws-toolkit-visual-studio#445]
**Describe the bug**
Being told to restart Visual Stuidio after trying ot activate Refactor.

**To Reproduce**
Select code, right click select Amazon Q-> Refactor

**Expected behavior**
Amazon to refactor the code

**Toolkit Logs**
Launching Amazon Q Language Server v2.0.0 from local cache location: C:\Users\leigh\AppData\Local\aws\toolkits\language-servers\AmazonQ\2.0.0 (Attribution notice for aws-lsp-codewhisperer can be found at: https://aws-language-servers.us-east-1.amazonaws.com/a8dafbc7-b928-4ca5-82b4-c261f51dd39f/THIRD_PARTY_LICENSES)
Activating: Amazon Q Language Client
Initialized: Amazon Q Language Client
Reconnected to Amazon Q with AWS Builder ID
Error occurred while attempting to determine if WebView2 runtime is installed. Error: Unable to find an entry point named '?' in DLL 'WebView2Loader.dll'.
Loading Amazon Q Chat UI: C:\Users\leigh\AppData\Local\aws\toolkits\language-servers\AmazonQ\2.0.0\clients\amazonq-ui.js

**Development System (please complete the following information):**
- Windows Version: 11
- Visual Studio Version: 2022
- AWS Toolkit for Visual Studio Version:  Language Server v2.0.0

**Comment by farisab1** [comment]
Hi @leigh-pointer, thank you for bringing this issue to our attention. Are you able to access Amazon Q chat after restarting Visual Studio?

**Comment by farisab1** [comment]
Also could you share the following:
- ActivityLog.xml for the following error
- Your devices OS architecture (x32/x64)

Thank you!

**Comment by leigh-pointer** [comment]
Where can i locate this file ActivityLog.xml
Windows 11, x64 
Microsoft Visual Studio Community 2022 (64-bit) Version 17.10.4

**Comment by leigh-pointer** [comment]
AWS Toolkit for Visual Studio
Toolkit Version: 1.54.0.1
Visual Studio: VS Community 2022, Version: 17.10.4


Initializing: Amazon Q Language Client
Launching Amazon Q Language Server v2.0.0 from local cache location: C:\Users\leigh\AppData\Local\aws\toolkits\language-servers\AmazonQ\2.0.0 (Attribution notice for aws-lsp-codewhisperer can be found at: https://aws-language-servers.us-east-1.amazonaws.com/a8dafbc7-b928-4ca5-82b4-c261f51dd39f/THIRD_PARTY_LICENSES)
Activating: Amazon Q Language Client
Initialized: Amazon Q Language Client
Reconnected to Amazon Q with AWS Builder ID
AWS Toolkit was unable to get Amazon Q suggestions: Value cannot be null.
Parameter name: uriString
Error occurred while attempting to determine if WebView2 runtime is installed. Error: Unable to find an entry point named '?' in DLL 'WebView2Loader.dll'.
Loading Amazon Q Chat UI: C:\Users\leigh\AppData\Local\aws\toolkits\language-servers\AmazonQ\2.0.0\clients\amazonq-ui.js

**Comment by farisab1** [comment]
Thanks for getting back to me @leigh-pointer , you can find the ActivityLog.xml from the following path `C:\Users\{Username}\AppData\Roaming\Microsoft\VisualStudio\17.09_...`. From there you should be able to open the ActivityLog.xml file in any web browser.

Does restarting Visual Studio resolve the error or is it consistently occuring?

**Comment by leigh-pointer** [comment]
After restarting the problem unfortunately still exists.

**Comment by farisab1** [comment]
Sorry to hear that the problem still occurs after restart. We just released a new version of the toolkie (1.55.0). Could you update your extension to this version and share the logs when this error comes up?

You can get to the toolkit logs by going to Extensions -> AWS Toolkit -> View Toolkit Logs from within Visual Studio. From the directory of logs the most recent file should be the corresponding log.

Thank you!

**Comment by leigh-pointer** [comment]
New Version has fixed the issue I was having and I am loving it.  Thank you very much. You can close this issue.
