### ISSUE TITLE
Unable to find an entry point named '?' in DLL 'WebView2Loader.dll'

### ISSUE THREAD

**Issue by hmadrigal** [aws/aws-toolkit-visual-studio#450]
**Describe the bug**
Since I have installed the product AWS Q in my Visual Studio Community, it has never loaded the Chat feature. It shows an error which says _Error loading chat. Restart Visual Studio or review logs in Amazon Web Services output window for troubleshooting_

Base on the message, here is the log info (before restarting):

```log

Initializing: Amazon Q Language Client
Launching Amazon Q Language Server v2.0.0 from local cache location: C:\Users\johndoe\AppData\Local\aws\toolkits\language-servers\AmazonQ\2.0.0 (Attribution notice for aws-lsp-codewhisperer can be found at: https://aws-language-servers.us-east-1.amazonaws.com/a8dafbc7-b928-4ca5-82b4-c261f51dd39f/THIRD_PARTY_LICENSES)
Activating: Amazon Q Language Client
Initialized: Amazon Q Language Client
Reconnected to Amazon Q with awsBuilderId:amazonQ
Error occurred while attempting to determine if WebView2 runtime is installed. Error: Unable to find an entry point named '?' in DLL 'WebView2Loader.dll'.
Loading Amazon Q Chat UI: C:\Users\hfmad\AppData\Local\aws\toolkits\language-servers\AmazonQ\2.0.0\clients\amazonq-ui.js

```

**To Reproduce**
I do not have any specific steps to reproduce

**Expected behavior**
It should load the chat and allow interaction

**Screenshots**

**Toolkit Logs**

[log_2024-07-14_22-17-54_16692.txt](https://github.com/user-attachments/files/16234692/log_2024-07-14_22-17-54_16692.txt)

**Development System (please complete the following information):**
- Windows Version:  Microsoft Windows Version 23H2 (OS Build 22631.3880)
- Visual Studio Version: Microsoft Visual Studio Community 2022 (64-bit) Version 17.10.4
- AWS Toolkit for Visual Studio Version: AWS Toolkit with Amazon Q 1.54.0.1

**Additional context**

**Comment by awschristou** [comment]
Hi @hmadrigal , thank you for reaching out.

It sound like you were using version 1.54.0.1 of the extension. Can you please update to the latest version of the extension and try again? If it fails, please attach that log. It contains additional details that may help us in understanding when this problem occurs.

**Comment by hmadrigal** [comment]
@awschristou Thank you for the quick response. It loaded well after I ran the update.
