### ISSUE TITLE
AWS Toolkit is not in the Installed list in Visual Studio Extension Manager

### ISSUE THREAD

**Issue by jocere** [aws/aws-toolkit-visual-studio#456]
[log_2024-08-01_11-59-14_9460.txt](https://github.com/user-attachments/files/16458588/log_2024-08-01_11-59-14_9460.txt)

**Describe the bug**

AWS Toolkit is not in Installed list in Visual Studio Extension Manager so the installation cannot be managed (can't uninstall)

**To Reproduce**

AWS Toolkit still shows up in the Browse menu and has an Install button, but gives an error when it tries to install.

**Expected behavior**

AWS Toolkit should be in the Installed list so the installation can be managed

**Screenshots**

**Toolkit Logs**

**Development System (please complete the following information):**
- Windows Version: 11 Version 10.0.22631 Build 22631
- Visual Studio Version: Microsoft Visual Studio Enterprise 2022 (64-bit) - Current Version 17.10.5
- AWS Toolkit for Visual Studio Version: Toolkit Version: 1.55.2.0

**Additional context**

**Comment by shruti0085** [comment]
Hi @jocere ,
From an instance of Visual Studio where you are encountering this problem, does https://github.com/aws/aws-toolkit-visual-studio/issues/452 match the description of what you are seeing? If that is continuing to happen, we'd really appreciate if you can follow the steps listed in the "help us out" section. This will help us (and the Visual Studio team) get some more clues about this problem and investigate this further.

Afterwards please try going through the guidance listed on that page to see if that helps resolve this issue.

**Comment by genifycom** [comment]
I have the same issue in Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.10.5

It happened late Aug 1 2024.

Extension Manager does not show AWS Tookit as installed. The Extensions menu continues to have an AWS Tookit item but Add Project is missing Platform AWS.

Because the AWS Tookit shows as not installed, we cannot uninstall it. I did try a reinstall, but end up at the same place. I quit Visual Studio and saw the install working, but restarting Visual Studio shows AWS Toolkit as not installed.

Help!!!

**Comment by shruti0085** [comment]
Have you already attempted the manual uninstall steps and repair steps listed in #451? Did the manual uninstall not succeed?

If you have, can you please have a look at https://github.com/aws/aws-toolkit-visual-studio/issues/452, and if your system is still in a bad state, please follow through the "help us out" section to help us collect more data about the problem.

Additionally, please attach your ActivityLog.xml and toolkit logs after you have attempted the steps in #451

**Comment by jocere** [comment]
I didn't make any changes to VS yet, but as of this morning AWS Toolkit shows up in the Installed list, and has the 'Uninstall' option available. I didn't apply any updates, but on restarting my PC and opening VS I got a 'can't start while setup is running' pop-up.

**Comment by shruti0085** [comment]
Thank you for sharing an update that the issue may be resolved with an update of Visual Studio. Can you please share another update after the next day or two of usage to confirm that things continue to remain stable?

**Comment by jocere** [comment]
It is not stable, on starting VS this morning the AWS extension is back to the old state. It does not show up in the installed list, and I have to enter my AWS credentials manually before I can use AWS services

**Comment by shruti0085** [comment]
@jocere can you try the steps mentioned in [this comment](https://github.com/aws/aws-toolkit-visual-studio/issues/460#issuecomment-2302554312) and let us know if you're back in a functional state?

**Comment by jocere** [comment]
@shruti0085 I tried the process in the comment, I also re-installed the extension and it has been working well. Extension shows up in the installed list, and the prompt for authentication (sso) has been working.
