### ISSUE TITLE
Support adding shortcut keys to manually trigger code suggestions

### ISSUE THREAD

**Issue by romanholidaypancakes** [aws/aws-toolkit-visual-studio#459]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Sometimes amzq doesn't have code hints, I hope I can force code hints with shortcut keys

**Describe alternatives you've considered**

**Additional context**

This feature exists in the vscode plugin

**Comment by awschristou** [comment]
Inline coding suggestions can be provided by pressing `Alt+C`. You need to have Amazon Q enabled, and be logged in to Amazon Q in order for this feature to work.

This shortcut key is configurable within Visual Studio's keyboard shortcuts settings. The command that is bound to a shortcut is `AWSToolkit.CodeWhisperer.GetSuggestion`. You can find your current shortcut by looking at the menu from the Q menu in your document's margin.

![image](https://github.com/user-attachments/assets/8081567f-2ebb-4f1e-a343-ac5d240f3eca)

**Comment by awschristou** [comment]
This guide should help you get signed in and connected to Amazon Q features.
https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/q-in-IDE-setup.html#setup-vs

**Comment by awschristou** [comment]
Okay, if that's the case, you should only need to open up some code (currently C# or C++). 

In this sample image, I've created a new console app, and have the program file open. Once you have code open, you should see the Q menu down in the lower left margin of the code file.

![image](https://github.com/user-attachments/assets/14fb9a9b-1870-4e46-ab1f-5eead912f3df)

**Comment by awschristou** [comment]
Thank you for sharing the screenshot. Its possible that the shortcut key was unassigned somehow (for example by another extension). If you click in the "press shortcut keys" box and then press Alt+C, are you then able to assign the hotkey? (at this point you would be able to assign whatever shortcut key you want)

![image](https://github.com/user-attachments/assets/c069774c-487c-4284-9444-b7253444a994)
