### ISSUE TITLE
Enable MFA in the toolkit

### ISSUE THREAD

**Issue by gl137** [aws/aws-toolkit-visual-studio#46]
**Is your feature request related to a problem? Please describe.**
MFA has been implemented in workplace  and aws toolkit expressly doesn't work with MFA. MFA does work for awscli so why hasn't it been actioned in toolkit?

**Describe the solution you'd like**
Enable MFA within toolkit

**Describe alternatives you've considered**

**Additional context**

**Comment by gl137** [comment]
https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/credentials.html
Multi-Factor Authentication (MFA) profiles are not supported by the Toolkit for Visual Studio

**Comment by rli** [comment]
Hi, thanks for the suggestion! Unfortunately, the toolkit does not directly use the AWS CLI for credential management, but I'll make sure that this is on the team list of feature requests.

**Comment by mikebouck** [comment]
+1

**Comment by ryan-payet-wcc** [comment]
+1

**Comment by ysfaran** [comment]
Is there an update on this? I actually think this topic is really important.

.NET Developers are unable to work with AWS Toolkit, unless they are willing to reduce their security boundaries.
In my opinion enabling MFA is **a must** for every developer.

**Comment by dbaranovsky** [comment]
Same question, it's very painful to not have this feature

**Comment by marcbesancenot** [comment]
Could you please consider this feature request as important, degrading security for developers to work and debug is not a good option

**Comment by justinmk3** [comment]
Please add your upvote 👍  to the main description here.

**Comment by ig16022** [comment]
Any progress on this?

**Comment by woodyiii** [comment]
+1

**Comment by awschristou** [comment]
Hello, we have a test build of the toolkit that supports credentials that assume roles with MFA. If you're interested in trying it out, please have a look at https://github.com/aws/aws-toolkit-visual-studio/issues/98#issuecomment-809827673 for details.

**Comment by awschristou** [comment]
Version 1.21.0.0 of the Toolkit contains support for credentials that assume role with MFA.

Details can be found at:
* Blog post: https://aws.amazon.com/blogs/developer/introducing-aws-toolkit-for-visual-studio-support-for-aws-sso-and-assume-role-with-mfa/
* User docs: https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/mfa-credentials.html
