### ISSUE TITLE
Deployment to new target failed to publish asset

### ISSUE THREAD

**Issue by CDNSnow** [aws/aws-toolkit-visual-studio#466]
**Describe the bug**
Am attempting to deploy a VS project to AWS EB Windows. NodeJS is up to date. Here is the stack trace:
Deployment failed: Error: Failed to publish asset d9000f8aebb57f90580b35d37c2d6317a85010798a8370cf2637443b4193b4d0:752326669855-us-east-1
    at Deployments.publishSingleAsset (C:\Users\leath\.aws-dotnet-deploy\node_modules\aws-cdk\lib\index.js:454:11645)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.publishAsset (C:\Users\leath\.aws-dotnet-deploy\node_modules\aws-cdk\lib\index.js:454:197644)
    at async C:\Users\leath\.aws-dotnet-deploy\node_modules\aws-cdk\lib\index.js:454:181545

**To Reproduce**
Unknown

**Development System (please complete the following information):**
Toolkit Version: 1.58.0.0
Visual Studio: VS Community 2022
Visual Studio Version: 17.11.0
OS: Windows 11 Pro
OS Version: 10.0.22631.0
OS Architecture: X64

**Comment by philasmar** [comment]
Could you please list the steps you took to get to this error?

From the stack trace alone, this seems to be a NodeJS/CDK issue.
I'm not sure why the folder `leath.aws-dotnet-deploy` is used. The temp folder created by the deploy tool is `.aws-dotnet-deploy`.

**Comment by CDNSnow** [comment]
![image](https://github.com/user-attachments/assets/3a46fc27-56e2-4404-8de5-2a8e6b1d6f99)

✨  Synthesis time: 15.3s

current credentials could not be used to assume 'arn:aws:iam::752326669855:role/cdk-hnb659fds-deploy-role-752326669855-us-east-1', but are for the right account. Proceeding anyway.
current credentials could not be used to assume 'arn:aws:iam::752326669855:role/cdk-hnb659fds-deploy-role-752326669855-us-east-1', but are for the right account. Proceeding anyway.
CrainInsuranceSite:  start: Building 9283bc0ba06c25445fda7ee263ec32e4148df8e3325790136db7a2a8c30f827e:752326669855-us-east-1
CrainInsuranceSite:  success: Built 9283bc0ba06c25445fda7ee263ec32e4148df8e3325790136db7a2a8c30f827e:752326669855-us-east-1
CrainInsuranceSite:  start: Building d9000f8aebb57f90580b35d37c2d6317a85010798a8370cf2637443b4193b4d0:752326669855-us-east-1
CrainInsuranceSite:  success: Built d9000f8aebb57f90580b35d37c2d6317a85010798a8370cf2637443b4193b4d0:752326669855-us-east-1
CrainInsuranceSite:  start: Publishing 9283bc0ba06c25445fda7ee263ec32e4148df8e3325790136db7a2a8c30f827e:752326669855-us-east-1
CrainInsuranceSite:  start: Publishing d9000f8aebb57f90580b35d37c2d6317a85010798a8370cf2637443b4193b4d0:752326669855-us-east-1
current credentials could not be used to assume 'arn:aws:iam::752326669855:role/cdk-hnb659fds-file-publishing-role-752326669855-us-east-1', but are for the right account. Proceeding anyway.
current credentials could not be used to assume 'arn:aws:iam::752326669855:role/cdk-hnb659fds-file-publishing-role-752326669855-us-east-1', but are for the right account. Proceeding anyway.
CrainInsuranceSite:  fail: No bucket named 'cdk-hnb659fds-assets-752326669855-us-east-1'. Is account 752326669855 bootstrapped?
CrainInsuranceSite:  fail: No bucket named 'cdk-hnb659fds-assets-752326669855-us-east-1'. Is account 752326669855 bootstrapped?

 ❌ Deployment failed: Error: Failed to publish asset d9000f8aebb57f90580b35d37c2d6317a85010798a8370cf2637443b4193b4d0:752326669855-us-east-1
    at Deployments.publishSingleAsset (C:\Users\leath\.aws-dotnet-deploy\node_modules\aws-cdk\lib\index.js:454:11645)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.publishAsset (C:\Users\leath\.aws-dotnet-deploy\node_modules\aws-cdk\lib\index.js:454:197644)
    at async C:\Users\leath\.aws-dotnet-deploy\node_modules\aws-cdk\lib\index.js:454:181545

Failed to publish asset d9000f8aebb57f90580b35d37c2d6317a85010798a8370cf2637443b4193b4d0:752326669855-us-east-1


CrainInsuranceSite could not be published as ASP.NET Core App to AWS Elastic Beanstalk on Windows: We had an issue deploying your application to AWS. Check the deployment output for more details. Deployment took 17.65s.
CrainInsuranceSite failed to publish to AWS.
CrainInsuranceSite could not be published as ASP.NET Core App to AWS Elastic Beanstalk on Windows: We had an issue deploying your application to AWS. Check the deployment output for more details. Deployment took 17.65s.
CrainInsuranceSite failed to publish to AWS.
CrainInsuranceSite could not be published as ASP.NET Core App to AWS Elastic Beanstalk on Windows: We had an issue deploying your application to AWS. Check the deployment output for more details. Deployment took 17.65s.
CrainInsuranceSite failed to publish to AWS.

**Comment by CDNSnow** [comment]
Oh--I did bootstrap it from the CLI.

**Comment by normj** [comment]
Can you share the logs in the toolkit from the "Configure AWS Cloud Development Kit (CDK)" collapsed section. I would have expect that to take care of bootstrapping.

**Comment by CDNSnow** [comment]
In doing so, I run into a permission problem. I see the JSON that needs to be added in the docs. But selecting myself as the user in the IAM Identity console, I do not see the permission tab that the documentation describes. I am root. Do you know why this is happening? When I bootstrap from the CLI, where does the account info come from?

**Comment by CDNSnow** [comment]
Problem solved. The bootstrapper,, having been run three times, failed to create a StagingBucket. Created it by hand and the app deployed.

**Comment by shruti0085** [comment]
@CDNSnow glad to hear your issue was resolved. We will close this issue. Please feel free to create a new github issue if you run into this again.
