### ISSUE TITLE
Can't uninstall, not showing as installed extension, reinstall won't work

### ISSUE THREAD

**Issue by WiseyD** [aws/aws-toolkit-visual-studio#469]
**Computer (please complete the following information):**

- Windows Version: Windows 10 22h@
- Visual Studio Version:17.11.3
- AWS Toolkit for Visual Studio Version: ?

Don't remember installing, is throwing an error on start up, nothing showing for AWS toolkit under installed extensions. Trying to re-install hoping it would show under installed extensions so I could remove. Won't install as it says its already installed. No option to uninstall, tried removing the AWS Toolkit folder from the appdata folder but when launching Visual studio it acts as if I just installed it and wants me to configure the toolkit, with the getting stated page loading. How do I get rid of this extension?

**Comment by awschristou** [comment]
Hi, you can uninstall the extension with the following steps:

- From the Windows start menu, Developer Command Prompt for VS 2022
- In the developer command prompt, uninstall the extension using the VSIX Installer by running: `vsixinstaller.exe /uninstall:0B82CB16-0E52-4363-9BC0-61E758689176`

**Comment by thoffmann-fms** [comment]
The other way to uninstall is via the Visual Studio Updater UI and the Modify button and un-check it.  It will show the AWS Toolkit as installed even if it's missing from the Visual Studio Extensions menu.
![image](https://github.com/user-attachments/assets/f6a79117-e4df-4ffb-ba88-ce4308781a69)
