### ISSUE TITLE
AWS Explorer is not appearing in Visual Studio 2022 with the AWS Toolkit

### ISSUE THREAD

**Issue by augspurgerr** [aws/aws-toolkit-visual-studio#477]
AWS Tools are not appearing in Visual Studio 2022. None of the features are working. I only see the AWS Toolkit in my menu bar, but only allowed to read the manual. None of the tools are displayed in the app. None of the menu items are displayed in the app. I tried uninstalling and reinstalling the toolkit.

**To Reproduce**
Update Visual Studio 2022 Enterprise to latest version.
Download the AWS Toolkit from Microsoft: https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2022
Install AWS Toolkit.

**Screenshots**
AWS Explorer does not appear in View Menu
![image](https://github.com/user-attachments/assets/e33d6525-1040-4c8b-a740-29830c8069f5)

"Publish to AWS Elastic Beanstalk...", does not appear in menu
![image](https://github.com/user-attachments/assets/dcc7dc3c-c981-4565-9608-645b062125a4)

AWS Menu has just read-me content
![image](https://github.com/user-attachments/assets/72f21115-fc59-462d-b468-d0c02900316c)

**Development System (please complete the following information):**
- Windows Version: Windows 10 Enterprise, Version 10.0.19045 Build 19045
- Visual Studio Version: Visual Studio 2022 Enterprise V17.11.5
- AWS Toolkit for Visual Studio Version: 1.60.0.0

I followed the instructions: https://github.com/aws/aws-toolkit-visual-studio/issues/451 that didn't work.

**Comment by awschristou** [comment]
Hi @augspurgerr , thank you for reaching out. With [version 1.59.0.0](https://github.com/aws/aws-toolkit-visual-studio/blob/main/CHANGELOG.md#15900-2024-10-24) of the AWS Toolkit extension, we've introduced a new getting started experience, which allows you to fully enable and disable feature sets in the extension. It sounds like in your case, the extension thinks things are disabled. From the  "Extensions" > "AWS Toolkit" > "Getting Started" menus, have a look at the "AWS Toolkit" feature. If it is disabled, you will need to enable it by setting up an auth connection (adding new credentials or selecting from existing ones).

**Comment by augspurgerr** [comment]
Thank you! That worked.
