### ISSUE TITLE
Bug when passing environment variables for lambda deployment

### ISSUE THREAD

**Issue by jpf5064** [aws/aws-toolkit-visual-studio#54]
Using the Visual Studio Toolkit for VS 2019. When passing environment variable - We are using json format and serializing within aws-lambda-tools-default.json. In the UI for publishing to Lambda the variable isn’t passed properly. We only see {.

However, we can publish without issue using the cli or in the console by pasting the variable.

**Comment by justinmk3** [comment]
.

**Comment by awschristou** [comment]
Hi @jpf5064 , the `environment-variables` field should be a semicolon-delimited set of key-value pairs, and the full value should be escaped.

For example, if I wanted to set the environment variables `foo=bar` and `bar=baz`, my aws-lambda-tools-default.json would look like:

```json
{
    "profile"     : "<your credentials profile>",
    "region"      : "us-west-2",
    "configuration" : "Release",
    "function-runtime"      : "dotnet6",
    "function-memory-size"  : 256,
    "function-timeout"      : 30,
    "function-handler"      : "<your lambda function handler>",
    "framework"             : "net6.0",
    "function-name"         : "zzzzz",
    "environment-variables"    : "\"foo\"=\"bar\";\"bar\"=\"baz\""
}
```

And when I go to publish this Lambda, I can see the environment variables populated in the advanced function details screen:
![image](https://user-images.githubusercontent.com/39839589/206585281-0457e8e0-a2ec-4ef1-9a7e-e5899bce7898.png)

One way to try populating the `environment-variables` field in the json file would be to fill out the values in the publish wizard once, and then publish, which will save the values to the json file.
