### ISSUE TITLE
Add support for creating/updating Lambda functions with Node.js 12.x

### ISSUE THREAD

**Issue by ChaseKR** [aws/aws-toolkit-visual-studio#58]
The list of language runtimes available for creating/Lambda functions is outdated and is only current to Node.js v8.10. Previously, this was a minor annoyance and I would just update it through the AWS web console. But now, when I try to publish, my upload fails and I'm presented with the error "The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions."

Thank you! Let me know how I can help.

**Comment by awschristou** [comment]
Hi @ChaseKR can you please share which version of the toolkit and Visual Studio you are using? The latest version of the toolkit is 1.16.0.0. It supports Visual Studio 2017 & 2019, and should allow you to create node 10 and node 12 lambda functions.

**Comment by ChaseKR** [comment]
Hi @awschristou - thanks for the quick and helpful response! Turns out the particular installation of VS I was working from wasn't applying my extensions updates. I applied the latest and I can see the latest Node.js runtimes now, 😊
