### ISSUE TITLE
Error uploading function

### ISSUE THREAD

**Issue by Ahmedyasser00** [aws/aws-toolkit-visual-studio#60]
**Describe the bug*
I'm trying to publish my function along past 30 hrs and I can't and Now when I'm trying to go to the website to check if there are somthing be updated I found "This site can't be reached"
https://amazonwebservices.gallerycdn.vsassets.io/extensions/amazonwebservices/awstoolkitforvisualstudio2017/1.16.1.0/1582154896754/AWSToolkitPackage.vsix

**To Reproduce**
1. right click on the function
2. Click on puplish to AWS lambda
3.Click on next
4.Click on upload
4. publishing goes to infinitie and after some time the popup appear with "error uploading function"

**Screenshots**
![publishing](https://user-images.githubusercontent.com/34465912/75079465-768d5400-5511-11ea-95ca-d8e8ebb8ffcb.png)
![error](https://user-images.githubusercontent.com/34465912/75079511-9f154e00-5511-11ea-9ac2-341426a74417.png)

**Computer (please complete the following information):**

- Windows Version:10
- Visual Studio Version: 2019
- AWS Toolkit for Visual Studio Version:

**Additional context**

**Comment by normj** [comment]
After you get the error box can you check the Toolkit's logs to see if there is any more information? The logs are stored in the `C:\Users\<user-id>\AppData\Local\AWSToolkit\logs\visualstudio` folder.

**Comment by manonandu** [comment]
@Ahmedyasser00 - Are you running visual studio as Administrator?

**Comment by awschristou** [comment]
I am closing this issue due to a lack of activity. If you are still having problems publishing Lambda functions in the Toolkit, please file a new issue with your repro steps, and any available logging information.
