### ISSUE TITLE
Automatic detect Content Type on upload in S3

### ISSUE THREAD

**Issue by mdido78** [aws/aws-toolkit-visual-studio#64]
IT would be great if the Content Type will be automatically detected during upload like in browser console. 

We use this often and we are constantly typing it manually (ex. Content-Type: application/json)

**Comment by normj** [comment]
That was actually recent PR to the AWS .NET SDK to auto map application/json content-type. We need to update the SDK version the toolkit is using and it will pick up that change.

**Comment by mdido78** [comment]
Thanks, this is great!

**Comment by awschristou** [comment]
I'll re-open this issue until we release a version of the toolkit that contains the fix.

**Comment by awschristou** [comment]
VS Toolkit 1.17.0.0 is now available, which has a fix for this issue.
