### ISSUE TITLE
Version 16.5.0 of Visual Studio 2019 fails to launch views after aws wizard executions

### ISSUE THREAD

**Issue by normj** [aws/aws-toolkit-visual-studio#65]
**Describe the bug**
This bug affects only latest release of Visual Studio 2019 which is version 16.5.0 and came out 3/16/2020. I have tested in VS 2017 and the bug isn't present. I don't know how to revert my install from an earlier version of 16.5.0 but I have been using the toolkit heavily this past month and would have noticed if it was happening in 16.4.0 which I had installed till earlier this week.

For all of the wizards in the toolkit that launch a view after the wizard is complete, like the deploy lambda function, you get an error dialog saying the view is already opened do you want to close it first. I have reproduced the issue in the Lambda, Beanstalk and ECS wizard so far. The same views come up correctly from the AWS Explorer.

**To Reproduce**
Steps to reproduce the behavior
example:
1. Ensure Visual Studio is updated to 16.5.0
2. Run through the Lambda deployment wizard.

**Expected behavior**
View comes up with no errors.

**Screenshots**

![image](https://user-images.githubusercontent.com/1653751/77240471-52ba3e00-6ba3-11ea-978f-4ed48276d17d.png)

![image](https://user-images.githubusercontent.com/1653751/77240473-5cdc3c80-6ba3-11ea-8bb7-272342552694.png)

If you click Yes on this dialog then the view is display box then the view is displayed so the bug isn't a complete blocker but extremely confusing and annoying.

**Comment by normj** [comment]
The AWS Explorer and the wizard uses the same code path for launching the views. The only difference I can think of is the Wizard currently has a modal dialog open. As an experiment I had the Lambda wizard do a 2 second delay of launching the view which ensured the wizard was closed before the view was opened. In that case I didn't see the error.

**Comment by normj** [comment]
We have reported the issue to Microsoft and they have given us a workaround. The fix is queued up to go out soon.

https://developercommunity.visualstudio.com/content/problem/965841/vs-extension-having-issues-opening-custom-editor.html

**Comment by awschristou** [comment]
VS Toolkit 1.17.0.0 is now available, which has a fix for this issue.
