### ISSUE TITLE
Support Gov Cloud Regions with MFA

### ISSUE THREAD

**Issue by powersparks** [aws/aws-toolkit-visual-studio#67]
**Is your feature request related to a problem? Please describe.**
on the same machine, I use AWS CLI, and have profiles setup for the gov cloud region. the options for regions are based on the commercial regions. If AWS Cli is  used, these regions are part of the configuration. However, support for gov cloud would be nice, (us-gov-west-1)

**Describe the solution you'd like**
new projects would work with the AWS CLI, e.g., .aws/ , config and credentials already hosted on my account

**Describe alternatives you've considered**
VSCode with the AWS cli works within the provided terminals (powershell, bash)

**Additional context**
none

**Comment by awschristou** [comment]
Hi @powersparks , thanks for reaching out. If you have a Gov Cloud based account, you can access those regions from the Visual Studio toolkit. The toolkit needs to be configured so that it knows your account is based in the Gov Cloud partition. See step 3, specifically **Account Type** in the [Credentials](https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/credentials.html) section of the User Guide.

**Comment by powersparks** [comment]
yes.. I just made it thru some of the documentation... and came back to change my issue. I think it's the MFA that is tripping it up. Taking a look at the "step 3" and will update my issue in a moment.

**Comment by awschristou** [comment]
Thanks for the update -- MFA is not supported by the toolkit at this time, but more conventional shared credentials types (plain old access key and secret, assume role, credentials_process) are supported.

**Comment by powersparks** [comment]
So I was able to work around the MFA, by first creating the profile "dev-myprofilename", select gov cloud, then shutdown visual studio. 
Next step is to edit the profile in the ./aws/credential file to include the token based on the aws cli command: 
`aws sts get-session-token --serial-number <your serial number> --token-code <code> --profile dev-default`
the ./aws/credential  file would look something like this once your done
 
```
    [dev-default]
    aws_access_key_id = <key> 
    aws_secret_access_key = <secret>

   output=json
   region=us-gov-west-1
   toolkit_artifact_guid=<generated by the toolkit>

   [dev-myprofilename]
   aws_access_key_id = <key>
   aws_secret_access_key = <your secret>
   aws_session_token = <your token>
   output=json
   region=us-gov-west-1
   toolkit_artifact_guid=<generated by the toolkit>
```

**Comment by powersparks** [comment]
I am closing this as the 2 MFA just needs to be added to the credential file after the initial profile is setup for gov cloud is done.
