### ISSUE TITLE
Publish to AWS gives file already open

### ISSUE THREAD

**Issue by genifycom** [aws/aws-toolkit-visual-studio#68]
**Describe the bug**
Whenever I Publish to AWS from Visual Studio 2019 16.5.1 I get a message dialog that says:

The document '%userprofile%\documents\.aws\temp\b38ca48f-610e-486c-95fa-d6596f9af50b.hostedControl' is already open. Do you want to close it?

This showed up after upgrading Visual Studio from 16.4

**Comment by normj** [comment]
Yes version 16.5.0 of Visual Studio 2019 has a regression. We have been working with Microsoft to get the issue resolved. We have a fix queued up in the toolkit which is going out very soon. We are tracking the issue using the following issue https://github.com/aws/aws-toolkit-visual-studio/issues/65
