### ISSUE TITLE
Publish to AWS Lambda uses Stale Credentials

### ISSUE THREAD

**Issue by timedroid** [aws/aws-toolkit-visual-studio#69]
**Describe the bug**
I login to AWS using temporary credentials obtained through federation and written to the default profile in .aws\credentials.

It appears these are cached and not re-read when expired. I've noticed with at least the publish function.

**To Reproduce**
1. Open a Lambda project in Visual Studio 2019 while having valid AWS credentials.
2. Publish lambda function.
3. Wait until credentials expire.
4. Attempt to publish lambda function again, get error about credentials being expired.
5. Obtain new credentials using federation.
6. Attempt to publish again.

**Expected behavior**
New credentials should be read from the default profile without needing to restart Visual Studio.

**Screenshots**
![image](https://user-images.githubusercontent.com/452024/78187581-a9920400-743c-11ea-9c31-f360cbc3ac3f.png)

**Computer (please complete the following information):**

- Windows 10
- Visual Studio 2019 16.4.5
- AWS Toolkit for Visual Studio Version:1.16.1.0

**Additional context**

**Comment by lakshmi220** [comment]
even am getting the same issue. any resolution please???

**Comment by awschristou** [comment]
Changes to how credentials are handled were made in version 1.21.0.0 of the Toolkit:
* The Toolkit now refreshes when it detects changes in the credentials files
* Each time the Publish Lambda dialog is opened, the credentials are validated before you can proceed to deploy

Also, the Toolkit supports AWS SSO based credentials, which you might be interested in trying out - [Blog post](https://aws.amazon.com/blogs/developer/introducing-aws-toolkit-for-visual-studio-support-for-aws-sso-and-assume-role-with-mfa/)

Please try these out, and file a new issue if you are still encountering issues.
