### ISSUE TITLE
AmazonS3Client Issue

### ISSUE THREAD

**Issue by muthukrishnan32** [aws/aws-toolkit-visual-studio#71]
**Describe the bug**
Method not found: 'Amazon.Runtime.RequestRetryMode Amazon.Runtime.IClientConfig.get_RetryMode()'.

**To Reproduce**
1) Installed AWSSDK.S3 for my project.
2) Consuming AmazonS3Client and AmazonS3Config
3) I'm getting the above exception

**Expected behavior**
Error free.

**Screenshots**
Attached.
![image](https://user-images.githubusercontent.com/48045413/78740492-8c958d80-7974-11ea-867f-a2adff6d8a50.png)

**Computer (please complete the following information):**
- Windows Version: Windows 10 Pro
- Visual Studio Version: Community 2017 Version 15.9.17, .Net Framework 4.8
- AWS Toolkit for Visual Studio Version: 1.16.1.0

**Comment by normj** [comment]
Is this with debugging a Lambda function with the Lambda Mock Test Tool?

**Comment by muthukrishnan32** [comment]
Yes you are correct...

**Comment by normj** [comment]
Okay, I'm working on getting a fix out. https://github.com/aws/aws-lambda-dotnet/pull/620. I'll respond back when I get the fix out.

**Comment by muthukrishnan32** [comment]
Thanks, I'm waiting for it..

**Comment by normj** [comment]
Version 0.10.1 of the test tool is out with the fix. If you close and reopen the Solution in Visual Studio that should automatically update you to the latest version with the fix.

**Comment by muthukrishnan32** [comment]
sure sir...let me do now...and will let you know..

**Comment by muthukrishnan32** [comment]
Yes. Now I'm not getting any exception like before. Thanks for it. But will confirm shortly once everything is working fine completely. If possible, can you please give me any code samples for delete files in S3 bucket.

**Comment by normj** [comment]
Great, thanks for confirming the issue is fixed.

As far as deleting an object in S3 it looks like you are very close judging from the screenshot. An issue I see with the code is the `DeleteObjectAsync` is an async call so you will want to use async/await when making calls with the AWS SDK.

**Comment by muthukrishnan32** [comment]
Hi,
Please see the attached screenshot of response. My file is not deleted from the S3.
![image](https://user-images.githubusercontent.com/48045413/78770646-7b687300-79ac-11ea-9fcf-d375cd1c334e.png)

**Comment by muthukrishnan32** [comment]
Hi,
I tried several ways, but im not able to delete a file. Could you please help me and let me know where im making mistake.

**Comment by muthukrishnan32** [comment]
Finally, I resolved it. Thanks for your support.
