### ISSUE TITLE
AWS Toolkit start page unable to fill in credential details

### ISSUE THREAD

**Issue by CharlesShen** [aws/aws-toolkit-visual-studio#72]
Under certain screen resolutions and screen DPIs, the start page needs to have scrolling enabled in the form so that AWS credentials can be filled.

![image](https://user-images.githubusercontent.com/2334303/78920621-8670e100-7a48-11ea-9876-42abafda613e.png)

**Comment by awschristou** [comment]
A fix for this has been released in v1.17.1.0 of the toolkit
