### ISSUE TITLE
In VS dark mode, the Elastic Beanstalk Availability Zones are hard to read due to black text

### ISSUE THREAD

**Issue by CharlesShen** [aws/aws-toolkit-visual-studio#73]
Screenshot provided highlighting the issue

![image](https://user-images.githubusercontent.com/2334303/78921245-76a5cc80-7a49-11ea-8a41-e6cf5d77fdc5.png)

**Comment by awschristou** [comment]
A fix for this has been released in v1.17.1.0 of the toolkit
