### ISSUE TITLE
launchSettings.json is using %USERNAME% instead of %USERPROFILE%

### ISSUE THREAD

**Issue by jamespfluger** [aws/aws-toolkit-visual-studio#83]
**Describe the bug**
This is an issue with the Mock Lambda Test Tool, but as reasoned in the context, I am opening the bug here.

The issue is that `launchSettings.json` is using `%USERNAME%` as part of the `executablePath` attribute. However, `%USERNAME%` will not always resolve to a path, and the tool fails to launch. `%USERPROFILE%` should be used instead.

**To Reproduce**
1. Login into Windows with a user whose username is NOT equivalent to their user profile name.
2. Create an "AWS Lambda Project (.NET Core - C#)"
3. Attempt to launch the Mock Lambda Test Tool
4. Receive error about not being able to locate the executable
5. Note that the path being looked for uses the username, which does not resolve to a directory.
6. (Optional) Run these commands to view the environmental variables for `%USERNAME%` and 
`Write-Output $env:username`
`Write-Output $env:userprofile`

**Expected behavior**
The Mock Lambda Test Tool should launch without issue.  
`%USERNAME%` is not guaranteed to resolve to the user's profile directory the same way that `%USERPROFILE%` is

**Screenshots**
![image](https://user-images.githubusercontent.com/16975008/80658414-b0b42e00-8a4b-11ea-8307-32810256f972.png)

**Computer:**
- Windows Version: Windows 10 Home - 10.0.18363
- Visual Studio Version: Visual Studio Community 2019 - 16.5.4
- AWS Toolkit for Visual Studio Version: 1.17.1.0

**Additional context**
While this is an issue with the Mock Lambda Test Tool, as per  aws/aws-lambda-dotnet#397, specifically [Norm's comment here](https://github.com/aws/aws-lambda-dotnet/issues/397#issuecomment-584333104) the AWS toolkit is what determines the options in the `launchSettings.json` file.

`%USERNAME%` will not always resolve to a proper path. It is the actual *name* of the user, but the path to their profile may be different. `%USERPROFILE%` will get the path instead of just the name.

My `%USERNAME%` is `James`, but my `%USERPROFILE%` directs to `C:\Users\me` because when I set up my laptop, the prefix of my email was used as the user folder. There is no easy way to modify this.

When a project is created, the `executablePath` attribute is created as such:
`"executablePath": "C:\\Users\\%USERNAME%\\.dotnet\\tools\\dotnet-lambda-test-tool-3.1.exe"`

I believe it should be 
`"executablePath": "%USERPROFILE%\\.dotnet\\tools\\dotnet-lambda-test-tool-3.1.exe"`

**Comment by diogocp** [comment]
This is very annoying because even if I fix it myself, the path keeps getting rewritten by the toolkit (this seems to happen when there is a merge conflict in the csproj file, forcing a reload of the project).

**Comment by awschristou** [comment]
Hi @jamespfluger and @diogocp , if we produced a preview build of the toolkit containing a fix for this issue, would you be interested in trying it out?

**Comment by jamespfluger** [comment]
Absolutely, just let me know what to do

**Comment by awschristou** [comment]
I have made a test build of the toolkit containing a fix that should set `%USERPROFILE%` (instead of %USERNAME%) into the `launchsettings.json` file when you load a project into Visual Studio.

If you have a chance to try it out, I would be interested in hearing how it worked for you.
* Download [AWSToolkitPackage.zip](https://github.com/aws/aws-toolkit-visual-studio/files/5171186/AWSToolkitPackage.zip)
* Unzip the file. It contains the toolkit as a .vsix file
* Close down your running Visual Studio instances
* double click the .vsix file to install it
* after the VSIX installer completes, re-launch Visual Studio and try out this version of the toolkit

(cc: @jamespfluger , @diogocp )

**Comment by diogocp** [comment]
Thanks @awschristou, that fixed the issue for me.

The only remaining annoyance is that it removes (or does not insert) the newline at end of file.

**Comment by shruti0085** [comment]
Thanks for your feedback @diogocp. 
Can you elaborate on the issue i.e which file is missing the newline?

**Comment by diogocp** [comment]
launchSettings.json

**Comment by jamespfluger** [comment]
@awschristou That fixed the issue for me as well. Thanks for the fix

**Comment by awschristou** [comment]
Thank you for trying out the test build @diogocp and @jamespfluger !

> The only remaining annoyance is that it removes (or does not insert) the newline at end of file.

Please file a separate issue for this behavior so that it can be tracked and investigated separate from the executablePath issue.

**Comment by awschristou** [comment]
v1.19.0.0 of the Toolkit is now available, which sets the test tool path using `USERPROFILE` when solutions are loaded.
