### ISSUE TITLE
AWS Serverless Template in Visual Studio 2019 Removes the IIS Express Debug Option

### ISSUE THREAD

**Issue by DeniseJames** [aws/aws-toolkit-visual-studio#86]
After I create a blogAPI using the AWS template the debug option to use IIS Expression is no longer available. Instead I only have the Mock Lambda Test Tool to debug.  

I added this to the launchsettings.json file:

`{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:60964/",
      "sslPort": 44364
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    
  }
}`
to the initial code below:
`"Mock Lambda Test Tool": {
      "commandName": "Executable",
      "executablePath": "C:\\Users\\%USERNAME%\\.dotnet\\tools\\dotnet-lambda-test-tool-3.1.exe",
      "commandLineArgs": "--port 5050",
      "workingDirectory": ".\\bin\\$(Configuration)\\netcoreapp3.1"
    }`

If I use the Web API AWS template I do get the IIS Express.  I want to use the dynamoDB template.

**Comment by michaelsync** [comment]
Any update on this issue?

**Comment by awschristou** [comment]
The two sample Serverless Project blueprints in question are "ASP.NET Core Web API" and "Blog API using DynamoDB".

Both projects contain a CloudFormation template file (`serverless.template`) and one or more Lambda Function entrypoints. The Web API project leverages ASP.NET Core (see the PackageReference for "Amazon.Lambda.AspNetCoreServer"), and the Blog API project contains simple Lambda function handlers for `APIGatewayProxyRequest` events. API Gateway is used to route requests to both projects, however ASP.NET Core is not used in the Blog API project, so IIS Express is not an option there.
