### ISSUE TITLE
dotnet-lambda-test-tool-3.1.exe does not exist

### ISSUE THREAD

**Issue by adibradfield** [aws/aws-toolkit-visual-studio#90]
**Describe the bug**
When trying to debug an existing serverless project, I received the above error message

**To Reproduce**
1. Open an existing serverless project targeting .NET Core 3,1
2. The debug profile should be set to run the executable "C:\Users\%USERNAME%\.dotnet\tools\dotnet-lambda-test-tool-3.1.exe" as it was set as the default
3. Attempt to launch the Mock Lambda Test Tool

**Expected behavior**
The test tool should launch as it did previously

**Screenshots**
![image](https://user-images.githubusercontent.com/12462105/81814451-b6684400-9520-11ea-9c2f-6672b655710c.png)
![image](https://user-images.githubusercontent.com/12462105/81814462-b8ca9e00-9520-11ea-9536-d8d64f017f61.png)

**Computer (please complete the following information):**

- Windows Version: Windows 10 1903
- Visual Studio Version: 2019 16.5.2
- AWS Toolkit for Visual Studio Version: 1.17.1.0

**Additional context**
Looks like for some reason the executable has suddenly gone missing from yesterday. Has happened to a few of my colleagues as well

**Comment by adibradfield** [comment]
Was able to fix it by running `dotnet tool uninstall --global Amazon.Lambda.TestTool-3.1` and then `dotnet tool install --global Amazon.Lambda.TestTool-3.1 --version 0.10.0`. Don't know if you want to keep this open, as I'm not sure what caused the tool installation to get messed up

**Comment by rli** [comment]
Thanks, glad you figured it out, we'll keep this open for investigation.

**Comment by Katy-kaboom101** [comment]
I didn’t figure it out see someone keeps accessing everything

**Comment by normj** [comment]
@adibradfield  Is this a project that is being shared across team members and is the launchSettings.json file checked into source control?

**Comment by adibradfield** [comment]
The answer to both of those is yes.

The issue appeared to be that the exe from the nuget package for the tool got deleted somehow. That tool was still installed, just the exe was missing

It's possible that for some reason it got picked up by the AV that we all use, but I couldn't see anything in the logs that would indicate that. Just strange that it happened on the same day for multiple people. Maybe an automatic update went wrong?

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by julealgon** [comment]
We had this exact same problem with a new hire who joined the team. He installed Visual Studio, then installed the AWS Toolkit, but was unable to debug any lambda projects as the "lambda test tool" was missing.

I asked him to try creating a new lambda project in the solution from AWS's template to see if that would force install the tool and it worked.

However, this is far from a desirable user experience. Once the Toolkit is installed, the lambda test tool should also be installed at the same time.

**Comment by awschristou** [comment]
Hi @julealgon , could your teammate try temporarily renaming the `Properties/launchSettings.json` file from your existing lambda projects, then close and reopen the solution in Visual Studio? When the solution is re-opened, the toolkit should create a new launchSettings.json file, and it would be interesting to know if (1) the file did get created and (2) if there are any noteworthy differences between the two files.

**Comment by julealgon** [comment]
> could your teammate try temporarily renaming the Properties/launchSettings.json file from your existing lambda projects, then close and reopen the solution in Visual Studio? When the solution is re-opened, the toolkit should create a new launchSettings.json file, and it would be interesting to know if (1) the file did get created and (2) if there are any noteworthy differences between the two files.

As I mentioned earlier @awschristou , my idea of creating a new project actually worked, so the tool ended up being installed in his machine. 

Perhaps I wasn't clear enough, but I suggested him to just create a dummy lambda project using the AWS template to force the installation, and then the dummy project was deleted. This process allowed him to run the existing, unaltered lambda project in the solution. Now he can run the tests just fine in subsequent Visual Studio executions.

**Comment by awschristou** [comment]
Thanks for clarifying. The Toolkit tries to install the lambda test tool when a solution is loading that seems to contain a lambda project. I wonder if there was a one-off failure the first time your solution was loaded. Please let us know if you continue to see any failures in setting up your project with the test tool.

I will close this issue at this time with the following workarounds:
* https://github.com/aws/aws-toolkit-visual-studio/issues/90#issuecomment-627970206
* https://github.com/aws/aws-toolkit-visual-studio/issues/90#issuecomment-786078000

**Comment by julealgon** [comment]
> The Toolkit tries to install the lambda test tool when a solution is loading that seems to contain a lambda project.

@awschristou have you considered moving the installation process from solution loading to the Toolkit installation itself? Is there a specific reason why the lambda test tool is not immediately installed as part of the toolkit installation and instead is done this way?

**Comment by awschristou** [comment]
We try to avoid bundling additional tools in the toolkit for a couple of reasons...
* Tools like the lambda test tool are developed and released independently of the Toolkit. If these tools were bundled in the Toolkit, it would require the Toolkit to be released any time there was a new version of any additional tool.
* Bundling the tools in with the Toolkit would increase the size of the Toolkit extension. 

People use the Toolkit in different ways -- some tools aren't relevant to their typical use cases, so we try to load-on-demand when possible. That said, there's always an opportunity to make the experience more seamless.

**Comment by julealgon** [comment]
I appreciate the clarification @awschristou . In that case, perhaps the toolkit installer should have some smarts to have "modules" like Visual Studio does, where the user can select what he wants to install, or add a module later on to the installation.

That's just a thought though.

Cheers.

**Comment by MattGrdinic** [comment]
For what it's worth **AVG (Business)** was indeed the culprit for me, satting:

"dotnet-lambda-test-tool-3.1.exe is infected with **IDP.Generic**". 

It would then remove (quarantine) the file, and even blocked the install location after reinstalling it a few times. Caught on to my ways it seems lol.
