### ISSUE TITLE
Missing assembly Microsoft.VisualStudio.Threading prevents Toolkit startup

### ISSUE THREAD

**Issue by Anna-liu-77** [aws/aws-toolkit-visual-studio#94]
**Describe the bug**
The toolkit for vs package can't load and can't create dotnet project

**To Reproduce**

1. follow the user guide to install the 'AWS Toolkit for Visual Studio', website is 

[https://docs.aws.amazon.com/zh_cn/toolkit-for-visual-studio/latest/user-guide/welcome.html](url)

2. after install complete, restart the Visual Studio, see the warning like this:
![warning](https://user-images.githubusercontent.com/59682597/83213660-44853100-a195-11ea-98f9-36d1022849c7.jpg)

**Computer (please complete the following information):**

- Windows Version:
- Visual Studio Version: 2017
- AWS Toolkit for Visual Studio Version:

**Comment by awschristou** [comment]
Hi @Anna-liu-77 , 

What version of the AWS Toolkit did you install?

Can you please attach the ActivityLog.xml log file mentioned in that error message to this issue?

**Comment by Anna-liu-77** [comment]
> Hi @Anna-liu-77 ,
> 
> What version of the AWS Toolkit did you install?
> 
> Can you please attach the ActivityLog.xml log file mentioned in that error message to this issue?

The version of the AWS Toolkit is 
![screenshot about version of toolkit](https://user-images.githubusercontent.com/59682597/83213084-d5f3a380-a193-11ea-998e-f1f9e38465bf.PNG)

The ActivityLog.xml log file is below attachment:
(this website don't support the file type, so changed to txt
[ActivityLog.txt](https://github.com/aws/aws-toolkit-visual-studio/files/4699311/ActivityLog.txt)
)

**Comment by awschristou** [comment]
Thank you, this appears to be the error of interest:

> Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=15.8.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

I will need to investigate this. In the meantime, can you please let me know your Visual Studio version? From the Help menu, select "About Visual Studio". Here is an example of the version I am interested in:

![image](https://user-images.githubusercontent.com/39839589/83278728-e4888d80-a188-11ea-8867-23b5df7f59e1.png)

**Comment by Anna-liu-77** [comment]
> Thank you, this appears to be the error of interest:
> 
> > Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=15.8.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
> 
> I will need to investigate this. In the meantime, can you please let me know your Visual Studio version? From the Help menu, select "About Visual Studio". Here is an example of the version I am interested in:
> 
> ![image](https://user-images.githubusercontent.com/39839589/83278728-e4888d80-a188-11ea-8867-23b5df7f59e1.png)

Thank you so much,  I updated the version of VS, it works. 
![vs2017-version](https://user-images.githubusercontent.com/59682597/83368599-033a8e80-a3ec-11ea-81e2-4374eac4833b.PNG)

**Comment by xetle** [comment]
Hi
I get the same error. I have Visual Studio Professional 15.6.4. 
I installed AWS Toolkit version 1.18.0.0

    <hr>80004005 - E_FAIL</hr>
The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Threading, Version=15.8.0.0

[ActivityLog.txt](https://github.com/aws/aws-toolkit-visual-studio/files/4891619/ActivityLog.txt)

**Comment by Anna-liu-77** [comment]
> Hi
> I get the same error. I have Visual Studio Professional 15.6.4.
> I installed AWS Toolkit version 1.18.0.0
> 
> ```
> <hr>80004005 - E_FAIL</hr>
> ```
> 
> The system cannot find the file specified. File name: 'Microsoft.VisualStudio.Threading, Version=15.8.0.0
> 
> [ActivityLog.txt](https://github.com/aws/aws-toolkit-visual-studio/files/4891619/ActivityLog.txt)

**Comment by xetle** [comment]
Hi - I've installed Visual Studio Professional 2019 Version 16.6.3 (I was using VS 2017) and this is working fine now.
Thanks
