### ISSUE TITLE
Add support for SSO / SAML

### ISSUE THREAD

**Issue by rlove** [aws/aws-toolkit-visual-studio#98]
_Update:_ A test build is available to try out! See https://github.com/aws/aws-toolkit-visual-studio/issues/98#issuecomment-809827673 for details.

---

**Is your feature request related to a problem? Please describe.**

I need a way to use "AWS Toolkit for Visual Studio" with SSO based credentials.   

We have an organizational policy that prevents the creation of an IAM user account for staff.   All staff accounts are managed through the SAML federation.

**Describe the solution you'd like**

Use the profiles that are set up in `~user/.aws/config` instead of an id/key pair.

*Example:*
Using CLI v2 you can run ` aws configure sso` which will set up required `config` entries to allow the use of the CLI with SSO. Then you can use `aws s3 ls --profile Profile-Name-Here`

**Describe alternatives you've considered**

Build architecture around containers instead of lambdas.   Since we will not need an Aws Toolkit.  To be honest we are so new to this we are really unsure of alternatives.

**Comment by awschristou** [comment]
Thank you for outlining your usage scenario @rlove . We're currently exploring some options for supporting SSO in the JetBrains Toolkit (including Rider). If/when those changes are complete, we'll see what we can apply to the Visual Studio Toolkit.

SAML support has been requested in #30, but I'll leave this issue as the request for SSO.

**Comment by ChrisDilts** [comment]
Proposing an alternative until support for SSO is built.
On the AWS SSO User portal page (https://<whatever>.awsapps.com/start), rather than select Management Console, select Command Line or Programmatic Access. That will generate Access Key / Secret Access Key / Session Token that you can use in your .aws/credentials file which you can use in VS.

**Comment by rlove** [comment]
I wonder if I can use the id/key/token from SSO that occurs with the CLI SSO login.   If I can then I might be able to write an automated script to take then from the cache and put them into credentials, which might be ideal workaround, as it's less manual steps to get up and running., each day.

I don't know the length of time for the temporary SSO cached credentials.   So this might not be an option.

**Comment by marcbesancenot** [comment]
+1 for this feature

**Comment by justinmk3** [comment]
@marcbesancenot consider adding your upvote 👍  to the main description so it will be counted when comparing requests in this project.

**Comment by scottblodgett** [comment]
> Proposing an alternative until support for SSO is built.
> On the AWS SSO User portal page (https://whatever.awsapps.com/start), rather than select Management Console, select Command Line or Programmatic Access. That will generate Access Key / Secret Access Key / Session Token that you can use in your .aws/credentials file which you can use in VS.

Unless I am missing something I don't think this will work. You need to be able to load the session token for SSO to work.

**Comment by annbrady** [comment]
As a workaround: install python3 + pip install aws-sso-credential-process

update your .aws/credential file

[profile-name]
credential_process=aws-sso-credential-process --profile profile-name
output=json
region=us-east-1
sso_account_id=targetaccountidthatyouseeonthessologin
sso_region=us-east-1
sso_role_name=targetrolethatyouseeonthessoconsole
sso_start_url=https://d-xxxxxx.awsapps.com/start/

**Comment by sc-alscient** [comment]
SSO is being worked on. See https://github.com/aws/aws-toolkit-vscode/pull/1304

**Comment by awschristou** [comment]
Hi @sc-alscient , the Toolkits team is investigating SSO support in the VS Code toolkit (seen in the PR you linked).

For the VS Toolkit, we've done some work to support SSO in the AWS SDK for .NET (https://github.com/aws/aws-sdk-net/pull/1701). This will help us investigate what would be needed to have the VS Toolkit support SSO.

**Comment by awschristou** [comment]
We've been working on adding support for credentials based on AWS SSO and MFA. We're not finished yet, but we're at the point where its worth sharing a test build and collecting some feedback.

Details on how to set yourself up with AWS SSO based credentials are identical to the instructions available in the [AWS Toolkit for VS Code User Guide](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/sso-credentials.html).
I don't have details for setting yourself up with MFA at this time.

Toolkit version: 1.20.1.6
sha 384: `096b9c42ca3011b8b776db9648d3be133edf089ff48631d9fe09aa4b6e420dd7076319e8a07cae6762823774a30d57cd`
Date: 2021/03/29
Toolkit: [AWSToolkitPackage.zip](https://github.com/aws/aws-toolkit-visual-studio/files/6225450/AWSToolkitPackage.zip)

If you try it out, please share what you tried to do in the Toolkit, and whether or not it worked for you.

Here's a quick demo of what the Toolkit looks like when you switch to an SSO based profile:
![sso-test-build](https://user-images.githubusercontent.com/39839589/112918280-63a46600-90b9-11eb-848d-68d24cc0ae03.gif)

**Comment by awschristou** [comment]
Version 1.21.0.0 of the Toolkit contains support for AWS SSO based credentials.

Details can be found at:
* Blog post: https://aws.amazon.com/blogs/developer/introducing-aws-toolkit-for-visual-studio-support-for-aws-sso-and-assume-role-with-mfa/
* User docs: https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/sso-credentials.html
